-- Chapter 04. 관계형 데이터베이스와 SQL 시작하기
-- 목적: 첫 테이블 생성, INSERT, SELECT, 조건, NULL, 정렬, UPDATE와 DELETE 기본 실습
-- 사용 방법: 파일 전체를 무조건 실행하지 말고 학습 중인 구간만 선택해 실행합니다.
-- 주의: 이 파일은 기존 public.students 테이블을 자동으로 삭제하지 않습니다.
-- 주의: 자동 커밋 상태에서는 변경 SQL이 실행 직후 확정될 수 있습니다.

-- ============================================================
-- 0. 현재 실행 위치 확인
-- 로컬 필수 경로의 기대 결과: ai_database_book / public
-- ============================================================
SELECT current_database();
SELECT current_schema();
SHOW search_path;

-- ============================================================
-- 1. students 테이블 생성
-- 같은 이름의 테이블이 이미 있다면 이 구간을 다시 실행하지 않습니다.
-- 처음부터 다시 시작해야 할 때만 reset_students.sql을 별도로 실행합니다.
-- ============================================================
CREATE TABLE public.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    major VARCHAR(100),
    grade INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 2. 단일 행 입력과 자동 생성값 확인
-- IDENTITY 값은 빈틈없는 순번을 보장하지 않습니다.
-- CURRENT_TIMESTAMP는 현재 트랜잭션의 시작 시각을 반환합니다.
-- ============================================================
INSERT INTO public.students (name, email, major, grade)
VALUES ('김민지', 'minji@example.com', '컴퓨터공학', 2)
RETURNING id, name, created_at;

-- ============================================================
-- 3. 여러 행 입력
-- ============================================================
INSERT INTO public.students (name, email, major, grade)
VALUES
    ('이준호', 'junho@example.com', '데이터사이언스', 3),
    ('박서연', 'seoyeon@example.com', '경영학', 1),
    ('최현우', 'hyunwoo@example.com', '컴퓨터공학', 4),
    ('정하늘', 'haneul@example.com', 'AI데이터공학', 2);

-- major와 grade를 생략해 NULL 값 확인
INSERT INTO public.students (name, email)
VALUES ('윤서진', 'seojin@example.com');

-- 데이터 상태 체크포인트 A
-- 정상적으로 처음 실행했다면 6행입니다.
-- id의 최댓값이 6이라는 의미는 아닙니다.
SELECT COUNT(*) AS student_count
FROM public.students;

-- ============================================================
-- 4. 전체 열과 필요한 열 조회
-- ORDER BY가 없으면 반환 행의 순서는 보장되지 않습니다.
-- ============================================================
SELECT *
FROM public.students;

SELECT id, name, email, major
FROM public.students
ORDER BY id ASC;

SELECT
    name AS student_name,
    major AS student_major
FROM public.students
ORDER BY id ASC;

-- ============================================================
-- 5. WHERE와 비교 연산자
-- ============================================================
SELECT *
FROM public.students
WHERE major = '컴퓨터공학'
ORDER BY id ASC;

SELECT *
FROM public.students
WHERE grade >= 3
ORDER BY grade DESC, id ASC;

-- major가 NULL인 행은 포함되지 않습니다.
SELECT *
FROM public.students
WHERE major <> '경영학'
ORDER BY id ASC;

-- NULL도 경영학이 아닌 대상으로 포함하는 방법
SELECT *
FROM public.students
WHERE major <> '경영학'
   OR major IS NULL
ORDER BY id ASC;

-- PostgreSQL의 NULL 안전 비교
SELECT *
FROM public.students
WHERE major IS DISTINCT FROM '경영학'
ORDER BY id ASC;

-- ============================================================
-- 6. AND, OR, IN과 괄호
-- ============================================================
SELECT *
FROM public.students
WHERE major = '컴퓨터공학'
  AND grade >= 3
ORDER BY id ASC;

SELECT *
FROM public.students
WHERE major = '컴퓨터공학'
   OR major = '데이터사이언스'
ORDER BY id ASC;

SELECT *
FROM public.students
WHERE major IN ('컴퓨터공학', '데이터사이언스')
ORDER BY id ASC;

SELECT *
FROM public.students
WHERE major = '컴퓨터공학'
  AND (grade = 2 OR grade = 3)
ORDER BY id ASC;

-- ============================================================
-- 7. LIKE와 ILIKE 문자열 검색
-- %는 0개 이상의 문자, _는 정확히 한 문자를 의미합니다.
-- ILIKE는 PostgreSQL의 대소문자 비구분 패턴 검색입니다.
-- ============================================================
SELECT *
FROM public.students
WHERE name LIKE '김%'
ORDER BY id ASC;

SELECT *
FROM public.students
WHERE name LIKE '%민%'
ORDER BY id ASC;

SELECT *
FROM public.students
WHERE name LIKE '김__'
ORDER BY id ASC;

SELECT *
FROM public.students
WHERE email ILIKE '%EXAMPLE.COM'
ORDER BY id ASC;

-- ============================================================
-- 8. NULL 확인
-- NULL은 = NULL 또는 <> NULL로 비교하지 않습니다.
-- ============================================================
SELECT *
FROM public.students
WHERE major IS NULL
ORDER BY id ASC;

SELECT *
FROM public.students
WHERE grade IS NULL
ORDER BY id ASC;

SELECT *
FROM public.students
WHERE major IS NOT NULL
ORDER BY id ASC;

-- 잘못된 예: 문법 오류가 아닐 수 있지만 조건 결과가 UNKNOWN이 되어
-- 일반적으로 0행이 반환됩니다.
-- SELECT *
-- FROM public.students
-- WHERE major = NULL;

-- ============================================================
-- 9. ORDER BY와 LIMIT
-- PostgreSQL에서 DESC 기본 정렬은 NULL이 앞에 올 수 있으므로
-- 의도가 중요하면 NULLS LAST를 직접 지정합니다.
-- ============================================================
SELECT *
FROM public.students
ORDER BY grade ASC NULLS LAST, id ASC;

SELECT *
FROM public.students
ORDER BY grade DESC NULLS LAST, id ASC;

-- created_at이 같을 수 있으므로 id를 보조 정렬 기준으로 사용합니다.
SELECT *
FROM public.students
ORDER BY created_at DESC, id DESC
LIMIT 3;

-- 실행 전 예상
-- 반환 열: name, grade
-- 조건: grade >= 3
-- 정렬: grade 내림차순, 같은 학년이면 id 오름차순
-- 체크포인트 A 예상 학생: 최현우, 이준호
SELECT name, grade
FROM public.students
WHERE grade >= 3
ORDER BY grade DESC, id ASC;

-- ============================================================
-- 10. UPDATE 전후 확인
-- SELECT → UPDATE RETURNING → 영향받은 행 수 확인 → SELECT 순서로 실행합니다.
-- 자동 커밋 상태에서는 실행 직후 변경이 확정될 수 있습니다.
-- ============================================================
SELECT *
FROM public.students
WHERE email = 'junho@example.com';

UPDATE public.students
SET grade = 4
WHERE email = 'junho@example.com'
RETURNING id, name, grade;

SELECT *
FROM public.students
WHERE email = 'junho@example.com';

-- 데이터 상태 체크포인트 B
-- 학생 수 6명, 이준호 grade 4, 박서연 존재

-- ============================================================
-- 11. DELETE 전후 확인
-- SELECT → DELETE RETURNING → 영향받은 행 수 확인 → SELECT 순서로 실행합니다.
-- ============================================================
SELECT *
FROM public.students
WHERE email = 'seoyeon@example.com';

DELETE FROM public.students
WHERE email = 'seoyeon@example.com'
RETURNING id, name, email;

SELECT *
FROM public.students
WHERE email = 'seoyeon@example.com';

-- 데이터 상태 체크포인트 C
-- 정상적으로 한 행이 삭제되었다면 5행입니다.
SELECT COUNT(*) AS remaining_student_count
FROM public.students;

-- ============================================================
-- 12. AI 생성 SQL 검토용 예시
-- 아래 DELETE는 실행하지 않습니다.
-- 체크포인트 C 기준 컴퓨터공학 학생은 김민지와 최현우 두 명입니다.
-- ============================================================
SELECT id, name, email, major
FROM public.students
WHERE major = '컴퓨터공학'
ORDER BY id ASC;

-- 실행하지 않는 가상 예시
-- DELETE FROM public.students
-- WHERE major = '컴퓨터공학';

-- ============================================================
-- 13. 위험한 SQL 검토용 예시
-- 아래 SQL은 실행하지 않습니다.
-- ============================================================

-- 모든 학생의 학년을 1로 변경합니다.
-- UPDATE public.students
-- SET grade = 1;

-- public.students 테이블의 모든 행을 삭제합니다.
-- DELETE FROM public.students;

-- NULL 비교의 잘못된 예입니다.
-- SELECT *
-- FROM public.students
-- WHERE major = NULL;
