-- Chapter 04. 관계형 데이터베이스와 SQL 시작하기
-- 목적: 첫 테이블 생성, INSERT, SELECT, 조건, NULL, 정렬, UPDATE와 DELETE 기본 실습
-- 사용 방법: 파일 전체를 무조건 실행하지 말고 학습 중인 구간만 선택해 실행합니다.
-- 주의: 이 파일은 기존 students 테이블을 자동으로 삭제하지 않습니다.

-- ============================================================
-- 0. 현재 실행 위치 확인
-- 기대 결과: ai_database_book / public
-- ============================================================
SELECT current_database();
SELECT current_schema();

-- ============================================================
-- 1. students 테이블 생성
-- 같은 이름의 테이블이 이미 있다면 이 구간을 다시 실행하지 않습니다.
-- 처음부터 다시 시작해야 할 때만 reset_students.sql을 별도로 실행합니다.
-- ============================================================
CREATE TABLE students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    major VARCHAR(100),
    grade INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 2. 단일 행 입력과 자동 생성값 확인
-- ============================================================
INSERT INTO students (name, email, major, grade)
VALUES ('김민지', 'minji@example.com', '컴퓨터공학', 2)
RETURNING id, name, created_at;

-- ============================================================
-- 3. 여러 행 입력
-- ============================================================
INSERT INTO students (name, email, major, grade)
VALUES
    ('이준호', 'junho@example.com', '데이터사이언스', 3),
    ('박서연', 'seoyeon@example.com', '경영학', 1),
    ('최현우', 'hyunwoo@example.com', '컴퓨터공학', 4),
    ('정하늘', 'haneul@example.com', 'AI데이터공학', 2);

-- major와 grade를 생략해 NULL 값 확인
INSERT INTO students (name, email)
VALUES ('윤서진', 'seojin@example.com');

-- 입력된 행 수 확인
-- 정상적으로 처음 실행했다면 6행
SELECT COUNT(*) AS student_count
FROM students;

-- ============================================================
-- 4. 전체 열과 필요한 열 조회
-- ============================================================
SELECT *
FROM students;

SELECT name, email, major
FROM students;

SELECT
    name AS student_name,
    major AS student_major
FROM students;

-- ============================================================
-- 5. WHERE와 비교 연산자
-- ============================================================
SELECT *
FROM students
WHERE major = '컴퓨터공학';

SELECT *
FROM students
WHERE grade >= 3;

SELECT *
FROM students
WHERE major <> '경영학';

-- ============================================================
-- 6. AND, OR, IN과 괄호
-- ============================================================
SELECT *
FROM students
WHERE major = '컴퓨터공학'
  AND grade >= 3;

SELECT *
FROM students
WHERE major = '컴퓨터공학'
   OR major = '데이터사이언스';

SELECT *
FROM students
WHERE major IN ('컴퓨터공학', '데이터사이언스');

SELECT *
FROM students
WHERE major = '컴퓨터공학'
  AND (grade = 2 OR grade = 3);

-- ============================================================
-- 7. LIKE와 ILIKE 문자열 검색
-- ============================================================
SELECT *
FROM students
WHERE name LIKE '김%';

SELECT *
FROM students
WHERE name LIKE '%민%';

SELECT *
FROM students
WHERE email ILIKE '%EXAMPLE.COM';

-- ============================================================
-- 8. NULL 확인
-- NULL은 = NULL로 비교하지 않습니다.
-- ============================================================
SELECT *
FROM students
WHERE major IS NULL;

SELECT *
FROM students
WHERE grade IS NULL;

SELECT *
FROM students
WHERE major IS NOT NULL;

-- 잘못된 예: 원하는 결과가 나오지 않습니다.
-- SELECT *
-- FROM students
-- WHERE major = NULL;

-- ============================================================
-- 9. ORDER BY와 LIMIT
-- ============================================================
SELECT *
FROM students
ORDER BY grade ASC NULLS LAST;

SELECT *
FROM students
ORDER BY grade DESC NULLS LAST;

SELECT *
FROM students
ORDER BY created_at DESC
LIMIT 3;

-- 실행 전 예상:
-- 반환 열: name, grade
-- 조건: grade >= 3
-- 정렬: grade 내림차순
-- 예상 학생: 최현우, 이준호
SELECT name, grade
FROM students
WHERE grade >= 3
ORDER BY grade DESC;

-- ============================================================
-- 10. UPDATE 전후 확인
-- 이 구간은 SELECT → UPDATE → SELECT 순서대로 실행합니다.
-- ============================================================
SELECT *
FROM students
WHERE email = 'junho@example.com';

UPDATE students
SET grade = 4
WHERE email = 'junho@example.com'
RETURNING id, name, grade;

SELECT *
FROM students
WHERE email = 'junho@example.com';

-- ============================================================
-- 11. DELETE 전후 확인
-- 이 구간은 SELECT → DELETE → SELECT 순서대로 실행합니다.
-- ============================================================
SELECT *
FROM students
WHERE email = 'seoyeon@example.com';

DELETE FROM students
WHERE email = 'seoyeon@example.com'
RETURNING id, name, email;

SELECT *
FROM students
WHERE email = 'seoyeon@example.com';

-- 삭제 후 전체 행 수 확인
-- 정상적으로 한 행이 삭제되었다면 5행
SELECT COUNT(*) AS remaining_student_count
FROM students;

-- ============================================================
-- 12. 위험한 SQL 검토용 예시
-- 아래 SQL은 실행하지 않습니다.
-- ============================================================

-- 모든 학생의 학년을 1로 변경합니다.
-- UPDATE students
-- SET grade = 1;

-- students 테이블의 모든 행을 삭제합니다.
-- DELETE FROM students;

-- NULL 비교의 잘못된 예입니다.
-- SELECT *
-- FROM students
-- WHERE major = NULL;
