window.CH4_TITLE="Chapter 04 이론 강의";
window.CH4_SLIDES=[
  {
    "k": "CHAPTER 04 · THEORY",
    "l": "이론 강의",
    "h": "<h1>관계형 데이터베이스와<br>SQL 시작하기</h1><p class=\"lead\">이론 강의에서는 첫 테이블과 CRUD SQL을 실행하기 전에 핵심 개념과 검증 기준을 정리합니다.</p><div class=\"title-meta\"><span class=\"pill\">CREATE TABLE</span><span class=\"pill\">CRUD</span><span class=\"pill\">NULL</span><span class=\"pill\">검증 습관</span></div>",
    "s": "안녕하세요. 4장은 관계형 데이터베이스와 에스큐엘을 실제로 시작하는 장입니다. 이번 장부터 처음으로 테이블을 만들고 데이터를 입력하고 조회하고 수정하고 삭제합니다. 이론 강의에서는 바로 코드를 실행하기보다, 어떤 순서로 실행해야 안전한지, 각 명령이 어떤 역할을 하는지, 실행 전후에 무엇을 확인해야 하는지 먼저 정리하겠습니다."
  },
  {
    "k": "WHERE WE ARE",
    "l": "전체 과정 속 위치",
    "h": "<h2>4장은 첫 SQL 실행과<br>CRUD 실습의 시작점입니다</h2><div class=\"flow\"><div class=\"flow-step done\">2장<br>기본 용어</div><div class=\"flow-arrow\">→</div><div class=\"flow-step done\">3장<br>설치·연결</div><div class=\"flow-arrow\">→</div><div class=\"flow-step current\">4장<br>Table·CRUD</div><div class=\"flow-arrow\">→</div><div class=\"flow-step\">5장<br>요구사항·ERD</div></div>",
    "s": "전체 과정에서 4장의 위치를 확인하겠습니다. 2장에서 데이터베이스 기본 용어를 배웠고, 3장에서 포스트그레스큐엘과 디비버 연결을 준비했습니다. 이제 4장에서는 처음으로 학생 테이블을 만들고, 데이터를 직접 입력하고, 조회하고, 수정하고, 삭제합니다. 5장부터는 여러 테이블과 관계를 설계하는 흐름으로 넘어갑니다."
  },
  {
    "k": "CHAPTER GOAL",
    "l": "학습 목표",
    "h": "<h2>목표는 문법 암기가 아니라<br>예상과 실제 결과 비교입니다</h2><ul class=\"bullet-list\"><li>현재 Database·Schema·search_path를 확인한다.</li><li>public.students Table을 생성한다.</li><li>INSERT, SELECT, UPDATE, DELETE를 구분한다.</li><li>NULL과 ORDER BY의 주의점을 설명한다.</li><li>변경 SQL의 영향받은 Row 수를 확인한다.</li></ul>",
    "s": "이번 장의 목표는 에스큐엘 문법을 많이 외우는 것이 아닙니다. 더 중요한 목표는 실행 전에 결과를 예상하고, 실행 후 실제 결과와 비교하는 습관을 만드는 것입니다. 현재 데이터베이스와 스키마, 검색 경로를 확인하고, 퍼블릭 스튜던츠 테이블을 만들고, 인서트, 셀렉트, 업데이트, 딜리트를 구분합니다. 또한 널과 오더 바이의 주의점, 변경 에스큐엘의 영향받은 행 수를 확인합니다."
  },
  {
    "k": "LEARNING LOOP",
    "l": "검증 순환",
    "h": "<h2>SQL은 실행 전후를<br>비교하면서 배웁니다</h2><div class=\"flow\"><div class=\"flow-step\">SQL 읽기</div><div class=\"flow-arrow\">→</div><div class=\"flow-step\">결과 예상</div><div class=\"flow-arrow\">→</div><div class=\"flow-step\">실행</div><div class=\"flow-arrow\">→</div><div class=\"flow-step current\">결과 비교</div></div><div class=\"quote\">실행 성공 ≠ 올바른 결과</div>",
    "s": "이 장에서 반복할 학습 순환입니다. 먼저 에스큐엘을 읽습니다. 그다음 어떤 열이 나오고 몇 행이 반환될지 예상합니다. 그다음 실행합니다. 마지막으로 실제 결과가 예상과 맞는지 비교합니다. 실행이 성공했다는 사실만으로 결과가 올바르다고 판단하지 않습니다. 반환된 행 수, 영향받은 행 수, 정렬 기준, 널 처리까지 함께 확인해야 합니다."
  },
  {
    "k": "TABLE SCOPE",
    "l": "실습 대상",
    "h": "<h2>이번 장의 실습 대상은<br>public.students입니다</h2><div class=\"table-wrap\"><table><thead><tr><th>구분</th><th>내용</th></tr></thead><tbody><tr><td>Table</td><td>students</td></tr><tr><td>Schema</td><td>public</td></tr><tr><td>한 Row</td><td>학생 한 명</td></tr><tr><td>Columns</td><td>id, name, email, major, grade, created_at</td></tr><tr><td>PK</td><td>id</td></tr></tbody></table></div>",
    "s": "이번 장에서 사용할 테이블은 퍼블릭 스튜던츠입니다. 스키마는 퍼블릭이고, 테이블 이름은 스튜던츠입니다. 이 테이블에서 한 행은 학생 한 명을 의미합니다. 열은 아이디, 이름, 이메일, 전공, 학년, 등록 시각입니다. 기본키는 아이디입니다. 이후 장에서는 여러 테이블로 확장하지만, 4장에서는 하나의 테이블로 기본 에스큐엘을 연습합니다."
  },
  {
    "k": "CRUD OVERVIEW",
    "l": "CRUD와 SQL",
    "h": "<h2>CRUD는 서비스 기능과<br>SQL 명령으로 연결됩니다</h2><div class=\"table-wrap\"><table><thead><tr><th>CRUD</th><th>SQL</th><th>서비스 기능 예시</th></tr></thead><tbody><tr><td>Create</td><td>INSERT</td><td>학생 등록</td></tr><tr><td>Read</td><td>SELECT</td><td>학생 목록 확인</td></tr><tr><td>Update</td><td>UPDATE</td><td>학생 정보 변경</td></tr><tr><td>Delete</td><td>DELETE</td><td>학생 정보 삭제</td></tr></tbody></table></div>",
    "s": "크러드는 애플리케이션에서 반복되는 네 가지 기본 데이터 작업입니다. 크리에이트는 새 행을 추가하는 작업이고 인서트에 해당합니다. 리드는 저장된 데이터를 조회하는 작업이고 셀렉트에 해당합니다. 업데이트는 기존 행을 수정하는 작업입니다. 딜리트는 기존 행을 삭제하는 작업입니다. 여기서 주의할 점은 크러드의 크리에이트가 크리에이트 테이블이 아니라 데이터 행 추가라는 것입니다."
  },
  {
    "k": "EXECUTION LOCATION",
    "l": "실행 위치",
    "h": "<h2>SQL 실행 전에는<br>위치를 먼저 확인합니다</h2><pre>SELECT current_database();\nSELECT current_schema();\nSHOW search_path;</pre><p class=\"body-text\">다른 Database나 Schema에 Table을 만들지 않도록 먼저 확인합니다.</p>",
    "s": "에스큐엘 실행 전에는 위치를 먼저 확인합니다. 커런트 데이터베이스, 커런트 스키마, 쇼 서치 패스를 실행합니다. 이 장의 기준 데이터베이스는 에이아이 데이터베이스 북입니다. 스키마는 퍼블릭을 기준으로 합니다. 위치를 확인하지 않으면 다른 데이터베이스나 다른 스키마에 테이블을 만들 수 있습니다."
  },
  {
    "k": "CREATE TABLE",
    "l": "Table 생성",
    "h": "<h2>CREATE TABLE은<br>데이터가 들어갈 구조를 만듭니다</h2><pre>CREATE TABLE public.students (\n    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    name VARCHAR(50) NOT NULL,\n    email VARCHAR(100) UNIQUE NOT NULL,\n    major VARCHAR(100),\n    grade INTEGER,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP\n);</pre>",
    "s": "크리에이트 테이블은 데이터를 넣는 명령이 아니라 데이터가 들어갈 구조를 만드는 명령입니다. 화면의 에스큐엘은 퍼블릭 스키마에 스튜던츠 테이블을 만듭니다. 아이디는 자동 생성되는 정수 기본키입니다. 이름과 이메일은 필수값입니다. 이메일은 유니크로 중복을 막습니다. 전공과 학년은 선택값이므로 널이 들어갈 수 있습니다. 등록 시각은 현재 타임스탬프를 기본값으로 사용합니다."
  },
  {
    "k": "COLUMN MEANING",
    "l": "Column 읽기",
    "h": "<h2>Column은 타입과 규칙을<br>함께 읽어야 합니다</h2><div class=\"table-wrap\"><table><thead><tr><th>Column</th><th>Type</th><th>Rule</th><th>역할</th></tr></thead><tbody><tr><td>id</td><td>INTEGER</td><td>IDENTITY PK</td><td>내부 식별자</td></tr><tr><td>name</td><td>VARCHAR(50)</td><td>NOT NULL</td><td>학생 이름</td></tr><tr><td>email</td><td>VARCHAR(100)</td><td>UNIQUE NOT NULL</td><td>학생 이메일</td></tr><tr><td>major</td><td>VARCHAR(100)</td><td>선택</td><td>전공</td></tr><tr><td>grade</td><td>INTEGER</td><td>선택</td><td>학년</td></tr></tbody></table></div>",
    "s": "열은 이름만 보는 것이 아니라 데이터 타입과 규칙을 함께 읽어야 합니다. 아이디는 정수이고 아이덴티티와 기본키 규칙이 있습니다. 이름은 문자열이고 반드시 입력해야 합니다. 이메일도 문자열이고 반드시 입력해야 하며 중복될 수 없습니다. 전공과 학년은 낫 널이 없으므로 입력하지 않으면 널이 저장될 수 있습니다. 이 구조는 기본 에스큐엘 학습을 위한 최소 구조입니다."
  },
  {
    "k": "IDENTITY",
    "l": "자동 번호",
    "h": "<h2>IDENTITY 값은<br>빈틈없는 순번이 아닙니다</h2><div class=\"quote\">id는 Row 식별자입니다.<br>현재 학생 수나 완벽한 순번이 아닙니다.</div><p class=\"body-text\">입력 실패, 삭제, 취소 등으로 번호 공백이 생길 수 있습니다.</p>",
    "s": "아이덴티티 값은 행을 고유하게 구분하기 위한 값입니다. 현재 학생 수나 빈틈없는 순번이 아닙니다. 입력 실패, 삭제, 트랜잭션 취소 등으로 번호에 공백이 생길 수 있습니다. 따라서 아이디가 6이라고 해서 반드시 학생이 6명이라고 판단하면 안 됩니다. 학생 수는 카운트로 확인해야 합니다."
  },
  {
    "k": "CURRENT TIMESTAMP",
    "l": "등록 시각",
    "h": "<h2>CURRENT_TIMESTAMP는<br>현재 트랜잭션 기준 시각입니다</h2><div class=\"grid-2\"><article class=\"card\"><h3>TIMESTAMPTZ</h3><p>시간대 정보를 고려하는 날짜와 시각 타입</p></article><article class=\"card emphasis\"><h3>DEFAULT CURRENT_TIMESTAMP</h3><p>값을 생략하면 등록 시각 자동 입력</p></article></div>",
    "s": "티아이엠이에스티에이엠피티제트, 즉 타임스탬프 위드 타임존은 시간대 정보를 고려하는 날짜와 시각 타입입니다. 디폴트 커런트 타임스탬프는 값을 생략하면 현재 트랜잭션 기준 시각을 자동으로 넣습니다. 같은 문장이나 같은 트랜잭션에서 여러 행을 입력하면 등록 시각이 같을 수 있으므로 최신 행 정렬에서는 아이디 같은 보조 기준을 함께 사용하는 것이 좋습니다."
  },
  {
    "k": "INSERT",
    "l": "행 추가",
    "h": "<h2>INSERT는 Table에<br>새 Row를 추가합니다</h2><pre>INSERT INTO public.students (name, email, major, grade)\nVALUES ('김민지', 'minji@example.com', '컴퓨터공학', 2)\nRETURNING id, name, created_at;</pre><p class=\"body-text\">RETURNING으로 자동 생성된 id와 created_at을 바로 확인합니다.</p>",
    "s": "인서트는 테이블에 새 행을 추가합니다. 문자열은 작은따옴표로 감싸고 숫자는 따옴표 없이 입력합니다. 아이디와 등록 시각은 직접 입력하지 않았지만 포스트그레스큐엘이 생성합니다. 리터닝을 사용하면 인서트 직후 별도의 셀렉트 없이 실제로 추가된 행과 자동 생성값을 확인할 수 있습니다."
  },
  {
    "k": "SELECT",
    "l": "데이터 조회",
    "h": "<h2>SELECT는 필요한 데이터를<br>조회합니다</h2><div class=\"grid-2\"><article class=\"card\"><h3>모든 Column</h3><pre>SELECT *\nFROM public.students;</pre></article><article class=\"card emphasis\"><h3>필요한 Column</h3><pre>SELECT name, email, major\nFROM public.students;</pre></article></div>",
    "s": "셀렉트는 테이블의 데이터를 조회합니다. 별표는 모든 열을 의미합니다. 초급 실습에서는 편리하지만 실제 분석이나 애플리케이션에서는 필요한 열만 명시하는 것이 좋습니다. 조회 결과를 확인할 때는 어떤 열이 반환되었는지, 몇 개의 행이 반환되었는지, 오더 바이가 있는지, 예상한 값과 실제 값이 일치하는지 봅니다."
  },
  {
    "k": "ORDER WARNING",
    "l": "순서 주의",
    "h": "<h2>ORDER BY가 없으면<br>Row 순서는 보장되지 않습니다</h2><div class=\"quote\">보이는 순서 ≠ 약속된 순서</div><pre>SELECT id, name, email, major\nFROM public.students\nORDER BY id ASC;</pre>",
    "s": "오더 바이가 없는 조회 결과의 행 순서는 보장되지 않습니다. 입력한 순서나 아이디 순서로 보일 수 있지만 그 순서에 의존하면 안 됩니다. 순서가 필요하면 반드시 오더 바이를 명시합니다. 화면 예시는 아이디 오름차순으로 정렬합니다. 보이는 순서와 약속된 순서는 다르다는 점을 기억해야 합니다."
  },
  {
    "k": "WHERE",
    "l": "조건 조회",
    "h": "<h2>WHERE는 조건에 맞는 Row만<br>선택합니다</h2><pre>SELECT *\nFROM public.students\nWHERE major = '컴퓨터공학'\nORDER BY id ASC;</pre><p class=\"body-text\">문자열은 작은따옴표, 숫자는 따옴표 없이 비교합니다.</p>",
    "s": "웨어는 조건에 맞는 행만 선택합니다. 전공이 컴퓨터공학인 학생을 조회하려면 메이저 이퀄 컴퓨터공학 조건을 사용합니다. 문자열 값은 작은따옴표로 감싸야 합니다. 학년처럼 정수 타입인 값은 따옴표 없이 비교합니다. 조건을 읽을 때는 어떤 열을 어떤 값과 비교하는지 먼저 확인합니다."
  },
  {
    "k": "AND OR IN",
    "l": "조건 조합",
    "h": "<h2>AND, OR, IN은<br>조건을 조합합니다</h2><div class=\"grid-3\"><article class=\"card\"><h3>AND</h3><p>모든 조건이 참</p></article><article class=\"card\"><h3>OR</h3><p>하나 이상이 참</p></article><article class=\"card emphasis\"><h3>IN</h3><p>여러 후보값 중 하나</p></article></div><p class=\"body-text\">AND와 OR를 함께 쓸 때는 괄호로 의도를 명확히 합니다.</p>",
    "s": "앤드는 모든 조건이 참인 행을 선택합니다. 오는 조건 중 하나 이상이 참인 행을 선택합니다. 인은 같은 열을 여러 후보값과 비교할 때 읽기 쉽게 사용할 수 있습니다. 앤드와 오알을 함께 사용하면 괄호로 의도를 명확히 표현하는 것이 좋습니다. 괄호를 생략해도 문법 오류가 나지 않을 수 있지만 사람이 의도한 범위와 다르게 읽히기 쉽습니다."
  },
  {
    "k": "LIKE ILIKE",
    "l": "문자열 검색",
    "h": "<h2>LIKE와 ILIKE는<br>문자열 패턴 검색에 사용합니다</h2><div class=\"table-wrap\"><table><thead><tr><th>패턴</th><th>의미</th></tr></thead><tbody><tr><td>'김%'</td><td>김으로 시작</td></tr><tr><td>'%민%'</td><td>중간에 민 포함</td></tr><tr><td>'%우'</td><td>우로 끝남</td></tr><tr><td>'김__'</td><td>김 뒤 정확히 두 글자</td></tr></tbody></table></div>",
    "s": "라이크는 문자열의 일부가 일치하는 행을 찾을 때 사용합니다. 퍼센트 기호는 길이에 상관없이 영 개 이상의 문자를 의미합니다. 언더스코어는 정확히 한 문자를 의미합니다. 포스트그레스큐엘에서 대소문자를 구분하지 않는 패턴 검색이 필요하면 아이라이크를 사용할 수 있습니다. 다만 아이라이크는 포스트그레스큐엘 문법이므로 다른 디비엠에스에서는 다를 수 있습니다."
  },
  {
    "k": "NULL",
    "l": "NULL 주의",
    "h": "<h2>NULL은 0이나 빈 문자열이 아닙니다</h2><div class=\"quote\">NULL = 값이 없거나<br>아직 알려지지 않은 상태</div><div class=\"grid-2\"><article class=\"card\"><h3>잘못된 비교</h3><pre>WHERE major = NULL</pre></article><article class=\"card emphasis\"><h3>올바른 확인</h3><pre>WHERE major IS NULL</pre></article></div>",
    "s": "널은 숫자 영이나 빈 문자열이 아닙니다. 값이 없거나 아직 알려지지 않은 상태입니다. 메이저 이퀄 널은 문법 오류가 아닐 수 있지만 원하는 행을 반환하지 않습니다. 일반 비교에서 널과 비교하면 참이나 거짓이 아니라 언노운이 됩니다. 널 여부는 이즈 널 또는 이즈 낫 널로 확인해야 합니다."
  },
  {
    "k": "ORDER LIMIT",
    "l": "정렬과 제한",
    "h": "<h2>ORDER BY와 LIMIT은<br>함께 안정적으로 사용합니다</h2><pre>SELECT *\nFROM public.students\nORDER BY grade DESC NULLS LAST, id ASC;</pre><pre>SELECT *\nFROM public.students\nORDER BY created_at DESC, id DESC\nLIMIT 3;</pre>",
    "s": "오더 바이는 조회 결과의 순서를 정하고, 리밋은 그중 몇 행을 가져올지 정합니다. 학년으로 정렬할 때 널을 마지막에 두려면 널스 라스트를 사용합니다. 최신 세 명을 조회할 때는 크리에이티드 앳 내림차순뿐 아니라 아이디 내림차순도 보조 기준으로 사용합니다. 동률이 가능한 정렬에서는 보조 정렬 기준이 중요합니다."
  },
  {
    "k": "UPDATE SAFETY",
    "l": "안전한 UPDATE",
    "h": "<h2>UPDATE는 SELECT로<br>대상 확인 후 실행합니다</h2><div class=\"flow\"><div class=\"flow-step\">SELECT<br>대상 확인</div><div class=\"flow-arrow\">→</div><div class=\"flow-step\">UPDATE<br>RETURNING</div><div class=\"flow-arrow\">→</div><div class=\"flow-step current\">영향 Row 수<br>확인</div><div class=\"flow-arrow\">→</div><div class=\"flow-step\">SELECT<br>재확인</div></div>",
    "s": "업데이트는 기존 행의 값을 수정합니다. 안전하게 실행하려면 먼저 같은 조건으로 셀렉트해서 대상 행을 확인합니다. 그다음 업데이트를 실행하고 리터닝 결과를 확인합니다. 디비버의 실행 결과나 상태 표시에서 영향받은 행 수가 예상과 같은지도 확인합니다. 마지막으로 다시 셀렉트를 실행해 실제 값이 바뀌었는지 재확인합니다."
  },
  {
    "k": "DELETE SAFETY",
    "l": "안전한 DELETE",
    "h": "<h2>DELETE도 SELECT로<br>대상 확인 후 실행합니다</h2><div class=\"flow\"><div class=\"flow-step\">SELECT<br>삭제 대상 확인</div><div class=\"flow-arrow\">→</div><div class=\"flow-step\">DELETE<br>RETURNING</div><div class=\"flow-arrow\">→</div><div class=\"flow-step current\">영향 Row 수<br>확인</div><div class=\"flow-arrow\">→</div><div class=\"flow-step\">SELECT<br>0행 확인</div></div>",
    "s": "딜리트는 테이블에서 행을 삭제합니다. 안전한 흐름은 업데이트와 비슷합니다. 먼저 셀렉트로 삭제 대상을 확인합니다. 그 다음 딜리트 리터닝을 실행합니다. 리터닝 결과가 예상한 한 행인지 확인하고, 영향받은 행 수가 일인지 확인합니다. 마지막으로 같은 조건으로 다시 셀렉트해서 결과가 영 행인지 확인합니다."
  },
  {
    "k": "CHECKPOINTS",
    "l": "데이터 상태",
    "h": "<h2>실습 데이터 상태는<br>체크포인트로 구분합니다</h2><div class=\"table-wrap\"><table><thead><tr><th>체크포인트</th><th>학생 수</th><th>이준호 학년</th><th>박서연</th></tr></thead><tbody><tr><td>A 입력 완료</td><td>6</td><td>3</td><td>존재</td></tr><tr><td>B UPDATE 완료</td><td>6</td><td>4</td><td>존재</td></tr><tr><td>C DELETE 완료</td><td>5</td><td>4</td><td>삭제</td></tr></tbody></table></div>",
    "s": "실습 중 데이터 상태가 계속 바뀌기 때문에 체크포인트를 구분해야 합니다. 체크포인트 에이는 입력이 완료된 상태입니다. 학생 수는 여섯 명이고 이준호 학년은 삼 학년이며 박서연은 존재합니다. 체크포인트 비는 업데이트 완료 상태입니다. 학생 수는 그대로 여섯 명이고 이준호 학년은 사 학년입니다. 체크포인트 씨는 딜리트 완료 상태입니다. 학생 수는 다섯 명이고 박서연은 삭제되었습니다."
  },
  {
    "k": "AI SQL REVIEW",
    "l": "AI SQL 검토",
    "h": "<h2>AI가 만든 SQL은<br>실행 전에 영향 범위를 검토합니다</h2><ul class=\"bullet-list\"><li>현재 데이터 상태가 어느 체크포인트인가?</li><li>대상 Table과 Column이 맞는가?</li><li>WHERE 조건이 충분히 좁은가?</li><li>NULL과 정렬 기준을 고려했는가?</li><li>변경 SQL을 바로 실행해도 안전한가?</li></ul>",
    "s": "에이아이가 만든 에스큐엘은 실행 전에 영향 범위를 검토해야 합니다. 현재 데이터 상태가 어느 체크포인트인지 먼저 확인합니다. 대상 테이블과 열이 맞는지 봅니다. 웨어 조건이 충분히 좁은지 확인합니다. 널과 정렬 기준을 고려했는지도 확인합니다. 특히 업데이트나 딜리트 같은 변경 에스큐엘은 바로 실행하지 않고 먼저 셀렉트로 대상 행을 확인해야 합니다."
  },
  {
    "k": "SUMMARY",
    "l": "핵심 정리",
    "h": "<h2>4장의 핵심</h2><div class=\"quote\">SQL은 문법만 실행하는 것이 아니라<br>예상 결과와 실제 결과를 비교하는 과정입니다.</div><ul class=\"bullet-list\"><li>위치 확인 후 실행한다.</li><li>ORDER BY 없는 순서를 믿지 않는다.</li><li>NULL은 IS NULL로 확인한다.</li><li>UPDATE·DELETE 전에는 SELECT로 범위를 확인한다.</li></ul>",
    "s": "4장의 핵심을 정리하겠습니다. 에스큐엘은 문법만 실행하는 것이 아니라 예상 결과와 실제 결과를 비교하는 과정입니다. 실행 전에는 위치를 확인합니다. 오더 바이가 없는 순서를 믿지 않습니다. 널은 이즈 널로 확인합니다. 업데이트와 딜리트 전에는 반드시 셀렉트로 범위를 확인합니다. 이 습관이 이후 조인, 집계, 트랜잭션, 에이아이 에스큐엘 검증까지 계속 이어집니다."
  }
];
