window.CH4_TITLE="Chapter 04 실습 강의";
window.CH4_SLIDES=[
  {
    "k": "CHAPTER 04 · PRACTICE",
    "l": "실습 강의",
    "h": "<h1>첫 Table 만들기와<br>기본 SQL 실행</h1><p class=\"lead\">왼쪽에는 이 자료를, 오른쪽에는 DBeaver SQL Editor를 띄워 한 단계씩 실행합니다.</p><div class=\"title-meta\"><span class=\"pill\">한 장 한 단계</span><span class=\"pill\">예상 후 실행</span><span class=\"pill\">결과 검증</span></div>",
    "s": "지금부터 4장 실습 강의를 진행하겠습니다. 화면 왼쪽에는 이 자료를 띄우고, 오른쪽에는 디비버 에스큐엘 편집기 화면을 띄워 진행합니다. 각 장표는 한 단계만 다룹니다. 먼저 무엇을 실행할지 읽고, 예상 결과를 말한 뒤, 실제로 실행하고 결과를 확인하겠습니다."
  },
  {
    "k": "PRACTICE RULE",
    "l": "진행 방식",
    "h": "<h2>실습은 한 구간씩<br>선택 실행합니다</h2><div class=\"grid-2\"><article class=\"card\"><h3>하지 않을 것</h3><p>SQL 파일 전체를 처음부터 끝까지 한 번에 실행하지 않습니다.</p></article><article class=\"card emphasis\"><h3>할 것</h3><p>현재 구간을 선택하고 실행 결과와 영향받은 Row 수를 확인합니다.</p></article></div>",
    "s": "실습에서 가장 중요한 규칙입니다. 에스큐엘 파일 전체를 처음부터 끝까지 한 번에 실행하지 않습니다. 현재 배우는 구간만 선택해서 실행합니다. 실행 전에는 예상 결과를 생각하고, 실행 후에는 반환 행이나 영향받은 행 수를 확인합니다. 변경 에스큐엘은 자동 커밋 상태에서 즉시 확정될 수 있으므로 더 조심합니다."
  },
  {
    "k": "STEP 01",
    "l": "위치 확인",
    "h": "<h2>현재 Database와 Schema를 확인합니다</h2><pre>SELECT current_database();\nSELECT current_schema();\nSHOW search_path;</pre><div class=\"expect\"><strong>완료 기준</strong><br>current_database = ai_database_book, public Schema 사용 가능</div>",
    "s": "디비버에서 에이아이 데이터베이스 북에 연결된 에스큐엘 편집기를 엽니다. 그리고 화면의 세 문장을 실행합니다. 커런트 데이터베이스, 커런트 스키마, 쇼 서치 패스입니다. 완료 기준은 현재 데이터베이스가 에이아이 데이터베이스 북이고, 퍼블릭 스키마를 사용할 수 있다는 것입니다."
  },
  {
    "k": "STEP 02",
    "l": "파일 열기",
    "h": "<h2>번호 SQL 파일을<br>순서대로 사용합니다</h2><div class=\"codebox\">01_create_students.sql<br>→ 02_insert_students.sql<br>→ verify_students.sql<br>→ 03_select_students.sql<br>→ 04_update_delete_students.sql<br>→ verify_students.sql</div><ul class=\"bullet-list\"><li>reset_students.sql: 처음부터 다시 시작할 때만 사용</li><li>basic_crud.sql: 기존 링크용 통합 참고</li></ul>",
    "s": "기본 실습은 공일 생성, 공이 입력, 상태 검증, 공삼 조회, 공사 수정과 삭제, 최종 상태 검증 순서로 진행합니다. 베리파이 스튜던츠는 데이터를 바꾸지 않고 현재 상태를 보여 줍니다. 리셋 파일은 처음부터 다시 시작할 때만 사용합니다. 베이식 크러드 파일은 기존 링크를 위한 통합 참고 자료이며 기본 출발점이 아닙니다."
  },
  {
    "k": "STEP 03",
    "l": "Table 생성",
    "h": "<h2>public.students Table을 생성합니다</h2><pre>CREATE TABLE public.students (\n    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    name VARCHAR(50) NOT NULL,\n    email VARCHAR(100) UNIQUE NOT NULL,\n    major VARCHAR(100),\n    grade INTEGER,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP\n);</pre>",
    "s": "퍼블릭 스튜던츠 테이블을 생성합니다. 이 문장을 선택해서 실행합니다. 이미 테이블이 있다면 릴레이션 스튜던츠 올레디 익지스트와 비슷한 오류가 나올 수 있습니다. 이 오류가 나왔다고 바로 삭제하지 않습니다. 기존 데이터가 있을 수 있기 때문에 현재 데이터베이스와 스키마, 테이블 상태를 먼저 확인합니다."
  },
  {
    "k": "STEP 04",
    "l": "Navigator 확인",
    "h": "<h2>DBeaver Navigator에서<br>Table을 확인합니다</h2><div class=\"codebox\">PostgreSQL 연결\n→ ai_database_book\n→ Schemas\n→ public\n→ Tables\n→ students</div><div class=\"expect\"><strong>완료 기준</strong><br>students Table이 보이면 성공입니다.</div>",
    "s": "디비버 네비게이터에서 테이블이 보이는지 확인합니다. 포스트그레스큐엘 연결 아래에서 에이아이 데이터베이스 북, 스키마, 퍼블릭, 테이블, 스튜던츠 순서로 확인합니다. 보이지 않으면 새로고침을 먼저 해 봅니다. 그래도 보이지 않으면 현재 연결 대상이 맞는지 다시 확인합니다."
  },
  {
    "k": "STEP 05",
    "l": "단일 INSERT",
    "h": "<h2>학생 한 명을 입력하고<br>자동 생성값을 확인합니다</h2><pre>INSERT INTO public.students (name, email, major, grade)\nVALUES ('김민지', 'minji@example.com', '컴퓨터공학', 2)\nRETURNING id, name, created_at;</pre><div class=\"expect\"><strong>예상</strong><br>id, name, created_at이 반환됩니다.</div>",
    "s": "학생 한 명을 입력합니다. 이름은 김민지, 이메일은 민지 앳 이그잼플 닷 컴, 전공은 컴퓨터공학, 학년은 이 학년입니다. 아이디와 등록 시각은 입력하지 않았지만 리터닝 결과로 확인합니다. 예상 결과는 아이디, 이름, 등록 시각이 반환되는 것입니다."
  },
  {
    "k": "STEP 06",
    "l": "여러 Row INSERT",
    "h": "<h2>여러 학생을 한 번에 입력합니다</h2><pre>INSERT INTO public.students (name, email, major, grade)\nVALUES\n    ('이준호', 'junho@example.com', '데이터사이언스', 3),\n    ('박서연', 'seoyeon@example.com', '경영학', 1),\n    ('최현우', 'hyunwoo@example.com', '컴퓨터공학', 4),\n    ('정하늘', 'haneul@example.com', 'AI데이터공학', 2);</pre>",
    "s": "이준호, 박서연, 최현우, 정하늘 네 명을 한 문장으로 추가합니다. 실행 결과에서도 네 행이 추가되어야 합니다. 오류가 발생하면 열과 값의 개수가 맞는지, 문자열에 작은따옴표를 사용했는지 살펴봅니다."
  },
  {
    "k": "STEP 07",
    "l": "NULL Row 입력",
    "h": "<h2>전공과 학년을 모르는 학생을 입력합니다</h2><pre>INSERT INTO public.students (name, email)\nVALUES ('윤서진', 'seojin@example.com');</pre><div class=\"expect\"><strong>예상</strong><br>major와 grade는 NULL, id와 created_at은 자동 생성됩니다.</div>",
    "s": "전공과 학년을 아직 모르는 학생을 입력합니다. 이번에는 이름과 이메일만 입력합니다. 메이저와 그레이드는 입력하지 않으므로 널이 저장됩니다. 아이디와 등록 시각은 자동으로 생성됩니다. 이 행은 이후 널 실습에서 사용합니다."
  },
  {
    "k": "CHECKPOINT A",
    "l": "초기 데이터 상태",
    "h": "<h2>초기 데이터 상태</h2><pre>SELECT COUNT(*) AS student_count\nFROM public.students;</pre><div class=\"table-wrap\"><table><thead><tr><th>항목</th><th>예상 상태</th></tr></thead><tbody><tr><td>학생 수</td><td>6명</td></tr><tr><td>이준호 학년</td><td>3</td></tr><tr><td>박서연</td><td>존재</td></tr><tr><td>NULL 학생</td><td>윤서진</td></tr></tbody></table></div>",
    "s": "초기 데이터에는 학생이 여섯 명 있습니다. 이준호는 삼 학년이고 박서연은 존재합니다. 윤서진의 전공과 학년에는 널이 저장되어 있습니다. 공삼 조회 파일은 이 상태를 기준으로 실행합니다."
  },
  {
    "k": "STEP 08",
    "l": "전체 조회",
    "h": "<h2>전체 Row와 Column을 조회합니다</h2><pre>SELECT *\nFROM public.students;</pre><div class=\"expect\"><strong>확인</strong><br>Column 구성과 Row 수를 확인하되, 표시 순서는 신뢰하지 않습니다.</div>",
    "s": "셀렉트 별표로 전체 열과 전체 행을 조회합니다. 이때 별표는 모든 열을 의미합니다. 결과에서 열 구성이 맞는지, 학생이 여섯 명인지 확인합니다. 다만 오더 바이가 없으므로 표시 순서는 신뢰하지 않습니다. 지금 보이는 순서가 항상 같은 순서라고 가정하지 않습니다."
  },
  {
    "k": "STEP 09",
    "l": "필요한 Column만 조회",
    "h": "<h2>필요한 Column만 선택합니다</h2><pre>SELECT name, email, major\nFROM public.students;</pre><div class=\"expect\"><strong>확인</strong><br>name, email, major 세 Column만 반환됩니다.</div>",
    "s": "필요한 열만 선택해 조회합니다. 결과에는 이름, 이메일, 전공 세 열만 표시됩니다. 실제 업무에서는 별표보다 필요한 열을 명시하는 편이 결과 구조를 이해하기 쉽습니다."
  },
  {
    "k": "STEP 10",
    "l": "ORDER BY",
    "h": "<h2>순서가 필요하면 ORDER BY를 사용합니다</h2><pre>SELECT id, name, email, major\nFROM public.students\nORDER BY id ASC;</pre><div class=\"expect\"><strong>예상</strong><br>id가 작은 Row부터 표시됩니다.</div>",
    "s": "순서가 필요하면 오더 바이를 사용합니다. 이 예제에서는 아이디가 작은 학생부터 표시됩니다. 오더 바이가 없는 결과에는 같은 순서를 기대할 수 없습니다."
  },
  {
    "k": "STEP 11",
    "l": "Alias",
    "h": "<h2>AS로 결과 Column 이름을 바꿔 표시합니다</h2><pre>SELECT\n    name AS student_name,\n    major AS student_major\nFROM public.students\nORDER BY id ASC;</pre><div class=\"expect\"><strong>주의</strong><br>AS는 원본 Column 이름을 바꾸지 않습니다.</div>",
    "s": "애즈로 조회 결과의 열 이름을 바꾸어 표시합니다. 네임은 스튜던트 네임으로, 메이저는 스튜던트 메이저로 표시합니다. 애즈는 원본 테이블의 열 이름을 바꾸는 것이 아닙니다. 조회 결과 화면에서 보이는 이름만 바꿉니다."
  },
  {
    "k": "STEP 12",
    "l": "WHERE: 문자열 비교",
    "h": "<h2>전공이 컴퓨터공학인 학생을 조회합니다</h2><pre>SELECT *\nFROM public.students\nWHERE major = '컴퓨터공학'\nORDER BY id ASC;</pre><div class=\"expect\"><strong>예상</strong><br>김민지, 최현우가 조회됩니다.</div>",
    "s": "전공이 컴퓨터공학인 학생을 조회합니다. 문자열은 작은따옴표로 감쌉니다. 초기 데이터에서는 김민지와 최현우 두 명이 반환됩니다."
  },
  {
    "k": "STEP 13",
    "l": "WHERE: 숫자 비교",
    "h": "<h2>학년이 3 이상인 학생을 조회합니다</h2><pre>SELECT *\nFROM public.students\nWHERE grade >= 3\nORDER BY grade DESC, id ASC;</pre><div class=\"expect\"><strong>예상</strong><br>최현우, 이준호가 조회됩니다.</div>",
    "s": "학년이 삼 이상인 학생을 조회합니다. 그레이드는 정수이므로 숫자는 따옴표 없이 비교합니다. 정렬은 학년 내림차순이고 같은 학년이면 아이디 오름차순입니다. 체크포인트 에이 기준 예상 학생은 최현우와 이준호입니다."
  },
  {
    "k": "STEP 14",
    "l": "<>와 NULL",
    "h": "<h2>같지 않다 조건과 NULL을 확인합니다</h2><pre>SELECT *\nFROM public.students\nWHERE major <> '경영학'\nORDER BY id ASC;</pre><div class=\"expect\"><strong>주의</strong><br>major가 NULL인 윤서진은 포함되지 않습니다.</div>",
    "s": "전공이 경영학이 아닌 행을 조회합니다. 전공이 널인 윤서진은 이 결과에 포함되지 않습니다. 널은 일반 값처럼 등호나 같지 않다 연산자로 비교하지 않고, 이즈 널 또는 이즈 낫 널을 사용합니다."
  },
  {
    "k": "STEP 15",
    "l": "NULL 포함 조건",
    "h": "<h2>NULL도 포함하려면 의도를 명시합니다</h2><pre>SELECT *\nFROM public.students\nWHERE major <> '경영학'\n   OR major IS NULL\nORDER BY id ASC;</pre><div class=\"expect\"><strong>확인</strong><br>윤서진이 결과에 포함됩니다.</div>",
    "s": "전공이 널인 학생도 포함하려면 오알 메이저 이즈 널 조건을 적습니다. 이 조건에서는 윤서진도 결과에 포함됩니다."
  },
  {
    "k": "STEP 16",
    "l": "AND 조건",
    "h": "<h2>AND로 조건을 모두 만족하는 Row를 찾습니다</h2><pre>SELECT *\nFROM public.students\nWHERE major = '컴퓨터공학'\n  AND grade >= 3\nORDER BY id ASC;</pre><div class=\"expect\"><strong>예상</strong><br>최현우 1행</div>",
    "s": "앤드는 모든 조건이 참인 행을 선택합니다. 전공이 컴퓨터공학이고 학년이 삼 이상인 학생을 조회합니다. 체크포인트 에이 기준으로 김민지는 이 학년이므로 제외되고, 최현우만 남습니다. 예상 행 수는 한 행입니다."
  },
  {
    "k": "STEP 17",
    "l": "OR와 IN",
    "h": "<h2>OR와 IN으로 여러 후보값을 처리합니다</h2><pre>SELECT *\nFROM public.students\nWHERE major IN ('컴퓨터공학', '데이터사이언스')\nORDER BY id ASC;</pre><div class=\"expect\"><strong>확인</strong><br>같은 Column의 여러 값 비교는 IN이 읽기 쉽습니다.</div>",
    "s": "같은 열을 여러 값과 비교할 때는 인이 읽기 쉬울 수 있습니다. 전공이 컴퓨터공학 또는 데이터사이언스인 학생을 조회합니다. 오알로 같은 조건을 길게 쓰는 것보다 인 목록으로 표현하면 의도가 더 분명합니다."
  },
  {
    "k": "STEP 18",
    "l": "LIKE",
    "h": "<h2>LIKE로 이름 패턴을 검색합니다</h2><pre>SELECT *\nFROM public.students\nWHERE name LIKE '김%'\nORDER BY id ASC;</pre><div class=\"expect\"><strong>예상</strong><br>김으로 시작하는 이름이 조회됩니다.</div>",
    "s": "라이크로 이름 패턴을 검색합니다. 김 퍼센트는 김으로 시작하는 문자열을 뜻하므로 김민지가 반환됩니다. 퍼센트는 길이에 상관없이 영 개 이상의 문자를 의미합니다."
  },
  {
    "k": "STEP 19",
    "l": "ILIKE",
    "h": "<h2>ILIKE로 대소문자 구분 없이 검색합니다</h2><pre>SELECT *\nFROM public.students\nWHERE email ILIKE '%EXAMPLE.COM'\nORDER BY id ASC;</pre><div class=\"expect\"><strong>확인</strong><br>PostgreSQL의 ILIKE는 대소문자 구분 없는 패턴 검색입니다.</div>",
    "s": "아이라이크로 이메일을 검색합니다. 아이라이크는 포스트그레스큐엘에서 대소문자를 구분하지 않는 패턴 검색입니다. 이 예제에서는 이메일이 이그잼플 닷 컴으로 끝나는 행을 조회합니다. 실행 후 전체 학생이 조건에 맞는지 확인합니다."
  },
  {
    "k": "STEP 20",
    "l": "IS NULL",
    "h": "<h2>NULL 값은 IS NULL로 찾습니다</h2><pre>SELECT *\nFROM public.students\nWHERE major IS NULL\nORDER BY id ASC;</pre><div class=\"expect\"><strong>예상</strong><br>윤서진 1행</div>",
    "s": "널 값은 이즈 널로 찾습니다. 메이저가 널인 학생을 조회합니다. 체크포인트 에이 기준 예상 결과는 윤서진 한 명입니다. 메이저 이퀄 널이 아니라 메이저 이즈 널을 사용해야 합니다."
  },
  {
    "k": "STEP 21",
    "l": "IS NOT NULL",
    "h": "<h2>값이 있는 Row는 IS NOT NULL로 찾습니다</h2><pre>SELECT *\nFROM public.students\nWHERE major IS NOT NULL\nORDER BY id ASC;</pre><div class=\"expect\"><strong>예상</strong><br>전공이 입력된 학생만 조회됩니다.</div>",
    "s": "값이 있는 행은 이즈 낫 널로 찾습니다. 전공이 입력된 학생만 조회합니다. 윤서진은 전공이 널이므로 제외됩니다. 널은 값이 없거나 아직 알려지지 않은 상태라는 점을 다시 확인합니다."
  },
  {
    "k": "STEP 22",
    "l": "ORDER BY NULLS LAST",
    "h": "<h2>NULL 위치를 명시해 정렬합니다</h2><pre>SELECT *\nFROM public.students\nORDER BY grade DESC NULLS LAST, id ASC;</pre><div class=\"expect\"><strong>확인</strong><br>grade가 NULL인 Row는 마지막에 표시됩니다.</div>",
    "s": "학년 내림차순으로 정렬하고 널은 마지막에 표시합니다. 널스 라스트를 직접 지정했기 때문에 학년이 널인 윤서진은 마지막에 표시됩니다. 정렬 방향에 따라 널의 기본 위치가 달라질 수 있으므로 의도가 중요하면 명시하는 것이 좋습니다."
  },
  {
    "k": "STEP 23",
    "l": "LIMIT",
    "h": "<h2>최신 3명을 조회합니다</h2><pre>SELECT *\nFROM public.students\nORDER BY created_at DESC, id DESC\nLIMIT 3;</pre><div class=\"expect\"><strong>확인</strong><br>created_at 동률 가능성을 고려해 id DESC를 보조 기준으로 사용합니다.</div>",
    "s": "최신 세 명을 조회합니다. 크리에이티드 앳 내림차순으로 정렬하고, 같은 시각이면 아이디 내림차순으로 정렬합니다. 리밋 삼은 정렬된 결과 중 세 행만 가져옵니다. 리밋만 사용하거나 동률을 구분하지 않는 정렬을 사용하면 안정적인 결과를 보장하기 어렵습니다."
  },
  {
    "k": "STEP 24",
    "l": "UPDATE 대상 확인",
    "h": "<h2>UPDATE 전에 대상 Row를 확인합니다</h2><pre>SELECT *\nFROM public.students\nWHERE email = 'junho@example.com';</pre><div class=\"expect\"><strong>예상</strong><br>이준호 1행, 현재 grade = 3</div>",
    "s": "업데이트를 실행하기 전에 먼저 대상 행을 확인합니다. 이메일이 준호 앳 이그잼플 닷 컴인 학생을 조회합니다. 체크포인트 에이 기준으로 이준호 한 행이 나와야 하고, 현재 학년은 삼 학년이어야 합니다. 조회 결과가 한 행이 아니면 업데이트를 실행하지 않습니다."
  },
  {
    "k": "STEP 25",
    "l": "UPDATE 실행",
    "h": "<h2>이준호 학년을 4로 수정합니다</h2><pre>UPDATE public.students\nSET grade = 4\nWHERE email = 'junho@example.com'\nRETURNING id, name, grade;</pre><div class=\"expect\"><strong>예상</strong><br>영향 Row 수 1, RETURNING: 이준호 grade 4</div>",
    "s": "이준호의 학년을 사 학년으로 수정합니다. 업데이트 문장은 이메일 조건으로 한 행만 대상으로 합니다. 리터닝 결과에서 아이디, 이름, 학년을 확인합니다. 예상은 영향 행 수 일, 리터닝 결과는 이준호 그레이드 사입니다."
  },
  {
    "k": "STEP 26",
    "l": "UPDATE 재확인",
    "h": "<h2>수정 결과를 다시 조회합니다</h2><pre>SELECT *\nFROM public.students\nWHERE email = 'junho@example.com';</pre><div class=\"expect\"><strong>완료 기준</strong><br>이준호 grade = 4</div>",
    "s": "수정 결과를 다시 조회합니다. 같은 이메일 조건으로 셀렉트합니다. 완료 기준은 이준호의 그레이드가 사로 바뀐 것입니다. 변경 에스큐엘은 실행 직후 결과를 확인하고, 다시 조회해서 데이터 상태를 확인하는 습관을 가져야 합니다."
  },
  {
    "k": "CHECKPOINT B",
    "l": "수정 실습 후 상태",
    "h": "<h2>수정 실습 후 상태</h2><div class=\"table-wrap\"><table><thead><tr><th>항목</th><th>상태</th></tr></thead><tbody><tr><td>학생 수</td><td>6명</td></tr><tr><td>이준호 학년</td><td>4</td></tr><tr><td>박서연</td><td>존재</td></tr></tbody></table></div>",
    "s": "수정 실습 후에도 학생은 여섯 명입니다. 이준호의 학년만 사 학년으로 바뀌었고 박서연은 아직 존재합니다."
  },
  {
    "k": "STEP 27",
    "l": "DELETE 대상 확인",
    "h": "<h2>DELETE 전에 삭제 대상 Row를 확인합니다</h2><pre>SELECT *\nFROM public.students\nWHERE email = 'seoyeon@example.com';</pre><div class=\"expect\"><strong>예상</strong><br>박서연 1행</div>",
    "s": "딜리트를 실행하기 전에 삭제 대상 행을 확인합니다. 이메일이 서연 앳 이그잼플 닷 컴인 학생을 조회합니다. 예상 결과는 박서연 한 행입니다. 조회 결과가 한 행이 아니면 딜리트를 실행하지 않습니다."
  },
  {
    "k": "STEP 28",
    "l": "DELETE 실행",
    "h": "<h2>박서연 Row를 삭제합니다</h2><pre>DELETE FROM public.students\nWHERE email = 'seoyeon@example.com'\nRETURNING id, name, email;</pre><div class=\"expect\"><strong>예상</strong><br>영향 Row 수 1, RETURNING: 박서연</div>",
    "s": "박서연 행을 삭제합니다. 딜리트 프롬 퍼블릭 스튜던츠, 웨어 이메일 조건을 사용합니다. 리터닝으로 삭제된 아이디, 이름, 이메일을 확인합니다. 예상은 영향 행 수 일, 리터닝 결과는 박서연 한 행입니다."
  },
  {
    "k": "STEP 29",
    "l": "DELETE 재확인",
    "h": "<h2>삭제 결과를 다시 조회합니다</h2><pre>SELECT *\nFROM public.students\nWHERE email = 'seoyeon@example.com';</pre><div class=\"expect\"><strong>완료 기준</strong><br>0 Row가 반환됩니다.</div>",
    "s": "삭제 결과를 다시 조회합니다. 같은 이메일 조건으로 셀렉트합니다. 완료 기준은 영 행이 반환되는 것입니다. 삭제한 행이 더 이상 조회되지 않는지 확인합니다."
  },
  {
    "k": "CHECKPOINT C",
    "l": "삭제 실습 후 상태",
    "h": "<h2>삭제 실습 후 상태</h2><pre>SELECT COUNT(*) AS student_count\nFROM public.students;</pre><div class=\"table-wrap\"><table><thead><tr><th>항목</th><th>상태</th></tr></thead><tbody><tr><td>학생 수</td><td>5명</td></tr><tr><td>이준호 학년</td><td>4</td></tr><tr><td>박서연</td><td>삭제</td></tr></tbody></table></div>",
    "s": "삭제 실습 후에는 학생이 다섯 명입니다. 이준호는 사 학년이고 박서연은 더 이상 존재하지 않습니다."
  },
  {
    "k": "STEP 30",
    "l": "위험 SQL 확인",
    "h": "<h2>WHERE 없는 UPDATE·DELETE는 실행하지 않습니다</h2><div class=\"grid-2\"><article class=\"card\"><h3>위험한 UPDATE</h3><pre>-- UPDATE public.students\n-- SET grade = 1;</pre></article><article class=\"card emphasis\"><h3>위험한 DELETE</h3><pre>-- DELETE FROM public.students;</pre></article></div><p class=\"body-text\">문법 오류는 아니지만 영향 범위가 전체 Table입니다.</p>",
    "s": "화면의 두 문장은 주석으로 표시한 실행 금지 예제입니다. 웨어 없는 업데이트는 모든 학생의 학년을 바꾸고, 웨어 없는 딜리트는 모든 행을 삭제합니다. 두 문장 모두 문법적으로 유효하기 때문에 더 위험합니다."
  },
  {
    "k": "STEP 31",
    "l": "AI SQL 검토",
    "h": "<h2>AI가 만든 DELETE SQL을<br>실행 전 검토합니다</h2><pre>DELETE FROM public.students\nWHERE major = '컴퓨터공학';</pre><ul class=\"bullet-list\"><li>현재 데이터 상태는 무엇인가?</li><li>삭제 대상은 몇 Row인가?</li><li>정말 물리 삭제가 맞는가?</li><li>먼저 SELECT로 대상 확인했는가?</li></ul>",
    "s": "에이아이가 전공이 컴퓨터공학인 학생을 삭제하는 문장을 만들었다고 가정합니다. 먼저 같은 조건의 셀렉트로 김민지와 최현우 두 명이 대상인지 봅니다. 요구사항이 물리 삭제인지도 검토합니다. 이 딜리트 문은 설명용이며 실행하지 않습니다."
  },
  {
    "k": "STEP 32",
    "l": "초기화 안내",
    "h": "<h2>필요할 때만 reset_students.sql을 사용합니다</h2><div class=\"codebox\">code/chapter04/reset_students.sql</div><ul class=\"bullet-list\"><li>현재 Database가 ai_database_book인지 확인</li><li>삭제 대상이 public.students인지 확인</li><li>읽기 전용 연결이 아닌지 확인</li><li>실습을 처음부터 다시 시작할 때만 실행</li></ul>",
    "s": "리셋 스튜던츠는 실습을 처음부터 다시 시작할 때만 사용합니다. 파일은 현재 데이터베이스, 퍼블릭 스키마 존재 여부, 읽기 전용 상태를 검사한 뒤 퍼블릭 스튜던츠만 삭제합니다. 단순 오류 해결을 위해 즉시 실행하지 않습니다."
  },
  {
    "k": "PRACTICE SUMMARY",
    "l": "실습 정리",
    "h": "<h2>실습 완료 기준</h2><ul class=\"bullet-list\"><li>번호 SQL 파일의 역할과 실행 순서를 설명한다.</li><li>초기 데이터 상태: 학생 6명·이준호 grade 3</li><li>SELECT, WHERE, LIKE, NULL, ORDER BY, LIMIT 실행</li><li>수정 실습 후 상태: 이준호 grade 4·학생 6명</li><li>삭제 실습 후 상태: 박서연 삭제·학생 5명</li><li>위험 SQL과 AI SQL의 영향 범위 검토</li></ul>",
    "s": "퍼블릭 스튜던츠를 만들고 학생 여섯 명을 입력했습니다. 조회 문법을 연습한 뒤 이준호의 학년을 사 학년으로 수정하고 박서연을 삭제했습니다. 최종 상태는 학생 다섯 명, 이준호 사 학년, 박서연 없음입니다. 웨어 없는 변경문과 에이아이가 제안한 딜리트는 영향 범위를 검토한 뒤 실행 여부를 결정합니다."
  }
];
