flowchart LR
    A[students]
    B[enrollments]

    A --> A1[id = 1 김민지]
    A --> A2[id = 2 이준호]
    A --> A3[id = 4 최현우]

    B --> B1[student_id = 1]
    B --> B2[student_id = 2]

    A1 --> C[조건 일치]
    B1 --> C
    A2 --> D[조건 일치]
    B2 --> D
    A3 --> E[조건 불일치]

    C --> F[INNER JOIN 결과 포함]
    D --> F
    E --> G[결과 제외]
