flowchart LR
    M[members]
    B[books]
    X[직접 N:M<br/>ID 목록 저장은 피함]
    L[loans<br/>FK member_id<br/>FK book_id<br/>borrowed_at]

    M -. N:M .-> B
    M --> X
    X --> L
    M -- "1 : 0..N" --> L
    B -- "1 : 0..N" --> L
