-- Chapter 09. transaction_lab 스키마 생성
-- Chapter 07의 course_project 데이터를 보호하면서 트랜잭션 실습 공간을 만듭니다.

SELECT current_database();
SELECT current_schema();
SHOW search_path;

BEGIN;

DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '실행 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF to_regclass('course_project.students') IS NULL
       OR to_regclass('course_project.courses') IS NULL
       OR to_regclass('course_project.enrollments') IS NULL THEN
        RAISE EXCEPTION
            '실행 중단: Chapter 07 course_project 테이블이 준비되지 않았습니다.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'course_project'
          AND table_name = 'enrollments'
          AND column_name = 'recorded_amount'
    ) THEN
        RAISE EXCEPTION
            '실행 중단: Chapter 07 recorded_amount 열이 없습니다.';
    END IF;

    IF to_regnamespace('transaction_lab') IS NOT NULL THEN
        RAISE EXCEPTION
            '실행 중단: transaction_lab 스키마가 이미 존재합니다.';
    END IF;

    IF (SELECT COUNT(*) FROM course_project.students WHERE id IN (101, 102, 103)) <> 3
       OR (
            SELECT COUNT(*)
            FROM course_project.courses
            WHERE (id, price) IN (
                (301, 100000::numeric),
                (302, 120000::numeric),
                (303, 150000::numeric)
            )
       ) <> 3
       OR (SELECT COUNT(*) FROM course_project.enrollments) <> 5 THEN
        RAISE EXCEPTION
            '실행 중단: Chapter 07 기준 데이터를 확인하세요.';
    END IF;
END
$$;

CREATE SCHEMA transaction_lab;

CREATE TABLE transaction_lab.course_inventory (
    course_id INTEGER PRIMARY KEY,
    capacity INTEGER NOT NULL,
    remaining_seats INTEGER NOT NULL,

    CONSTRAINT fk_transaction_inventory_course
        FOREIGN KEY (course_id)
        REFERENCES course_project.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transaction_inventory_capacity
        CHECK (capacity > 0),

    CONSTRAINT chk_transaction_inventory_remaining
        CHECK (
            remaining_seats >= 0
            AND remaining_seats <= capacity
        )
);

CREATE TABLE transaction_lab.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    enrolled_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL,
    recorded_amount NUMERIC(12, 0) NOT NULL,

    CONSTRAINT fk_transaction_enrollment_student
        FOREIGN KEY (student_id)
        REFERENCES course_project.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_transaction_enrollment_course
        FOREIGN KEY (course_id)
        REFERENCES course_project.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transaction_enrollment_status
        CHECK (status IN ('수강중', '취소')),

    CONSTRAINT chk_transaction_enrollment_amount
        CHECK (recorded_amount >= 0)
);

CREATE UNIQUE INDEX uq_transaction_enrollments_active
ON transaction_lab.enrollments (student_id, course_id)
WHERE status = '수강중';

CREATE TABLE transaction_lab.payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id INTEGER NOT NULL,
    amount NUMERIC(12, 0) NOT NULL,
    paid_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT uq_transaction_payment_enrollment
        UNIQUE (enrollment_id),

    CONSTRAINT fk_transaction_payment_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES transaction_lab.enrollments(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transaction_payment_amount
        CHECK (amount >= 0)
);

COMMIT;

SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema = 'transaction_lab'
ORDER BY table_name;
