-- Chapter 09. transaction_lab 스키마 생성
-- 목적: Chapter 07의 course_project 데이터를 보호하면서 트랜잭션 실습 공간을 만듭니다.
-- 주의: 이 파일은 기존 스키마나 테이블을 자동으로 삭제하지 않습니다.

SELECT current_database();
SELECT current_schema();

-- Chapter 07 프로젝트 준비 상태 확인
SELECT COUNT(*) AS project_student_count
FROM course_project.students;

SELECT COUNT(*) AS project_course_count
FROM course_project.courses;

CREATE SCHEMA transaction_lab;

CREATE TABLE transaction_lab.course_inventory (
    course_id INTEGER PRIMARY KEY,
    capacity INTEGER NOT NULL,
    remaining_seats INTEGER NOT NULL,

    CONSTRAINT fk_transaction_inventory_course
        FOREIGN KEY (course_id)
        REFERENCES course_project.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transaction_inventory_capacity
        CHECK (capacity > 0),

    CONSTRAINT chk_transaction_inventory_remaining
        CHECK (
            remaining_seats >= 0
            AND remaining_seats <= capacity
        )
);

CREATE TABLE transaction_lab.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    enrolled_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_amount INTEGER NOT NULL,

    CONSTRAINT fk_transaction_enrollment_student
        FOREIGN KEY (student_id)
        REFERENCES course_project.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_transaction_enrollment_course
        FOREIGN KEY (course_id)
        REFERENCES course_project.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transaction_enrollment_status
        CHECK (status IN ('수강중', '취소')),

    CONSTRAINT chk_transaction_enrollment_amount
        CHECK (paid_amount >= 0)
);

CREATE TABLE transaction_lab.payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id INTEGER UNIQUE NOT NULL,
    amount INTEGER NOT NULL,
    paid_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_transaction_payment_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES transaction_lab.enrollments(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transaction_payment_amount
        CHECK (amount >= 0)
);

-- 생성 확인
SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'transaction_lab'
ORDER BY table_name;
