-- Chapter 09. transaction_lab 스키마 생성
-- 목적: Chapter 07의 course_project 데이터를 보호하면서 트랜잭션 실습 공간을 만듭니다.
-- 주의: 이 파일은 기존 transaction_lab 객체를 자동으로 삭제하지 않습니다.
-- 생성 전 사전 조건을 검사하고, 스키마와 테이블 생성 전체를 하나의 트랜잭션으로 처리합니다.

SELECT current_database();
SELECT current_schema();
SHOW search_path;

BEGIN;

-- ============================================================
-- 0. Chapter 07 기준 상태와 중복 생성 여부 검사
-- ============================================================
DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '실행 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF to_regclass('course_project.students') IS NULL
       OR to_regclass('course_project.courses') IS NULL
       OR to_regclass('course_project.enrollments') IS NULL THEN
        RAISE EXCEPTION
            '실행 중단: Chapter 07 course_project 테이블이 준비되지 않았습니다.';
    END IF;

    IF to_regnamespace('transaction_lab') IS NOT NULL THEN
        RAISE EXCEPTION
            '실행 중단: transaction_lab 스키마가 이미 존재합니다. 현재 상태를 확인하거나 reset_transaction_lab.sql을 사용하세요.';
    END IF;

    IF (
        SELECT COUNT(*)
        FROM course_project.students
        WHERE id IN (101, 102, 103)
    ) <> 3 THEN
        RAISE EXCEPTION
            '실행 중단: 실습 학생 101, 102, 103이 모두 존재해야 합니다.';
    END IF;

    IF (
        SELECT COUNT(*)
        FROM course_project.courses
        WHERE (id, price) IN (
            (301, 100000),
            (302, 120000),
            (303, 150000)
        )
    ) <> 3 THEN
        RAISE EXCEPTION
            '실행 중단: 강의 301~303의 존재 여부와 기준 가격을 확인하세요.';
    END IF;

    IF (SELECT COUNT(*) FROM course_project.enrollments) <> 5 THEN
        RAISE EXCEPTION
            '실행 중단: Chapter 07 최종 신청 행 수는 5여야 합니다.';
    END IF;
END
$$;

-- ============================================================
-- 1. 실습 전용 스키마
-- ============================================================
CREATE SCHEMA transaction_lab;

-- ============================================================
-- 2. 강의별 좌석 상태
-- ============================================================
CREATE TABLE transaction_lab.course_inventory (
    course_id INTEGER PRIMARY KEY,
    capacity INTEGER NOT NULL,
    remaining_seats INTEGER NOT NULL,

    CONSTRAINT fk_transaction_inventory_course
        FOREIGN KEY (course_id)
        REFERENCES course_project.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transaction_inventory_capacity
        CHECK (capacity > 0),

    CONSTRAINT chk_transaction_inventory_remaining
        CHECK (
            remaining_seats >= 0
            AND remaining_seats <= capacity
        )
);

-- ============================================================
-- 3. 트랜잭션 실습용 수강신청
-- 동일 학생·강의의 수강중 행은 한 건만 허용합니다.
-- ============================================================
CREATE TABLE transaction_lab.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    enrolled_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_amount INTEGER NOT NULL,

    CONSTRAINT fk_transaction_enrollment_student
        FOREIGN KEY (student_id)
        REFERENCES course_project.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_transaction_enrollment_course
        FOREIGN KEY (course_id)
        REFERENCES course_project.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transaction_enrollment_status
        CHECK (status IN ('수강중', '취소')),

    CONSTRAINT chk_transaction_enrollment_amount
        CHECK (paid_amount >= 0)
);

CREATE UNIQUE INDEX uq_transaction_enrollments_active
ON transaction_lab.enrollments (student_id, course_id)
WHERE status = '수강중';

-- ============================================================
-- 4. 결제 기록
-- FK와 UNIQUE는 유효한 신청 참조와 신청당 최대 한 결제를 보장합니다.
-- 수강중 신청에 결제가 최소 한 건 존재해야 한다는 규칙은
-- 트랜잭션 흐름과 최종 검증 SQL로 확인합니다.
-- ============================================================
CREATE TABLE transaction_lab.payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id INTEGER NOT NULL,
    amount INTEGER NOT NULL,
    paid_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT uq_transaction_payment_enrollment
        UNIQUE (enrollment_id),

    CONSTRAINT fk_transaction_payment_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES transaction_lab.enrollments(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transaction_payment_amount
        CHECK (amount >= 0)
);

COMMIT;

-- 생성 확인
SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'transaction_lab'
ORDER BY table_name;

SELECT
    indexname,
    indexdef
FROM pg_indexes
WHERE schemaname = 'transaction_lab'
ORDER BY indexname;
