(() => {
  'use strict';

  if (!Array.isArray(window.CH5_SLIDES)) return;

  const isPractice = String(window.CH5_TITLE || '').includes('실습');

  const replaceAll = (value, pairs) => {
    let output = String(value ?? '');
    pairs.forEach(([from, to]) => {
      output = output.split(from).join(to);
    });
    return output;
  };

  const commonPairs = [];

  const practicePairs = [
    ['library_schema.sql', '01_library_schema.sql'],
    ['library_seed.sql', '02_library_seed.sql'],
    ['library_validation.sql', '03_library_validation.sql'],
    ['title VARCHAR(100) NOT NULL', 'title VARCHAR(200) NOT NULL'],
    ['author VARCHAR(50) NOT NULL', 'author VARCHAR(100) NOT NULL'],
    ['isbn VARCHAR(30)', 'isbn VARCHAR(20) NOT NULL'],
    ['제목과 저자는 필수이고 출판연도와 아이에스비엔은 선택적으로 둘 수 있습니다.', '제목과 저자, 아이에스비엔은 필수이고 출판연도는 현재 초안에서 선택값입니다.'],
    ['members: 2행', 'members: 3행'],
    ['books: 2행', 'books: 3행'],
    ['loans: 3행', 'loans: 4행'],
    ['members가 2행', 'members가 3행'],
    ['books가 2행', 'books가 3행'],
    ['loans가 3행', 'loans가 4행'],
    ['회원 2행 조회', '회원 3행 조회'],
    ['도서 2행 조회', '도서 3행 조회'],
    ['members 2행, books 2행, loans 3행', 'members 3행, books 3행, loans 4행'],
    ['멤버스가 이 행, 북스가 이 행, 로운스가 삼 행', '멤버스가 삼 행, 북스가 삼 행, 로운스가 사 행']
  ];

  window.CH5_SLIDES.forEach((slide) => {
    if (!slide) return;
    slide.h = replaceAll(slide.h, commonPairs);
    slide.s = replaceAll(slide.s, commonPairs);
    if (isPractice) {
      slide.h = replaceAll(slide.h, practicePairs);
      slide.s = replaceAll(slide.s, practicePairs);
    }
  });

  if (!isPractice) return;

  const byKey = (key) => window.CH5_SLIDES.find((slide) => slide?.k === key);

  const files = byKey('FILES');
  if (files) {
    files.h = `<h2>Chapter 05 권장 실습 파일</h2><div class="table-wrap"><table><thead><tr><th>파일</th><th>역할</th></tr></thead><tbody><tr><td>01_library_schema.sql</td><td>members, books, loans Table 생성</td></tr><tr><td>02_library_seed.sql</td><td>3·3·4 샘플 입력과 IDENTITY 조정</td></tr><tr><td>03_library_validation.sql</td><td>행 수, 관계, NULL, 고아 참조, 시간 순서 확인</td></tr><tr><td>reset_library.sql</td><td>정말 처음부터 다시 시작할 때만 초기화</td></tr></tbody></table></div><p class="body-text">기존 library_*.sql은 호환용이며 번호 파일과 중복 실행하지 않습니다.</p>`;
    files.s = `처음 학습하는 독자는 번호형 파일을 사용합니다. 영일 라이브러리 스키마 에스큐엘은 세 테이블을 하나의 트랜잭션으로 생성합니다. 영이 라이브러리 시드 에스큐엘은 회원 세 명, 도서 세 건, 대여 네 건을 입력하고 아이덴티티 다음 값을 조정합니다. 영삼 라이브러리 밸리데이션 에스큐엘은 행 수와 관계, 널, 고아 참조와 시간 순서를 확인합니다. 기존 라이브러리 언더스코어 파일은 호환용이므로 번호 파일과 중복 실행하지 않습니다.`;
  }

  const schemaStep = byKey('STEP 08');
  if (schemaStep) {
    schemaStep.h = `<h2>Step 08. 01_library_schema.sql을 실행합니다</h2><div class="flow"><div class="flow-step">BEGIN</div><div class="flow-arrow">→</div><div class="flow-step">위치·쓰기 상태<br>기존 Table 확인</div><div class="flow-arrow">→</div><div class="flow-step">members → books → loans</div><div class="flow-arrow">→</div><div class="flow-step current">0행 확인<br>COMMIT</div></div>`;
    schemaStep.s = `영일 라이브러리 스키마 에스큐엘을 실행합니다. 이 파일은 현재 데이터베이스와 쓰기 가능 상태, 퍼블릭 스키마와 기존 테이블 존재 여부를 먼저 확인합니다. 멤버스, 북스, 로운스 생성은 하나의 트랜잭션으로 묶여 있어 중간 오류가 발생하면 일부 테이블만 남는 상태를 피할 수 있습니다. 마지막에는 세 테이블이 모두 존재하고 영 행인지 확인한 뒤 커밋합니다.`;
  }

  const booksStep = byKey('STEP 10');
  if (booksStep) {
    booksStep.h = `<h2>Step 10. books Table을 만듭니다</h2><pre>CREATE TABLE public.books (\n    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    title VARCHAR(200) NOT NULL,\n    author VARCHAR(100) NOT NULL,\n    published_year INTEGER,\n    isbn VARCHAR(20) NOT NULL\n);</pre>`;
    booksStep.s = `북스 테이블을 만듭니다. 이 장에서 한 행은 대여 대상으로 관리하는 도서 한 건입니다. 제목은 이백 자, 저자는 백 자 범위의 문자열로 두고 제목과 저자, 아이에스비엔은 필수값입니다. 출판연도는 현재 초안에서 선택값으로 둡니다. 아이에스비엔의 유일성은 아직 미확정이므로 유니크 제약조건은 적용하지 않습니다.`;
  }

  const sampleSlide = window.CH5_SLIDES.find((slide) => /샘플|기준 행 수|입력 완료|Seed/i.test(`${slide?.k || ''} ${slide?.l || ''} ${slide?.h || ''}`) && /members/i.test(slide?.h || ''));
  if (sampleSlide) {
    sampleSlide.h = replaceAll(sampleSlide.h, practicePairs);
    if (!/미반납/.test(sampleSlide.h)) {
      sampleSlide.h += `<div class="expect"><strong>기준 상태</strong><br>members 3 · books 3 · loans 4 · 미반납 3</div>`;
    }
  }
})();
