param()
$ErrorActionPreference='Stop'
$dst=Split-Path -Parent $MyInvocation.MyCommand.Path
function Clean([string]$x){(($x -replace '`','' -replace '<[^>]+>','' -replace '^[-*]\s*','' -replace '\s+',' ').Trim())}
function Sections($path,$max){$l=Get-Content $path -Encoding UTF8;$out=@();for($i=0;$i-lt$l.Count;$i++){if($l[$i]-match '^## (\d+)\. (.+)$' -and [int]$Matches[1]-le$max){$n=[int]$Matches[1];$t=$Matches[2];$body=@();$code=@();$in=$false;for($j=$i+1;$j-lt$l.Count-and $l[$j]-notmatch '^## \d+\.';$j++){if($l[$j]-match '^```'){$in=-not$in;continue};if($in){if($l[$j].Trim()){$code+=$l[$j]}}elseif($l[$j].Trim() -and $l[$j]-notmatch '^#|^\||^!\['){$body+=(Clean $l[$j])}};$out+=@{n=$n;t=$t;body=$body;code=$code}}};$out}
function Intro($kind){if($kind-eq'theory'){@(
@{k='CHAPTER 06';l='이론 강의';t='정규화와 데이터 무결성으로 좋은 테이블 만들기';h='<h1>정규화와 데이터 무결성으로<br>좋은 테이블 만들기</h1><p class="lead">데이터가 바뀌어도 의미와 정확성을 지키는 구조를 배웁니다.</p>';s='5장에서는 요구사항을 테이블 구조로 바꾸었습니다. 6장에서는 그 구조가 데이터의 추가, 수정, 삭제를 견딜 수 있는지 검토합니다. 좋은 테이블은 단순히 조회가 되는 테이블이 아닙니다. 같은 사실을 한 곳에서 관리하고, 잘못된 값과 관계가 저장되지 않도록 규칙을 적용하며, 실제 오류 데이터로 그 규칙을 검증할 수 있어야 합니다.'},
@{k='CHAPTER GOALS';l='학습 목표';t='이번 장을 마치면 할 수 있는 일';h='<h2>이번 장을 마치면<br>할 수 있는 일</h2><ul class="bullet-list"><li>위험한 중복과 정상적인 반복을 구분합니다.</li><li>삽입·수정·삭제 이상을 설명합니다.</li><li>제1·제2·제3정규형을 질문으로 판단합니다.</li><li>제약조건을 적용하고 오류 데이터로 검증합니다.</li></ul>';s='이번 장의 목표는 정규형 이름을 외우는 것이 아닙니다. 값이 반복될 때 어떤 불일치가 생기는지 설명하고, 한 행의 의미와 컬럼의 주인을 기준으로 분리 여부를 판단하는 것이 먼저입니다. 그다음 기본키, 외래키, 필수값, 고유성과 값의 조건을 적용하고, 정상 데이터와 경계값은 성공하며 잘못된 데이터는 실패하는지 확인합니다.'},
@{k='CHAPTER FLOW';l='학습 흐름';t='문제 발견에서 실행 검증까지 이어집니다';h='<h2>이번 장의 학습 흐름</h2><div class="flow"><div class="flow-step">중복과 이상<br>발견</div><div class="flow-arrow">→</div><div class="flow-step">행 의미와<br>종속 판단</div><div class="flow-arrow">→</div><div class="flow-step">1·2·3정규형<br>적용</div><div class="flow-arrow">→</div><div class="flow-step">제약조건<br>구현</div><div class="flow-arrow">→</div><div class="flow-step">정상·경계·오류<br>검증</div></div>';s='먼저 반복 저장 때문에 생기는 삽입, 수정, 삭제 문제를 확인합니다. 다음으로 한 행이 무엇을 나타내는지와 어떤 값이 다른 값을 결정하는지 살펴봅니다. 이 판단을 제1, 제2, 제3정규형에 적용해 테이블을 분리합니다. 분리한 구조에는 제약조건을 구현하고, 마지막으로 정상·경계·오류 데이터를 실행해 설계가 의도대로 동작하는지 검증합니다.'}
)}else{@(
@{k='CHAPTER 06';l='실습 강의';t='정규화와 무결성 규칙을 직접 검증합니다';h='<h1>정규화와 무결성 규칙을<br>직접 검증합니다</h1><p class="lead">구조 생성부터 오류 테스트와 복구까지 단계별로 진행합니다.</p>';s='실습에서는 정규화된 구조를 직접 만들고, 설명한 규칙이 실제 포스트그레스큐엘에서 동작하는지 확인합니다. 성공하는 예제만 실행하지 않습니다. 허용되어야 하는 경계값과 반드시 실패해야 하는 오류값을 따로 실행하고, 오류 뒤에는 트랜잭션 상태를 복구한 다음 최종 검증까지 완료합니다.'},
@{k='CHAPTER GOALS';l='학습 목표';t='이번 실습을 마치면 할 수 있는 일';h='<h2>이번 실습을 마치면<br>할 수 있는 일</h2><ul class="bullet-list"><li>정규화 전 구조의 문제를 표시합니다.</li><li>members·books·loans 구조를 생성합니다.</li><li>제약조건별 성공·실패 결과를 예측합니다.</li><li>오류 후 ROLLBACK하고 최종 상태를 검증합니다.</li></ul>';s='실습 목표는 파일을 끝까지 실행하는 것이 아닙니다. 정규화 전 구조에서 반복과 이상 현상을 찾고, 회원, 도서, 대여 테이블을 생성한 뒤 각 제약조건이 어떤 데이터를 막는지 예측해야 합니다. 정상과 경계 데이터는 성공하고 오류 데이터는 의도대로 실패하는지 확인하며, 오류가 난 뒤에는 롤백으로 상태를 복구할 수 있어야 합니다.'},
@{k='CHAPTER FLOW';l='학습 흐름';t='예상하고 실행한 뒤 증거로 확인합니다';h='<h2>이번 실습의 학습 흐름</h2><div class="flow"><div class="flow-step">위치·파일<br>확인</div><div class="flow-arrow">→</div><div class="flow-step">문제 구조<br>분석</div><div class="flow-arrow">→</div><div class="flow-step">Schema·Seed<br>실행</div><div class="flow-arrow">→</div><div class="flow-step">경계·오류<br>테스트</div><div class="flow-arrow">→</div><div class="flow-step">복구·최종<br>검증</div></div>';s='각 단계는 수행 작업, 실행 전 예상, 완료 기준, 오류 발생 시 확인 순서로 진행합니다. 먼저 실행 위치와 파일을 확인하고 정규화 전 구조의 문제를 분석합니다. 스키마와 기준 데이터를 만든 뒤 경계값과 오류값을 하나씩 실행합니다. 마지막에는 오류 상태를 복구하고 행 수, 관계, 날짜와 활성 대여 규칙을 다시 확인합니다.'}
)}}
function Build($kind,$md,$max,$out){$slides=@(Intro $kind);foreach($sec in Sections $md $max){$b=@($sec.body|?{$_}|Select-Object -First 4);if(!$b){$b=@('이 단계의 목적과 완료 기준을 확인합니다.')};$lis=($b|%{"<li>$_</li>"})-join'';$h="<h2>$($sec.t)</h2><ul class=`"bullet-list`">$lis</ul>";if($sec.code.Count){$c=@($sec.code|Select-Object -First 10);$h="<h2>$($sec.t)</h2><pre><code>"+[System.Net.WebUtility]::HtmlEncode(($c-join"`n"))+"</code></pre>"};$ctx=(($sec.body|Select-Object -First 8)-join' ');if($ctx.Length-gt650){$ctx=$ctx.Substring(0,650)};while($ctx.Length-lt280){$ctx+=' 이 단계에서는 실행 전에 예상 결과를 적고, 실제 결과가 데이터의 의미와 업무 규칙에 맞는지 확인합니다.'};$s="$($sec.t). $ctx";$slides+=@{k=if($kind-eq'theory'){'NORMALIZATION'}else{'PRACTICE STEP'};l=if($kind-eq'theory'){'이론 강의'}else{'실습 강의'};t=$sec.t;h=$h;s=$s}};Set-Content $out ('window.CH6_SLIDES='+($slides|ConvertTo-Json -Depth 8 -Compress)+';') -Encoding UTF8}
Build theory 'D:\DEV\ai-database-book\book\chapter06\chapter06.md' 26 "$dst\chapter06_theory_slides.js"
Build practice 'D:\DEV\ai-database-book\book\chapter06\chapter06_activity.md' 25 "$dst\chapter06_practice_slides.js"

