-- Chapter 15. AI 튜터링 질문 관리 서비스 스키마
-- 기존 프로젝트·앞 장 스키마·Role을 자동으로 변경하지 않습니다.
-- 처음부터 다시 시작할 때만 reset_tutor_project.sql을 별도로 사용합니다.

SELECT
    current_user AS current_user_name,
    current_database() AS current_database_name,
    current_schema() AS current_schema_name;

SELECT
    to_regnamespace('course_project') AS course_project_schema,
    to_regnamespace('transaction_lab') AS transaction_lab_schema,
    to_regnamespace('performance_lab') AS performance_lab_schema,
    to_regnamespace('security_lab') AS security_lab_schema,
    to_regnamespace('nosql_lab') AS nosql_lab_schema,
    to_regnamespace('ai_review_lab') AS ai_review_lab_schema,
    to_regnamespace('rag_lab') AS rag_lab_schema;

CREATE SCHEMA tutor_project;

CREATE TABLE tutor_project.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    joined_at DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_tutor_project_students_email
        UNIQUE (email),
    CONSTRAINT chk_tutor_project_students_name
        CHECK (char_length(trim(name)) > 0)
);

CREATE TABLE tutor_project.tutors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    specialty VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_tutor_project_tutors_email
        UNIQUE (email),
    CONSTRAINT chk_tutor_project_tutors_name
        CHECK (char_length(trim(name)) > 0),
    CONSTRAINT chk_tutor_project_tutors_specialty
        CHECK (char_length(trim(specialty)) > 0)
);

CREATE TABLE tutor_project.questions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    question_code VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tutor_project_questions_student
        FOREIGN KEY (student_id)
        REFERENCES tutor_project.students(id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_tutor_project_questions_code
        UNIQUE (question_code),
    CONSTRAINT chk_tutor_project_questions_title
        CHECK (char_length(trim(title)) > 0),
    CONSTRAINT chk_tutor_project_questions_body
        CHECK (char_length(trim(body)) > 0),
    CONSTRAINT chk_tutor_project_questions_status
        CHECK (status IN ('open', 'answered', 'closed'))
);

CREATE TABLE tutor_project.answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INTEGER NOT NULL,
    tutor_id INTEGER NOT NULL,
    answer_body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tutor_project_answers_question
        FOREIGN KEY (question_id)
        REFERENCES tutor_project.questions(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_tutor_project_answers_tutor
        FOREIGN KEY (tutor_id)
        REFERENCES tutor_project.tutors(id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_tutor_project_answers_body
        CHECK (char_length(trim(answer_body)) > 0)
);

CREATE TABLE tutor_project.learning_materials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    material_type VARCHAR(30) NOT NULL,
    content_summary TEXT NOT NULL,
    source_url TEXT,
    access_scope VARCHAR(20) NOT NULL DEFAULT 'public',
    source_version VARCHAR(20) NOT NULL DEFAULT 'v1',
    content_hash VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_tutor_project_materials_code
        UNIQUE (material_code),
    CONSTRAINT chk_tutor_project_materials_title
        CHECK (char_length(trim(title)) > 0),
    CONSTRAINT chk_tutor_project_materials_summary
        CHECK (char_length(trim(content_summary)) > 0),
    CONSTRAINT chk_tutor_project_materials_type
        CHECK (material_type IN ('article', 'document', 'video', 'quiz')),
    CONSTRAINT chk_tutor_project_materials_scope
        CHECK (access_scope IN ('public', 'internal', 'restricted')),
    CONSTRAINT chk_tutor_project_materials_hash
        CHECK (char_length(trim(content_hash)) > 0)
);

CREATE TABLE tutor_project.question_materials (
    question_id INTEGER NOT NULL,
    material_id INTEGER NOT NULL,
    display_order INTEGER NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tutor_project_question_materials
        PRIMARY KEY (question_id, material_id),
    CONSTRAINT fk_tutor_project_qm_question
        FOREIGN KEY (question_id)
        REFERENCES tutor_project.questions(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_tutor_project_qm_material
        FOREIGN KEY (material_id)
        REFERENCES tutor_project.learning_materials(id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_tutor_project_qm_display_order
        UNIQUE (question_id, display_order),
    CONSTRAINT chk_tutor_project_qm_display_order
        CHECK (display_order > 0)
);

-- 반복 조회 패턴이 명확한 세 인덱스입니다.
CREATE INDEX idx_tutor_project_questions_student_status_created
ON tutor_project.questions (student_id, status, created_at DESC);

CREATE INDEX idx_tutor_project_answers_question_created
ON tutor_project.answers (question_id, created_at);

CREATE INDEX idx_tutor_project_qm_material
ON tutor_project.question_materials (material_id);

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'tutor_project'
ORDER BY table_name;
