-- Chapter 10. performance_lab 스키마 생성
-- 목적: 기존 프로젝트를 보호하면서 인덱스 성능 실험용 테이블을 만듭니다.
-- 주의: 기존 스키마나 테이블을 자동으로 삭제하지 않습니다.

SELECT current_database();
SELECT current_schema();

-- 앞 장 데이터가 유지되는지 확인
SELECT COUNT(*) AS project_enrollment_count
FROM course_project.enrollments;

CREATE SCHEMA performance_lab;

CREATE TABLE performance_lab.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    joined_at DATE NOT NULL,
    CONSTRAINT chk_performance_students_name
        CHECK (char_length(trim(name)) > 0)
);

CREATE TABLE performance_lab.instructors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    specialty VARCHAR(100) NOT NULL,
    CONSTRAINT chk_performance_instructors_name
        CHECK (char_length(trim(name)) > 0)
);

CREATE TABLE performance_lab.courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    level VARCHAR(20) NOT NULL,
    price INTEGER NOT NULL,
    opened_at DATE NOT NULL,

    CONSTRAINT fk_performance_courses_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES performance_lab.instructors(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_performance_courses_title
        CHECK (char_length(trim(title)) > 0),

    CONSTRAINT chk_performance_courses_level
        CHECK (level IN ('basic', 'intermediate', 'advanced')),

    CONSTRAINT chk_performance_courses_price
        CHECK (price >= 0)
);

CREATE TABLE performance_lab.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    enrolled_at DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_amount INTEGER NOT NULL,

    CONSTRAINT fk_performance_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES performance_lab.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_performance_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES performance_lab.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_performance_enrollments_status
        CHECK (status IN ('신청', '수강중', '완료', '취소')),

    CONSTRAINT chk_performance_enrollments_amount
        CHECK (paid_amount >= 0)
);

SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'performance_lab'
ORDER BY table_name;
