-- Chapter 07. 온라인 강의 수강신청 프로젝트 스키마
-- 목적: course_project 전용 스키마와 네 테이블·제약조건을 생성합니다.
-- 주의: 기존 객체를 자동으로 삭제하지 않습니다.
-- 같은 스키마가 이미 존재하면 reset_course_project.sql 실행 여부를 먼저 검토합니다.
-- 자동 커밋 상태에서는 일부 CREATE만 반영될 수 있으므로 실행 후 객체를 확인합니다.

-- ============================================================
-- 0. 현재 실행 위치 확인
-- 기대 데이터베이스: ai_database_book
-- 전용 스키마 이름을 모든 객체에 명시하므로 current_schema가 course_project일 필요는 없습니다.
-- ============================================================
SELECT current_database();
SELECT current_schema();
SHOW search_path;

-- ============================================================
-- 1. 프로젝트 전용 스키마
-- ============================================================
CREATE SCHEMA course_project;

-- ============================================================
-- 2. 학생
-- P07-R01: 학생은 이름, 이메일, 가입일을 가집니다.
-- P07-R10: 학생 이메일은 공백일 수 없고 정확히 같은 문자열은 중복될 수 없습니다.
-- 이메일 대소문자와 별칭 정규화는 이번 범위에서 다루지 않습니다.
-- ============================================================
CREATE TABLE course_project.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    joined_at DATE NOT NULL,

    CONSTRAINT uq_course_students_email
        UNIQUE (email),

    CONSTRAINT chk_course_students_name_not_blank
        CHECK (char_length(trim(name)) > 0),

    CONSTRAINT chk_course_students_email_not_blank
        CHECK (char_length(trim(email)) > 0)
);

-- ============================================================
-- 3. 강사
-- P07-R02: 강사는 이름, 이메일, 전문 분야를 가집니다.
-- P07-R10: 강사 이메일은 공백일 수 없고 정확히 같은 문자열은 중복될 수 없습니다.
-- ============================================================
CREATE TABLE course_project.instructors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    specialty VARCHAR(100) NOT NULL,

    CONSTRAINT uq_course_instructors_email
        UNIQUE (email),

    CONSTRAINT chk_course_instructors_name_not_blank
        CHECK (char_length(trim(name)) > 0),

    CONSTRAINT chk_course_instructors_email_not_blank
        CHECK (char_length(trim(email)) > 0),

    CONSTRAINT chk_course_instructors_specialty_not_blank
        CHECK (char_length(trim(specialty)) > 0)
);

-- ============================================================
-- 4. 강의
-- P07-R03: 제목, 선택 설명, 난이도, 가격과 개설일을 가집니다.
-- P07-R04·R05: 강의는 정확히 한 강사를 참조하고 강사는 여러 강의를 담당할 수 있습니다.
-- P07-D01: 무료 강의의 가격은 NULL이 아니라 0으로 저장합니다.
-- ============================================================
CREATE TABLE course_project.courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    level VARCHAR(20) NOT NULL,
    price INTEGER NOT NULL,
    opened_at DATE NOT NULL,

    CONSTRAINT fk_course_courses_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES course_project.instructors(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_course_courses_title_not_blank
        CHECK (char_length(trim(title)) > 0),

    CONSTRAINT chk_course_courses_level
        CHECK (level IN ('basic', 'intermediate', 'advanced')),

    CONSTRAINT chk_course_courses_price
        CHECK (price >= 0)
);

-- ============================================================
-- 5. 수강신청 사건
-- P07-R06~R09: 학생·강의 관계, 신청일, 상태와 실제 결제 금액을 저장합니다.
-- P07-D01: 무료 신청의 paid_amount는 NULL이 아니라 0으로 저장합니다.
-- P07-D02: 취소되어도 신청 당시 금액은 보존하며 환불 정보는 별도 범위입니다.
-- ============================================================
CREATE TABLE course_project.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    enrolled_at DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_amount INTEGER NOT NULL,

    CONSTRAINT fk_course_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES course_project.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_course_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES course_project.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_course_enrollments_status
        CHECK (status IN ('신청', '수강중', '완료', '취소')),

    CONSTRAINT chk_course_enrollments_paid_amount
        CHECK (paid_amount >= 0)
);

-- ============================================================
-- 6. 동시에 진행 중인 중복 신청 차단
-- P07-D03: 학생·강의 조합당 신청 또는 수강중 상태는 최대 한 건입니다.
-- 완료·취소 이력은 여러 건 저장할 수 있습니다.
-- ============================================================
CREATE UNIQUE INDEX uq_course_enrollments_active
ON course_project.enrollments (student_id, course_id)
WHERE status IN ('신청', '수강중');

-- DBeaver 탐색 위치:
-- Schemas -> course_project -> Tables
-- Schemas -> course_project -> Tables -> enrollments -> Indexes
