-- Chapter 07. 온라인 강의 수강신청 프로젝트 스키마
-- 목적: course_project 전용 스키마와 네 테이블을 생성합니다.
-- 주의: 기존 객체를 자동으로 삭제하지 않습니다.
-- 같은 스키마가 이미 존재하면 reset_course_project.sql 실행 여부를 먼저 검토합니다.

SELECT current_database();
SELECT current_schema();

CREATE SCHEMA course_project;

CREATE TABLE course_project.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    joined_at DATE NOT NULL,
    CONSTRAINT chk_course_students_name_not_blank
        CHECK (char_length(trim(name)) > 0)
);

CREATE TABLE course_project.instructors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    specialty VARCHAR(100) NOT NULL,
    CONSTRAINT chk_course_instructors_name_not_blank
        CHECK (char_length(trim(name)) > 0),
    CONSTRAINT chk_course_instructors_specialty_not_blank
        CHECK (char_length(trim(specialty)) > 0)
);

CREATE TABLE course_project.courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    level VARCHAR(20) NOT NULL,
    price INTEGER NOT NULL,
    opened_at DATE NOT NULL,

    CONSTRAINT fk_course_courses_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES course_project.instructors(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_course_courses_title_not_blank
        CHECK (char_length(trim(title)) > 0),

    CONSTRAINT chk_course_courses_level
        CHECK (level IN ('basic', 'intermediate', 'advanced')),

    CONSTRAINT chk_course_courses_price
        CHECK (price >= 0)
);

CREATE TABLE course_project.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    enrolled_at DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_amount INTEGER NOT NULL,

    CONSTRAINT fk_course_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES course_project.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_course_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES course_project.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_course_enrollments_status
        CHECK (status IN ('신청', '수강중', '완료', '취소')),

    CONSTRAINT chk_course_enrollments_paid_amount
        CHECK (paid_amount >= 0)
);

-- DBeaver 탐색 위치:
-- Schemas -> course_project -> Tables
