-- Chapter 13. ai_review_lab 스키마와 나쁜 설계 테이블 생성
-- 목적: 기존 프로젝트를 보호하면서 AI 설계 검토를 격리합니다.
-- 주의: 기존 스키마나 테이블을 자동으로 삭제하지 않습니다.

SELECT
    current_user AS current_user_name,
    current_database() AS current_database_name,
    current_schema() AS current_schema_name;

-- 앞 장 스키마는 존재 여부만 확인하고 변경하지 않습니다.
SELECT
    to_regnamespace('course_project') AS course_project_schema,
    to_regnamespace('transaction_lab') AS transaction_lab_schema,
    to_regnamespace('performance_lab') AS performance_lab_schema,
    to_regnamespace('security_lab') AS security_lab_schema,
    to_regnamespace('nosql_lab') AS nosql_lab_schema;

CREATE SCHEMA ai_review_lab;

-- 교육 목적상 일부러 역할 혼합, 약한 타입, FK 부재와
-- 평문 민감정보 형태의 문제를 포함한 나쁜 설계입니다.
CREATE TABLE ai_review_lab.bad_enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT,
    student_email TEXT,
    course_title TEXT,
    course_price TEXT,
    instructor_name TEXT,
    payment_status TEXT,
    sensitive_value_plaintext TEXT,
    enrollment_status TEXT,
    created_at TEXT
);

SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'ai_review_lab'
ORDER BY table_name;
