-- Chapter 13. ai_review_lab 스키마와 나쁜 설계 테이블 생성
-- 목적: 기존 프로젝트를 보호하면서 AI 설계 검토를 격리합니다.
-- 주의: 기존 스키마나 테이블을 자동으로 삭제하지 않습니다.

SELECT current_user AS current_user_name;
SELECT current_database();
SELECT current_schema();
SHOW search_path;

-- ============================================================
-- P13-V01. 실행 위치와 기준 상태 보호
-- ============================================================
DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '실행 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF to_regclass('course_project.enrollments') IS NULL THEN
        RAISE EXCEPTION
            '실행 중단: Chapter 07의 course_project.enrollments가 없습니다.';
    END IF;

    IF (SELECT COUNT(*) FROM course_project.enrollments) <> 5 THEN
        RAISE EXCEPTION
            '실행 중단: course_project.enrollments는 기준 5행이어야 합니다.';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_namespace
        WHERE nspname = 'ai_review_lab'
    ) THEN
        RAISE EXCEPTION
            '실행 중단: ai_review_lab이 이미 존재합니다. 보존 여부를 확인한 뒤 reset_ai_review_lab.sql 사용을 검토하세요.';
    END IF;
END
$$;

-- 앞 장 스키마는 존재 여부만 확인하고 변경하지 않습니다.
SELECT
    to_regnamespace('course_project') AS course_project_schema,
    to_regnamespace('transaction_lab') AS transaction_lab_schema,
    to_regnamespace('performance_lab') AS performance_lab_schema,
    to_regnamespace('security_lab') AS security_lab_schema,
    to_regnamespace('nosql_lab') AS nosql_lab_schema;

-- ============================================================
-- P13-T01. 나쁜 설계 기준선 생성
-- 중간 실패 시 일부 객체만 남지 않도록 하나의 트랜잭션으로 처리합니다.
-- ============================================================
BEGIN;

CREATE SCHEMA ai_review_lab;

-- 교육 목적상 역할 혼합, 약한 타입, FK 부재와 평문 민감정보 형태의
-- 문제를 의도적으로 포함합니다. 실제 개인정보·카드번호는 사용하지 않습니다.
CREATE TABLE ai_review_lab.bad_enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT,
    student_email TEXT,
    course_title TEXT,
    course_price TEXT,
    instructor_name TEXT,
    payment_status TEXT,
    sensitive_value_plaintext TEXT,
    enrollment_status TEXT,
    created_at TEXT
);

COMMIT;

-- ============================================================
-- 생성 결과 확인
-- ============================================================
SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'ai_review_lab'
ORDER BY table_name;

SELECT
    to_regclass('ai_review_lab.bad_enrollments') IS NOT NULL
        AS bad_design_table_created;
