-- Chapter 13. 요구사항을 기준으로 보완한 좋은 설계
-- 실행 전 01_ai_review_lab_schema.sql을 먼저 실행합니다.
-- 미확정 정책인 재신청 금지와 CASCADE 삭제는 적용하지 않습니다.

SELECT current_database();

CREATE TABLE ai_review_lab.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    joined_at DATE NOT NULL,

    CONSTRAINT uq_ai_review_students_email
        UNIQUE (email),

    CONSTRAINT chk_ai_review_students_name
        CHECK (char_length(trim(name)) > 0)
);

CREATE TABLE ai_review_lab.instructors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    specialty VARCHAR(100) NOT NULL,

    CONSTRAINT uq_ai_review_instructors_email
        UNIQUE (email),

    CONSTRAINT chk_ai_review_instructors_name
        CHECK (char_length(trim(name)) > 0)
);

CREATE TABLE ai_review_lab.courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id INTEGER NOT NULL,
    course_code VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    level VARCHAR(20) NOT NULL,
    price INTEGER NOT NULL,
    opened_at DATE NOT NULL,

    CONSTRAINT fk_ai_review_courses_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES ai_review_lab.instructors(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_ai_review_courses_code
        UNIQUE (course_code),

    CONSTRAINT chk_ai_review_courses_title
        CHECK (char_length(trim(title)) > 0),

    CONSTRAINT chk_ai_review_courses_level
        CHECK (level IN ('basic', 'intermediate', 'advanced')),

    CONSTRAINT chk_ai_review_courses_price
        CHECK (price >= 0)
);

CREATE TABLE ai_review_lab.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    agreed_amount INTEGER NOT NULL,
    enrolled_at DATE NOT NULL,

    CONSTRAINT fk_ai_review_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES ai_review_lab.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_ai_review_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES ai_review_lab.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_ai_review_enrollments_status
        CHECK (status IN ('신청', '수강중', '완료', '취소')),

    CONSTRAINT chk_ai_review_enrollments_amount
        CHECK (agreed_amount >= 0)
);

-- 재신청 정책이 미확정이므로
-- UNIQUE(student_id, course_id)는 적용하지 않습니다.

CREATE TABLE ai_review_lab.payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id INTEGER NOT NULL,
    amount INTEGER NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    paid_at TIMESTAMPTZ,
    payment_reference VARCHAR(100) NOT NULL,

    CONSTRAINT fk_ai_review_payments_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES ai_review_lab.enrollments(id)
        ON DELETE RESTRICT,

    -- 단순화 가정: 한 신청에 현재 결제 상태 한 건만 저장합니다.
    CONSTRAINT uq_ai_review_payments_enrollment
        UNIQUE (enrollment_id),

    CONSTRAINT uq_ai_review_payments_reference
        UNIQUE (payment_reference),

    CONSTRAINT chk_ai_review_payments_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_ai_review_payments_status
        CHECK (
            payment_status IN (
                '결제대기',
                '결제완료',
                '결제실패',
                '환불'
            )
        ),

    CONSTRAINT chk_ai_review_payments_paid_at
        CHECK (
            (
                payment_status IN ('결제완료', '환불')
                AND paid_at IS NOT NULL
            )
            OR
            (
                payment_status IN ('결제대기', '결제실패')
                AND paid_at IS NULL
            )
        )
);

SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'ai_review_lab'
ORDER BY table_name;
