-- Chapter 13. 요구사항을 기준으로 보완한 좋은 설계
-- 실행 전 01→02 파일을 순서대로 실행합니다.
-- Chapter 07에서 확정한 활성 신청 정책을 유지합니다.

SELECT current_database();
SELECT current_schema();
SHOW search_path;

-- ============================================================
-- P13-V03. 생성 전 상태 확인
-- ============================================================
DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '실행 중단: 현재 데이터베이스는 %입니다.',
            current_database();
    END IF;

    IF to_regclass('ai_review_lab.bad_enrollments') IS NULL
       OR (SELECT COUNT(*) FROM ai_review_lab.bad_enrollments) <> 3 THEN
        RAISE EXCEPTION
            '실행 중단: 나쁜 설계 기준 데이터 3행이 준비되지 않았습니다.';
    END IF;

    IF to_regclass('ai_review_lab.students') IS NOT NULL
       OR to_regclass('ai_review_lab.instructors') IS NOT NULL
       OR to_regclass('ai_review_lab.courses') IS NOT NULL
       OR to_regclass('ai_review_lab.enrollments') IS NOT NULL
       OR to_regclass('ai_review_lab.payments') IS NOT NULL THEN
        RAISE EXCEPTION
            '실행 중단: 좋은 설계 테이블이 이미 존재합니다.';
    END IF;
END
$$;

BEGIN;

-- P13-R01: 학생 이메일은 공백이 아니며 정확히 같은 문자열이 중복될 수 없습니다.
-- 이메일 대소문자 정규화는 P13-D07에서 별도 결정합니다.
CREATE TABLE ai_review_lab.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    joined_at DATE NOT NULL,

    CONSTRAINT uq_ai_review_students_email
        UNIQUE (email),

    CONSTRAINT chk_ai_review_students_name_not_blank
        CHECK (char_length(trim(name)) > 0),

    CONSTRAINT chk_ai_review_students_email_not_blank
        CHECK (char_length(trim(email)) > 0)
);

-- P13-R02: 강사 이메일은 공백이 아니며 정확히 같은 문자열이 중복될 수 없습니다.
CREATE TABLE ai_review_lab.instructors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    specialty VARCHAR(100) NOT NULL,

    CONSTRAINT uq_ai_review_instructors_email
        UNIQUE (email),

    CONSTRAINT chk_ai_review_instructors_name_not_blank
        CHECK (char_length(trim(name)) > 0),

    CONSTRAINT chk_ai_review_instructors_email_not_blank
        CHECK (char_length(trim(email)) > 0),

    CONSTRAINT chk_ai_review_instructors_specialty_not_blank
        CHECK (char_length(trim(specialty)) > 0)
);

-- P13-R03: 강의는 강사 한 명을 참조합니다.
CREATE TABLE ai_review_lab.courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id INTEGER NOT NULL,
    course_code VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    level VARCHAR(20) NOT NULL,
    price INTEGER NOT NULL,
    opened_at DATE NOT NULL,

    CONSTRAINT fk_ai_review_courses_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES ai_review_lab.instructors(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_ai_review_courses_code
        UNIQUE (course_code),

    CONSTRAINT chk_ai_review_courses_code_not_blank
        CHECK (char_length(trim(course_code)) > 0),

    CONSTRAINT chk_ai_review_courses_title_not_blank
        CHECK (char_length(trim(title)) > 0),

    CONSTRAINT chk_ai_review_courses_level
        CHECK (level IN ('basic', 'intermediate', 'advanced')),

    CONSTRAINT chk_ai_review_courses_price
        CHECK (price >= 0)
);

-- P13-R04~R06: N:M 해소, 상태 허용값, 신청 시점 금액 0 이상
CREATE TABLE ai_review_lab.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    agreed_amount INTEGER NOT NULL,
    enrolled_at DATE NOT NULL,

    CONSTRAINT fk_ai_review_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES ai_review_lab.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_ai_review_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES ai_review_lab.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_ai_review_enrollments_status
        CHECK (status IN ('신청', '수강중', '완료', '취소')),

    CONSTRAINT chk_ai_review_enrollments_amount
        CHECK (agreed_amount >= 0)
);

-- P13-R09: Chapter 07에서 확정한 활성 신청 정책을 유지합니다.
-- 신청·수강중은 학생·강의 조합당 한 건이며 완료·취소 이력 뒤 재신청은 허용합니다.
CREATE UNIQUE INDEX uq_ai_review_enrollments_active
ON ai_review_lab.enrollments (student_id, course_id)
WHERE status IN ('신청', '수강중');

-- P13-R07~R08: 결제는 신청을 참조하며 카드번호 대신 외부 비민감 참조값만 저장합니다.
-- P13-D02: 한 신청의 현재 결제 상태 한 건만 보존하는 단순 모델입니다.
-- P13-D06: 환불 샘플은 전액 환불이며 부분 환불 원장은 범위 밖입니다.
CREATE TABLE ai_review_lab.payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id INTEGER NOT NULL,
    amount INTEGER NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    paid_at TIMESTAMPTZ,
    refunded_at TIMESTAMPTZ,
    payment_reference VARCHAR(100) NOT NULL,

    CONSTRAINT fk_ai_review_payments_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES ai_review_lab.enrollments(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_ai_review_payments_enrollment
        UNIQUE (enrollment_id),

    CONSTRAINT uq_ai_review_payments_reference
        UNIQUE (payment_reference),

    CONSTRAINT chk_ai_review_payments_reference_not_blank
        CHECK (char_length(trim(payment_reference)) > 0),

    CONSTRAINT chk_ai_review_payments_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_ai_review_payments_status
        CHECK (
            payment_status IN (
                '결제대기',
                '결제완료',
                '결제실패',
                '환불'
            )
        ),

    CONSTRAINT chk_ai_review_payments_timestamps
        CHECK (
            (
                payment_status IN ('결제대기', '결제실패')
                AND paid_at IS NULL
                AND refunded_at IS NULL
            )
            OR
            (
                payment_status = '결제완료'
                AND paid_at IS NOT NULL
                AND refunded_at IS NULL
            )
            OR
            (
                payment_status = '환불'
                AND paid_at IS NOT NULL
                AND refunded_at IS NOT NULL
                AND refunded_at >= paid_at
            )
        )
);

COMMIT;

SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'ai_review_lab'
ORDER BY table_name;

SELECT
    schemaname,
    tablename,
    indexname,
    indexdef
FROM pg_indexes
WHERE schemaname = 'ai_review_lab'
ORDER BY tablename, indexname;
