-- Chapter 11. security_lab 스키마 생성
-- 목적: 기존 프로젝트를 보호하면서 권한·백업·복원 검증용 테이블을 만듭니다.
-- 주의: 기존 스키마나 테이블을 자동으로 삭제하지 않습니다.

SELECT current_user AS current_user_name;
SELECT current_database();
SELECT current_schema();
SHOW search_path;

-- ============================================================
-- 0. 실행 전 보호 조건
-- ============================================================
DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '실행 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF to_regclass('course_project.enrollments') IS NULL THEN
        RAISE EXCEPTION
            '실행 중단: Chapter 07의 course_project.enrollments가 없습니다.';
    END IF;

    IF (SELECT COUNT(*) FROM course_project.enrollments) <> 5 THEN
        RAISE EXCEPTION
            '실행 중단: course_project.enrollments는 기준 5행이어야 합니다.';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_namespace
        WHERE nspname = 'security_lab'
    ) THEN
        RAISE EXCEPTION
            '실행 중단: security_lab 스키마가 이미 존재합니다. 보존 여부를 확인한 뒤 reset_security_lab.sql 사용을 검토하세요.';
    END IF;
END
$$;

-- ============================================================
-- 1. 스키마와 테이블 생성
-- 중간 실패 시 일부 객체만 남지 않도록 하나의 트랜잭션으로 처리합니다.
-- ============================================================
BEGIN;

CREATE SCHEMA security_lab;

CREATE TABLE security_lab.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    joined_at DATE NOT NULL,

    CONSTRAINT uq_security_students_email
        UNIQUE (email),

    CONSTRAINT chk_security_students_name_not_blank
        CHECK (char_length(trim(name)) > 0),

    CONSTRAINT chk_security_students_email_not_blank
        CHECK (char_length(trim(email)) > 0)
);

CREATE TABLE security_lab.courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    level VARCHAR(20) NOT NULL,
    price INTEGER NOT NULL,

    CONSTRAINT chk_security_courses_title_not_blank
        CHECK (char_length(trim(title)) > 0),

    CONSTRAINT chk_security_courses_level
        CHECK (level IN ('basic', 'intermediate', 'advanced')),

    CONSTRAINT chk_security_courses_price
        CHECK (price >= 0)
);

CREATE TABLE security_lab.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_amount INTEGER NOT NULL,
    enrolled_at DATE NOT NULL,

    CONSTRAINT fk_security_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES security_lab.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_security_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES security_lab.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_security_enrollments_status
        CHECK (status IN ('신청', '수강중', '완료', '취소')),

    CONSTRAINT chk_security_enrollments_amount
        CHECK (paid_amount >= 0)
);

-- Chapter 07에서 확정한 정책을 유지합니다.
-- 완료·취소 이력은 여러 건 허용하지만 진행 중 신청은 학생·강의당 한 건입니다.
CREATE UNIQUE INDEX uq_security_enrollments_active
ON security_lab.enrollments (student_id, course_id)
WHERE status IN ('신청', '수강중');

COMMIT;

-- ============================================================
-- 2. 생성 결과 확인
-- ============================================================
SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'security_lab'
ORDER BY table_name;

SELECT
    schemaname,
    tablename,
    indexname,
    indexdef
FROM pg_indexes
WHERE schemaname = 'security_lab'
ORDER BY tablename, indexname;
