-- Chapter 11. security_lab 스키마 생성
-- 목적: 기존 프로젝트를 보호하면서 권한·백업·복원 검증용 테이블을 만듭니다.
-- 주의: 기존 스키마나 테이블을 자동으로 삭제하지 않습니다.

SELECT
    current_user AS current_user_name,
    current_database() AS current_database_name,
    current_schema() AS current_schema_name;

-- 앞 장 프로젝트가 유지되는지 확인
SELECT COUNT(*) AS project_enrollment_count
FROM course_project.enrollments;

CREATE SCHEMA security_lab;

CREATE TABLE security_lab.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    joined_at DATE NOT NULL,

    CONSTRAINT chk_security_students_name
        CHECK (char_length(trim(name)) > 0)
);

CREATE TABLE security_lab.courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    level VARCHAR(20) NOT NULL,
    price INTEGER NOT NULL,

    CONSTRAINT chk_security_courses_title
        CHECK (char_length(trim(title)) > 0),

    CONSTRAINT chk_security_courses_level
        CHECK (level IN ('basic', 'intermediate', 'advanced')),

    CONSTRAINT chk_security_courses_price
        CHECK (price >= 0)
);

CREATE TABLE security_lab.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_amount INTEGER NOT NULL,
    enrolled_at DATE NOT NULL,

    CONSTRAINT fk_security_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES security_lab.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_security_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES security_lab.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_security_enrollments_status
        CHECK (status IN ('신청', '수강중', '완료', '취소')),

    CONSTRAINT chk_security_enrollments_amount
        CHECK (paid_amount >= 0)
);

-- 같은 학생의 같은 강의 재신청 정책이 미확정이므로
-- UNIQUE(student_id, course_id)는 적용하지 않습니다.

SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'security_lab'
ORDER BY table_name;
