flowchart TB
    A[1NF 적용 전]
    A --> B[borrowed_books 컬럼]
    B --> C[데이터베이스 입문, SQL 기초]

    C --> D[한 칸에 여러 값]
    D --> E[검색 / 수정 / 관리 어려움]

    E --> F[1NF 적용]
    F --> G[한 칸에는 하나의 값]

    G --> H[김민지 - 데이터베이스 입문]
    G --> I[김민지 - SQL 기초]
    G --> J[이준호 - 데이터베이스 입문]
