-- Chapter 14. SQL 데이터 분석과 Python 확장
-- 목적: analysis_lab 전용 스키마와 분석 기준 테이블을 생성합니다.
-- 주의: 기존 객체를 자동으로 삭제하지 않습니다.

SELECT current_database();
SELECT current_user;
SELECT current_schema();

CREATE SCHEMA analysis_lab;

CREATE TABLE analysis_lab.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    region VARCHAR(20) NOT NULL,
    joined_at DATE NOT NULL,

    CONSTRAINT chk_analysis_students_name_not_blank
        CHECK (char_length(trim(name)) > 0),
    CONSTRAINT chk_analysis_students_region
        CHECK (region IN ('서울', '경기', '부산', '대구'))
);

CREATE TABLE analysis_lab.instructors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    specialty VARCHAR(50) NOT NULL,

    CONSTRAINT chk_analysis_instructors_name_not_blank
        CHECK (char_length(trim(name)) > 0),
    CONSTRAINT chk_analysis_instructors_specialty_not_blank
        CHECK (char_length(trim(specialty)) > 0)
);

CREATE TABLE analysis_lab.courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id INTEGER NOT NULL,
    title VARCHAR(120) NOT NULL,
    category VARCHAR(30) NOT NULL,
    level VARCHAR(20) NOT NULL,
    price INTEGER NOT NULL,
    opened_at DATE NOT NULL,

    CONSTRAINT fk_analysis_courses_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES analysis_lab.instructors(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_analysis_courses_title_not_blank
        CHECK (char_length(trim(title)) > 0),
    CONSTRAINT chk_analysis_courses_category
        CHECK (category IN ('Database', 'Python', 'Data Analysis', 'AI')),
    CONSTRAINT chk_analysis_courses_level
        CHECK (level IN ('basic', 'intermediate', 'advanced')),
    CONSTRAINT chk_analysis_courses_price
        CHECK (price >= 0)
);

CREATE TABLE analysis_lab.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    enrolled_at DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_amount INTEGER NOT NULL,
    completed_at DATE,

    CONSTRAINT fk_analysis_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES analysis_lab.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_analysis_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES analysis_lab.courses(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_analysis_enrollments_student_course_date
        UNIQUE (student_id, course_id, enrolled_at),

    CONSTRAINT chk_analysis_enrollments_status
        CHECK (status IN ('신청', '수강중', '완료', '취소')),

    CONSTRAINT chk_analysis_enrollments_paid_amount
        CHECK (paid_amount >= 0),

    CONSTRAINT chk_analysis_enrollments_cancel_amount
        CHECK (
            (status = '취소' AND paid_amount = 0)
            OR
            (status <> '취소' AND paid_amount >= 0)
        ),

    CONSTRAINT chk_analysis_enrollments_completion_state
        CHECK (
            (status = '완료' AND completed_at IS NOT NULL)
            OR
            (status <> '완료' AND completed_at IS NULL)
        ),

    CONSTRAINT chk_analysis_enrollments_completion_date
        CHECK (completed_at IS NULL OR completed_at >= enrolled_at)
);

-- DBeaver 탐색 위치:
-- Schemas -> analysis_lab -> Tables
