-- Chapter 14. SQL 데이터 분석과 Python 확장
-- 목적: analysis_lab 전용 스키마와 분석 기준 테이블을 생성합니다.
-- 주의: 기존 객체를 자동으로 삭제하지 않습니다.

SELECT current_database();
SELECT current_user;
SELECT current_schema();
SHOW search_path;

-- ============================================================
-- P14-V01. 실행 위치와 기존 객체 보호
-- ============================================================
DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '실행 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF to_regnamespace('analysis_lab') IS NOT NULL THEN
        RAISE EXCEPTION
            '실행 중단: analysis_lab이 이미 존재합니다. 보존 여부를 확인한 뒤 reset_analysis_lab.sql 사용을 검토하세요.';
    END IF;
END
$$;

-- ============================================================
-- 스키마·테이블·분석 기간 VIEW를 하나의 트랜잭션에서 생성
-- ============================================================
BEGIN;

CREATE SCHEMA analysis_lab;

CREATE TABLE analysis_lab.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    region VARCHAR(20) NOT NULL,
    joined_at DATE NOT NULL,

    CONSTRAINT chk_analysis_students_name_not_blank
        CHECK (char_length(trim(name)) > 0),
    CONSTRAINT chk_analysis_students_region
        CHECK (region IN ('서울', '경기', '부산', '대구'))
);

CREATE TABLE analysis_lab.instructors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    specialty VARCHAR(50) NOT NULL,

    CONSTRAINT chk_analysis_instructors_name_not_blank
        CHECK (char_length(trim(name)) > 0),
    CONSTRAINT chk_analysis_instructors_specialty_not_blank
        CHECK (char_length(trim(specialty)) > 0)
);

CREATE TABLE analysis_lab.courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id INTEGER NOT NULL,
    title VARCHAR(120) NOT NULL,
    category VARCHAR(30) NOT NULL,
    level VARCHAR(20) NOT NULL,
    price INTEGER NOT NULL,
    opened_at DATE NOT NULL,

    CONSTRAINT fk_analysis_courses_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES analysis_lab.instructors(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_analysis_courses_title_not_blank
        CHECK (char_length(trim(title)) > 0),
    CONSTRAINT chk_analysis_courses_category
        CHECK (category IN ('Database', 'Python', 'Data Analysis', 'AI')),
    CONSTRAINT chk_analysis_courses_level
        CHECK (level IN ('basic', 'intermediate', 'advanced')),
    CONSTRAINT chk_analysis_courses_price
        CHECK (price >= 0)
);

CREATE TABLE analysis_lab.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    enrolled_at DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    paid_amount INTEGER NOT NULL,
    completed_at DATE,

    CONSTRAINT fk_analysis_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES analysis_lab.students(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_analysis_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES analysis_lab.courses(id)
        ON DELETE RESTRICT,

    -- 같은 날짜의 동일 원천 행이 중복 적재되는 것을 막는 수집 규칙입니다.
    CONSTRAINT uq_analysis_enrollments_student_course_date
        UNIQUE (student_id, course_id, enrolled_at),

    CONSTRAINT chk_analysis_enrollments_status
        CHECK (status IN ('신청', '수강중', '완료', '취소')),

    CONSTRAINT chk_analysis_enrollments_paid_amount
        CHECK (paid_amount >= 0),

    CONSTRAINT chk_analysis_enrollments_cancel_amount
        CHECK (
            (status = '취소' AND paid_amount = 0)
            OR
            (status <> '취소' AND paid_amount >= 0)
        ),

    CONSTRAINT chk_analysis_enrollments_completion_state
        CHECK (
            (status = '완료' AND completed_at IS NOT NULL)
            OR
            (status <> '완료' AND completed_at IS NULL)
        ),

    CONSTRAINT chk_analysis_enrollments_completion_date
        CHECK (completed_at IS NULL OR completed_at >= enrolled_at)
);

-- Chapter 07에서 확정한 활성 신청 규칙을 유지합니다.
-- 신청·수강중은 학생·강의 조합당 최대 한 건이며 완료·취소 이력 뒤 재신청은 허용합니다.
CREATE UNIQUE INDEX uq_analysis_enrollments_active
ON analysis_lab.enrollments (student_id, course_id)
WHERE status IN ('신청', '수강중');

-- 모든 SQL과 Python 분석이 같은 반개방 기간을 사용하도록 한 곳에 고정합니다.
CREATE VIEW analysis_lab.analysis_parameters AS
SELECT
    DATE '2026-01-01' AS start_date,
    DATE '2026-07-01' AS end_date_exclusive;

COMMIT;

-- 생성 결과 확인
SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'analysis_lab'
ORDER BY table_name;

SELECT
    table_schema,
    table_name
FROM information_schema.views
WHERE table_schema = 'analysis_lab'
ORDER BY table_name;

SELECT *
FROM analysis_lab.analysis_parameters;

-- DBeaver 탐색 위치:
-- Schemas -> analysis_lab -> Tables / Views
