-- Chapter 14. rag_lab 스키마 생성
-- 목적: 기존 프로젝트를 보호하면서 벡터 검색과 RAG 평가를 격리합니다.
-- 주의: 기존 스키마·테이블·Role·확장을 자동으로 변경하지 않습니다.

SELECT
    current_user AS current_user_name,
    current_database() AS current_database_name,
    current_schema() AS current_schema_name;

-- 앞 장 스키마는 존재 여부만 확인합니다.
SELECT
    to_regnamespace('course_project') AS course_project_schema,
    to_regnamespace('transaction_lab') AS transaction_lab_schema,
    to_regnamespace('performance_lab') AS performance_lab_schema,
    to_regnamespace('security_lab') AS security_lab_schema,
    to_regnamespace('nosql_lab') AS nosql_lab_schema,
    to_regnamespace('ai_review_lab') AS ai_review_lab_schema;

CREATE SCHEMA rag_lab;

CREATE TABLE rag_lab.document_sources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_key TEXT NOT NULL,
    title TEXT NOT NULL,
    source_path TEXT NOT NULL,
    source_version TEXT NOT NULL,
    access_scope TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    content_hash TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT uq_rag_document_source_version
        UNIQUE (document_key, source_version),

    CONSTRAINT chk_rag_document_title
        CHECK (char_length(trim(title)) > 0),

    CONSTRAINT chk_rag_document_access_scope
        CHECK (access_scope IN ('public', 'internal', 'restricted')),

    CONSTRAINT chk_rag_document_hash
        CHECK (char_length(trim(content_hash)) > 0)
);

CREATE TABLE rag_lab.document_chunks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id INTEGER NOT NULL,
    chunk_no INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,
    chunk_strategy_version TEXT NOT NULL,
    embedding_source TEXT NOT NULL,
    embedding_dimension INTEGER NOT NULL,
    embedding_x NUMERIC(10, 6) NOT NULL,
    embedding_y NUMERIC(10, 6) NOT NULL,
    embedding_z NUMERIC(10, 6) NOT NULL,
    embedded_at TIMESTAMPTZ NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_rag_chunks_source
        FOREIGN KEY (source_id)
        REFERENCES rag_lab.document_sources(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_rag_source_chunk_strategy
        UNIQUE (source_id, chunk_no, chunk_strategy_version),

    CONSTRAINT chk_rag_chunk_no
        CHECK (chunk_no > 0),

    CONSTRAINT chk_rag_chunk_text
        CHECK (char_length(trim(chunk_text)) > 0),

    CONSTRAINT chk_rag_embedding_dimension
        CHECK (embedding_dimension = 3)
);

CREATE TABLE rag_lab.query_cases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text TEXT NOT NULL,
    requester_scope TEXT NOT NULL,
    embedding_source TEXT NOT NULL,
    embedding_dimension INTEGER NOT NULL,
    embedding_x NUMERIC(10, 6) NOT NULL,
    embedding_y NUMERIC(10, 6) NOT NULL,
    embedding_z NUMERIC(10, 6) NOT NULL,
    top_k INTEGER NOT NULL,
    distance_threshold NUMERIC(10, 6) NOT NULL,
    expected_action TEXT NOT NULL,

    CONSTRAINT chk_rag_query_text
        CHECK (char_length(trim(question_text)) > 0),

    CONSTRAINT chk_rag_query_scope
        CHECK (requester_scope IN ('public', 'internal', 'restricted')),

    CONSTRAINT chk_rag_query_dimension
        CHECK (embedding_dimension = 3),

    CONSTRAINT chk_rag_query_top_k
        CHECK (top_k > 0),

    CONSTRAINT chk_rag_query_threshold
        CHECK (distance_threshold >= 0),

    CONSTRAINT chk_rag_expected_action
        CHECK (expected_action IN ('answer', 'abstain'))
);

CREATE TABLE rag_lab.relevance_judgments (
    query_id INTEGER NOT NULL,
    chunk_id INTEGER NOT NULL,
    relevance_grade INTEGER NOT NULL,
    judgment_note TEXT NOT NULL,

    CONSTRAINT pk_rag_relevance_judgments
        PRIMARY KEY (query_id, chunk_id),

    CONSTRAINT fk_rag_judgment_query
        FOREIGN KEY (query_id)
        REFERENCES rag_lab.query_cases(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_rag_judgment_chunk
        FOREIGN KEY (chunk_id)
        REFERENCES rag_lab.document_chunks(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_rag_relevance_grade
        CHECK (relevance_grade IN (1, 2))
);

CREATE TABLE rag_lab.retrieval_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_label TEXT NOT NULL,
    query_id INTEGER NOT NULL,
    rank_no INTEGER NOT NULL,
    chunk_id INTEGER NOT NULL,
    l2_distance NUMERIC(12, 8) NOT NULL,
    passed_threshold BOOLEAN NOT NULL,
    embedding_source TEXT NOT NULL,
    filter_note TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_rag_retrieval_run_rank
        UNIQUE (run_label, query_id, rank_no),

    CONSTRAINT fk_rag_retrieval_query
        FOREIGN KEY (query_id)
        REFERENCES rag_lab.query_cases(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_rag_retrieval_chunk
        FOREIGN KEY (chunk_id)
        REFERENCES rag_lab.document_chunks(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_rag_retrieval_rank
        CHECK (rank_no > 0),

    CONSTRAINT chk_rag_retrieval_distance
        CHECK (l2_distance >= 0)
);

CREATE TABLE rag_lab.answer_reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id INTEGER NOT NULL,
    review_case TEXT NOT NULL UNIQUE,
    generated_answer TEXT NOT NULL,
    cited_chunk_ids INTEGER[] NOT NULL DEFAULT '{}',
    is_search_relevant BOOLEAN NOT NULL,
    access_allowed BOOLEAN NOT NULL,
    freshness_ok BOOLEAN NOT NULL,
    citations_present BOOLEAN NOT NULL,
    all_claims_supported BOOLEAN NOT NULL,
    has_unsupported_claim BOOLEAN NOT NULL,
    expected_abstain BOOLEAN NOT NULL,
    answer_abstained BOOLEAN NOT NULL,
    review_note TEXT NOT NULL,

    CONSTRAINT fk_rag_answer_review_query
        FOREIGN KEY (query_id)
        REFERENCES rag_lab.query_cases(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_rag_answer_support_consistency
        CHECK (NOT (all_claims_supported AND has_unsupported_claim)),

    CONSTRAINT chk_rag_answer_text
        CHECK (char_length(trim(generated_answer)) > 0)
);

SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'rag_lab'
ORDER BY table_name;
