flowchart LR
    A[BEGIN] --> B[SQL 1 실행]
    B --> C[SQL 2 실행]
    C --> D[SQL 3 실행]

    D --> E{문제 없음?}
    E -- 예 --> F[COMMIT]
    E -- 아니오 --> G[ROLLBACK]

    F --> H[변경 내용 확정]
    G --> I[변경 내용 취소]
