-- Chapter 06. 정규화와 데이터 무결성으로 좋은 테이블 만들기
-- 목적: 정규화 전 원시 테이블과 정규화 후 테이블·제약조건을 생성합니다.
-- 주의: 이 파일은 기존 테이블이나 데이터를 자동으로 삭제하지 않습니다.
-- Chapter 05 테이블과 충돌하지 않도록 _nf 접미사를 사용합니다.
-- 자동 커밋 상태에서는 일부 CREATE만 반영될 수 있으므로 실행 후 구조를 확인합니다.

-- ============================================================
-- 0. 현재 실행 위치 확인
-- 기대 결과: ai_database_book / public
-- ============================================================
SELECT current_database();
SELECT current_schema();
SHOW search_path;

-- ============================================================
-- 1. 정규화 전 원시 테이블
-- 회원·도서·대여 사실이 한 행에 섞여 있습니다.
-- ============================================================
CREATE TABLE public.library_records_raw (
    loan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_name VARCHAR(50) NOT NULL,
    member_email VARCHAR(100) NOT NULL,
    book_title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    borrowed_at DATE NOT NULL,
    due_at DATE NOT NULL,
    returned_at DATE
);

-- ============================================================
-- 2. 정규화 후 회원 테이블
-- C-01: 정확히 같은 이메일 문자열의 중복을 허용하지 않습니다.
-- C-03: 회원 이름은 공백 문자열일 수 없습니다.
-- ============================================================
CREATE TABLE public.members_nf (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    joined_at DATE NOT NULL,

    CONSTRAINT uq_members_nf_email
        UNIQUE (email),

    CONSTRAINT chk_members_nf_name_not_blank
        CHECK (char_length(trim(name)) > 0)
);

-- ============================================================
-- 3. 정규화 후 도서 테이블
-- C-02: 같은 ISBN 문자열의 도서를 중복 등록하지 않습니다.
-- C-03: 도서 제목은 공백 문자열일 수 없습니다.
-- published_year의 허용 범위는 확정되지 않아 별도 CHECK를 적용하지 않습니다.
-- ============================================================
CREATE TABLE public.books_nf (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    published_year INTEGER,
    isbn VARCHAR(20) NOT NULL,

    CONSTRAINT uq_books_nf_isbn
        UNIQUE (isbn),

    CONSTRAINT chk_books_nf_title_not_blank
        CHECK (char_length(trim(title)) > 0)
);

-- ============================================================
-- 4. 정규화 후 대여 사건 테이블
-- C-04·C-05: 날짜 선후 관계를 확인합니다.
-- C-06: 존재하는 회원과 도서만 참조합니다.
-- C-07: 참조 중인 부모 삭제를 RESTRICT로 차단합니다.
-- ============================================================
CREATE TABLE public.loans_nf (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    book_id INTEGER NOT NULL,
    borrowed_at DATE NOT NULL,
    due_at DATE NOT NULL,
    returned_at DATE,

    CONSTRAINT fk_loans_nf_member
        FOREIGN KEY (member_id)
        REFERENCES public.members_nf(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_loans_nf_book
        FOREIGN KEY (book_id)
        REFERENCES public.books_nf(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_loans_nf_due_date
        CHECK (due_at >= borrowed_at),

    CONSTRAINT chk_loans_nf_returned_date
        CHECK (
            returned_at IS NULL
            OR returned_at >= borrowed_at
        )
);

-- ============================================================
-- 5. 한 도서의 활성 대여 중복 차단
-- C-08: returned_at이 NULL인 미반납 대여는 도서당 최대 한 건입니다.
-- 반납된 과거 대여 행은 여러 건 저장할 수 있습니다.
-- ============================================================
CREATE UNIQUE INDEX uq_loans_nf_active_book
ON public.loans_nf (book_id)
WHERE returned_at IS NULL;

-- 생성 후 DBeaver에서 다음 구조를 확인합니다.
-- Schemas -> public -> Tables
-- public.library_records_raw, public.members_nf, public.books_nf, public.loans_nf
-- Indexes -> uq_loans_nf_active_book
