-- Chapter 06 호환 파일: 01_normalization_schema.sql과 같은 역할
-- 새 학습 흐름에서는 01_normalization_schema.sql 사용을 권장합니다.
-- 시작 상태: Chapter 06 실습 테이블이 없음
-- 완료 상태: 원시 테이블과 정규화 후 기본 테이블이 비어 있는 상태로 생성됨

SELECT current_database();
SELECT current_user;
SELECT current_schema();
SHOW search_path;

DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '생성 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF to_regnamespace('public') IS NULL THEN
        RAISE EXCEPTION '생성 중단: public 스키마가 존재하지 않습니다.';
    END IF;

    IF current_setting('transaction_read_only')::boolean THEN
        RAISE EXCEPTION '생성 중단: 현재 연결이 읽기 전용입니다.';
    END IF;

    IF to_regclass('public.library_records_raw') IS NOT NULL
       OR to_regclass('public.members_nf') IS NOT NULL
       OR to_regclass('public.books_nf') IS NOT NULL
       OR to_regclass('public.loans_nf') IS NOT NULL THEN
        RAISE EXCEPTION
            '생성 중단: Chapter 06 실습 테이블이 이미 있습니다. 상태를 확인하거나 reset_normalization.sql을 사용하세요.';
    END IF;
END
$$;

CREATE TABLE public.library_records_raw (
    loan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_name VARCHAR(50),
    member_email VARCHAR(100),
    book_title VARCHAR(200),
    author VARCHAR(100),
    borrowed_at DATE,
    due_at DATE,
    returned_at DATE
);

CREATE TABLE public.members_nf (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    email VARCHAR(100),
    joined_at DATE
);

CREATE TABLE public.books_nf (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200),
    author VARCHAR(100),
    published_year INTEGER,
    isbn VARCHAR(20)
);

CREATE TABLE public.loans_nf (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER,
    book_id INTEGER,
    borrowed_at DATE,
    due_at DATE,
    returned_at DATE
);

SELECT
    to_regclass('public.library_records_raw') AS raw_table,
    to_regclass('public.members_nf') AS members_table,
    to_regclass('public.books_nf') AS books_table,
    to_regclass('public.loans_nf') AS loans_table;
