-- Chapter 06. 정규화와 데이터 무결성으로 좋은 테이블 만들기
-- 목적: 정규화 전 원시 테이블과 정규화 후 테이블을 별도로 생성합니다.
-- 주의: 이 파일은 기존 테이블이나 데이터를 자동으로 삭제하지 않습니다.
-- Chapter 05 테이블과 충돌하지 않도록 _nf 접미사를 사용합니다.

-- ============================================================
-- 0. 현재 실행 위치 확인
-- 기대 결과: ai_database_book / public
-- ============================================================
SELECT current_database();
SELECT current_schema();

-- ============================================================
-- 1. 정규화 전 원시 테이블
-- 회원·도서·대여 사실이 한 행에 섞여 있습니다.
-- ============================================================
CREATE TABLE library_records_raw (
    loan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_name VARCHAR(50) NOT NULL,
    member_email VARCHAR(100) NOT NULL,
    book_title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    borrowed_at DATE NOT NULL,
    due_at DATE NOT NULL,
    returned_at DATE
);

-- ============================================================
-- 2. 정규화 후 회원 테이블
-- ============================================================
CREATE TABLE members_nf (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    joined_at DATE NOT NULL,
    CONSTRAINT chk_members_nf_name_not_blank
        CHECK (char_length(trim(name)) > 0)
);

-- ============================================================
-- 3. 정규화 후 도서 테이블
-- ============================================================
CREATE TABLE books_nf (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    published_year INTEGER,
    isbn VARCHAR(20) UNIQUE NOT NULL,
    CONSTRAINT chk_books_nf_title_not_blank
        CHECK (char_length(trim(title)) > 0),
    CONSTRAINT chk_books_nf_published_year
        CHECK (published_year IS NULL OR published_year >= 1000)
);

-- ============================================================
-- 4. 정규화 후 대여 사건 테이블
-- RESTRICT는 참조 중인 부모 행의 삭제를 막습니다.
-- ============================================================
CREATE TABLE loans_nf (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    book_id INTEGER NOT NULL,
    borrowed_at DATE NOT NULL,
    due_at DATE NOT NULL,
    returned_at DATE,

    CONSTRAINT fk_loans_nf_member
        FOREIGN KEY (member_id)
        REFERENCES members_nf(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_loans_nf_book
        FOREIGN KEY (book_id)
        REFERENCES books_nf(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_loans_nf_due_date
        CHECK (due_at >= borrowed_at),

    CONSTRAINT chk_loans_nf_returned_date
        CHECK (
            returned_at IS NULL
            OR returned_at >= borrowed_at
        )
);

-- 생성 후 DBeaver에서 다음 테이블을 확인합니다.
-- library_records_raw, members_nf, books_nf, loans_nf
