window.CH3_TITLE='Chapter 03 실습 강의';
window.CH3_SLIDES=[
{k:'CHAPTER 03 · PRACTICE',l:'실습 강의',h:`<h1>PostgreSQL과 DBeaver<br>실습 환경 만들기</h1><p class="lead">왼쪽에는 이 자료를, 오른쪽에는 설치 화면 또는 DBeaver 화면을 띄워놓고 한 단계씩 진행합니다.</p><div class="title-meta"><span class="pill">한 장 한 단계</span><span class="pill">입력값 확인</span><span class="pill">완료 기준 검증</span></div>`,s:`지금부터 3장 실습 강의를 진행하겠습니다. 화면 왼쪽에는 이 발표자료를 띄우고, 오른쪽에는 실제 설치 화면이나 디비버 화면을 띄워 놓는 방식으로 진행합니다. 각 장표는 한 단계만 다룹니다. 수행할 작업, 입력해야 할 값, 완료 확인 방법, 자주 생기는 오류를 차례대로 확인하겠습니다.`},
{k:'PRACTICE RULE',l:'진행 방식',h:`<h2>실습은 따라 하기보다<br>확인하면서 진행합니다</h2><div class="grid-2"><article class="card"><h3>자료 화면</h3><p>이번 단계의 목적, 입력값, 완료 기준을 확인합니다.</p></article><article class="card emphasis"><h3>프로그램 화면</h3><p>실제 설치·연결·SQL 실행 결과를 확인합니다.</p></article></div>`,s:`실습은 단순히 클릭 순서를 따라 하는 것보다 확인하면서 진행하는 것이 중요합니다. 발표자료 화면에서는 이번 단계의 목적과 입력값, 완료 기준을 확인합니다. 프로그램 화면에서는 실제 설치, 연결, 에스큐엘 실행 결과를 확인합니다. 화면이 버전에 따라 다를 수 있으므로 버튼 위치를 외우기보다 무엇을 설정하고 무엇을 확인하는지 이해하는 데 집중합니다.`},
{k:'CHECK BEFORE',l:'설치 전 확인',h:`<h2>설치 전 준비 사항을 확인합니다</h2><div class="table-wrap"><table><thead><tr><th>항목</th><th>확인 내용</th></tr></thead><tbody><tr><td>운영체제</td><td>Windows, macOS, Linux 중 현재 환경</td></tr><tr><td>설치 권한</td><td>프로그램과 서비스를 설치할 수 있는지</td></tr><tr><td>인터넷</td><td>설치 파일과 DBeaver Driver 다운로드 가능 여부</td></tr><tr><td>포트</td><td>기본값 5432 사용 가능 여부</td></tr><tr><td>비밀번호</td><td>안전하게 별도 기록</td></tr></tbody></table></div>`,s:`먼저 설치 전 준비 사항을 확인합니다. 운영체제가 윈도우인지, 맥오에스인지, 리눅스인지 확인합니다. 프로그램과 서비스를 설치할 권한이 있어야 합니다. 설치 파일과 디비버 드라이버를 내려받을 수 있도록 인터넷 연결이 필요합니다. 포스트그레스큐엘 기본 포트는 오천사백삼십이입니다. 그리고 설치 중 설정할 비밀번호는 반드시 안전하게 별도로 기록해야 합니다.`},
{k:'DOWNLOAD POSTGRESQL',l:'Step 01',h:`<h2>PostgreSQL 공식 다운로드 페이지로 이동합니다</h2><div class="step-box"><h3>수행 작업</h3><ul class="bullet-list"><li>브라우저에서 PostgreSQL 공식 다운로드 페이지를 엽니다.</li><li>현재 운영체제에 맞는 설치 경로를 선택합니다.</li><li>Windows 기준으로 안내되는 설치 프로그램을 내려받습니다.</li></ul></div><div class="codebox smallcode">https://www.postgresql.org/download/</div>`,s:`첫 번째 단계입니다. 브라우저에서 포스트그레스큐엘 공식 다운로드 페이지를 엽니다. 현재 운영체제에 맞는 설치 경로를 선택합니다. 윈도우 기준 수업에서는 안내되는 설치 프로그램을 내려받습니다. 여기서 중요한 것은 비공식 다운로드 링크를 사용하지 않는 것입니다. 설치 파일은 공식 페이지에서 연결되는 경로를 사용합니다.`},
{k:'RUN INSTALLER',l:'Step 02',h:`<h2>PostgreSQL 설치 프로그램을 실행합니다</h2><div class="grid-2"><article class="card"><h3>수행 작업</h3><p>설치 프로그램을 실행하고 기본 안내에 따라 진행합니다.</p></article><article class="card emphasis"><h3>확인 기준</h3><p>PostgreSQL Server와 명령행 도구가 설치 대상에 포함되어 있는지 확인합니다.</p></article></div>`,s:`두 번째 단계입니다. 내려받은 포스트그레스큐엘 설치 프로그램을 실행합니다. 설치 화면은 버전에 따라 조금 다를 수 있습니다. 기본 안내에 따라 진행하되, 포스트그레스큐엘 서버와 명령행 도구가 설치 대상에 포함되어 있는지 확인합니다. 명령행 도구는 필수 실습 대부분을 디비버로 진행하더라도 환경 확인과 확장 학습에 유용합니다.`},
{k:'SET PASSWORD',l:'Step 03',h:`<h2>postgres 사용자 비밀번호를 설정합니다</h2><div class="grid-2"><article class="card warn"><h3>주의</h3><p>비밀번호는 수업 자료, GitHub, 화면 캡처, AI 질문에 넣지 않습니다.</p></article><article class="card emphasis"><h3>완료 확인</h3><p>나중에 DBeaver 연결의 Password 항목에 같은 값을 입력합니다.</p></article></div>`,s:`세 번째 단계입니다. 설치 과정에서 포스트그레스 사용자 비밀번호를 설정합니다. 이 값은 나중에 디비버 연결에서 패스워드 항목에 입력합니다. 비밀번호를 잊어버리면 연결 단계에서 어려움이 생길 수 있으므로 안전한 비밀번호 관리 도구에 기록합니다. 단, 이 비밀번호를 에스큐엘 파일, 깃허브, 화면 캡처, 에이아이 질문에 넣지 않습니다.`},
{k:'PORT 5432',l:'Step 04',h:`<h2>Port는 기본적으로 5432를 사용합니다</h2><div class="quote">특별한 충돌이 없으면<br>PostgreSQL 기본 Port 5432를 사용합니다.</div><p class="body-text">이미 다른 PostgreSQL이 사용 중이면 포트 충돌이 발생할 수 있습니다.</p>`,s:`네 번째 단계입니다. 특별한 충돌이 없다면 포스트그레스큐엘 기본 포트인 오천사백삼십이를 사용합니다. 포트는 서버가 연결을 기다리는 통신 번호입니다. 이미 다른 포스트그레스큐엘 서버가 같은 포트를 사용하고 있다면 충돌이 생길 수 있습니다. 포트를 바꾸었다면 나중에 디비버 연결에서도 같은 포트 번호를 입력해야 합니다.`},
{k:'STACK BUILDER',l:'Step 05',h:`<h2>Stack Builder는 기본 실습에 필수는 아닙니다</h2><div class="grid-2"><article class="card"><h3>필수</h3><p>PostgreSQL Server 설치와 서비스 실행</p></article><article class="card"><h3>선택</h3><p>추가 패키지 설치 제안은 이번 장 기본 실습에서 생략 가능</p></article></div>`,s:`설치 마지막에 스택 빌더 실행을 제안할 수 있습니다. 스택 빌더는 추가 도구나 확장을 설치하는 데 사용할 수 있지만, 이번 장의 기본 실습에는 필수는 아닙니다. 포스트그레스큐엘 서버와 필요한 도구가 설치되고 서비스가 실행되면 기본 준비는 완료됩니다.`},
{k:'SERVICE STATUS',l:'Step 06',h:`<h2>PostgreSQL 서비스 실행 상태를 확인합니다</h2><div class="step-box"><h3>Windows 기준</h3><ul class="bullet-list"><li>서비스 앱을 엽니다.</li><li>PostgreSQL 관련 서비스를 찾습니다.</li><li>상태가 실행 중인지 확인합니다.</li></ul></div>`,s:`여섯 번째 단계입니다. 윈도우 기준으로 서비스 앱을 열고 포스트그레스큐엘 관련 서비스를 찾습니다. 상태가 실행 중인지 확인합니다. 서비스가 실행 중이어야 디비버가 포스트그레스큐엘 서버에 연결할 수 있습니다. 서비스 이름은 설치 버전에 따라 조금 다를 수 있습니다.`},
{k:'OPTIONAL PSQL',l:'선택 확인',h:`<h2>psql 버전 확인은 선택 사항입니다</h2><pre>psql --version</pre><p class="body-text">명령이 인식되지 않아도 서버 설치가 반드시 실패한 것은 아닙니다.</p>`,s:`피에스큐엘 버전 확인은 선택 사항입니다. 터미널에서 피에스큐엘 대시대시 버전을 실행할 수 있습니다. 하지만 명령이 인식되지 않는다고 해서 서버 설치가 반드시 실패한 것은 아닙니다. 실행 파일 경로가 환경변수에 등록되지 않았을 수 있습니다. 이 책의 기본 실습은 디비버 연결로 진행할 수 있습니다.`},
{k:'DOWNLOAD DBEAVER',l:'Step 07',h:`<h2>DBeaver Community를 설치합니다</h2><div class="step-box"><h3>수행 작업</h3><ul class="bullet-list"><li>DBeaver 공식 다운로드 페이지를 엽니다.</li><li>Community Edition을 선택합니다.</li><li>운영체제에 맞는 설치 파일을 내려받아 실행합니다.</li></ul></div><div class="codebox smallcode">https://dbeaver.io/download/</div>`,s:`일곱 번째 단계입니다. 디비버 공식 다운로드 페이지를 엽니다. 이 책의 실습은 디비버 커뮤니티 에디션으로 진행할 수 있습니다. 운영체제에 맞는 설치 파일을 내려받고 실행합니다. 설치가 끝나면 디비버를 시작합니다.`},
{k:'NEW CONNECTION',l:'Step 08',h:`<h2>DBeaver에서 새 Database 연결을 만듭니다</h2><div class="flow"><div class="flow-step">DBeaver 실행</div><div class="flow-arrow">→</div><div class="flow-step">새 연결</div><div class="flow-arrow">→</div><div class="flow-step current">PostgreSQL 선택</div><div class="flow-arrow">→</div><div class="flow-step">다음</div></div>`,s:`여덟 번째 단계입니다. 디비버를 실행하고 새 데이터베이스 연결을 만듭니다. 연결 목록에서 포스트그레스큐엘을 선택합니다. 화면 위치는 버전에 따라 다를 수 있지만, 핵심은 새 연결을 만들고 데이터베이스 종류로 포스트그레스큐엘을 선택하는 것입니다.`},
{k:'DRIVER DOWNLOAD',l:'Step 09',h:`<h2>JDBC Driver 다운로드 안내가 나오면 내려받습니다</h2><div class="grid-2"><article class="card"><h3>왜 필요한가</h3><p>DBeaver가 PostgreSQL과 통신하기 위해 Driver가 필요합니다.</p></article><article class="card emphasis"><h3>완료 확인</h3><p>Driver 다운로드 후 연결 설정 화면으로 이동합니다.</p></article></div>`,s:`아홉 번째 단계입니다. 디비버가 제이디비씨 드라이버 다운로드를 안내할 수 있습니다. 드라이버는 디비버가 포스트그레스큐엘과 통신하기 위해 필요한 구성 요소입니다. 안내가 나오면 내려받습니다. 회사나 학교 네트워크에서 다운로드가 막힌다면 인터넷 연결과 보안 정책을 확인해야 합니다.`},
{k:'CONNECTION INPUT',l:'Step 10',h:`<h2>로컬 Windows 기준 연결값을 입력합니다</h2><div class="table-wrap"><table><thead><tr><th>항목</th><th>입력값</th></tr></thead><tbody><tr><td>Host</td><td>localhost</td></tr><tr><td>Port</td><td>5432</td></tr><tr><td>Database</td><td>postgres</td></tr><tr><td>Username</td><td>postgres</td></tr><tr><td>Password</td><td>설치 시 설정한 값</td></tr></tbody></table></div>`,s:`열 번째 단계입니다. 로컬 윈도우 기준 연결값을 입력합니다. 호스트는 로컬호스트입니다. 포트는 오천사백삼십이입니다. 데이터베이스는 처음에는 포스트그레스를 사용합니다. 사용자 이름도 포스트그레스입니다. 비밀번호는 설치 과정에서 직접 설정한 값을 입력합니다. 포트를 바꾼 경우에는 여기서도 바꾼 값을 입력해야 합니다.`},
{k:'TEST CONNECTION',l:'Step 11',h:`<h2>Test Connection을 실행합니다</h2><div class="grid-2"><article class="card emphasis"><h3>성공 의미</h3><p>서버 도달, 사용자 인증, 지정 Database 접속이 가능함</p></article><article class="card warn"><h3>주의</h3><p>이후 SQL이 항상 올바른 DB에서 실행된다는 뜻은 아닙니다.</p></article></div>`,s:`열한 번째 단계입니다. 테스트 커넥션을 실행합니다. 성공했다면 서버에 도달했고, 사용자 인증이 되었고, 지정한 데이터베이스에 접속할 수 있다는 뜻입니다. 하지만 이것만으로 이후 모든 에스큐엘이 올바른 데이터베이스에서 실행된다고 보장되지는 않습니다. 에스큐엘 편집기를 열 때마다 현재 연결 대상을 확인해야 합니다.`},
{k:'SAVE CONNECTION',l:'Step 12',h:`<h2>연결을 저장하고 SQL 편집기를 엽니다</h2><div class="step-box"><h3>완료 확인</h3><ul class="bullet-list"><li>Database Navigator에 PostgreSQL 연결이 보입니다.</li><li>SQL Editor를 열 수 있습니다.</li><li>현재 연결 대상이 postgres Database인지 확인합니다.</li></ul></div>`,s:`열두 번째 단계입니다. 연결 테스트가 성공하면 연결을 저장합니다. 데이터베이스 내비게이터에 포스트그레스큐엘 연결이 보이는지 확인합니다. 에스큐엘 편집기를 열고 현재 연결 대상이 포스트그레스 데이터베이스인지 확인합니다. 작업용 데이터베이스를 만들기 전에는 기본 포스트그레스 데이터베이스에 연결되어 있을 수 있습니다.`},
{k:'CHECK DB EXISTS',l:'Step 13',h:`<h2>ai_database_book 존재 여부를 먼저 확인합니다</h2><pre>SELECT datname,
       pg_get_userbyid(datdba) AS database_owner
FROM pg_database
WHERE datname = 'ai_database_book';</pre>`,s:`열세 번째 단계입니다. 작업용 데이터베이스를 만들기 전에 에이아이 데이터베이스 북이 이미 있는지 확인합니다. 화면의 에스큐엘을 기본 포스트그레스 데이터베이스에 연결된 편집기에서 실행합니다. 결과가 영 행이면 아직 데이터베이스가 없습니다. 결과가 한 행이면 기존 데이터베이스가 있는 것이므로 소유자와 사용 목적을 확인합니다.`},
{k:'IF EXISTS',l:'분기 판단',h:`<h2>조회 결과에 따라 다음 작업을 선택합니다</h2><div class="grid-3"><article class="card"><h3>0행</h3><p>새로 생성 가능</p></article><article class="card"><h3>1행</h3><p>기존 DB 소유자와 상태 확인</p></article><article class="card warn"><h3>초기화 필요</h3><p>자동 DROP 안내 없이 백업과 삭제 대상을 별도로 확인</p></article></div>`,s:`조회 결과에 따라 다음 작업을 선택합니다. 영 행이면 데이터베이스가 없으므로 새로 만들 수 있습니다. 한 행이면 기존 데이터베이스가 있으므로 소유자와 상태를 확인합니다. 초기화가 필요한 경우에도 자동으로 드롭 데이터베이스를 안내하지 않습니다. 백업 여부와 삭제 대상을 먼저 확인해야 합니다.`},
{k:'CREATE DB',l:'Step 14',h:`<h2>필요한 경우 Database를 생성합니다</h2><pre>CREATE DATABASE ai_database_book;</pre><div class="step-box"><h3>실행 조건</h3><ul class="bullet-list"><li>CREATE DATABASE 권한이 있는 사용자</li><li>같은 이름의 Database가 없음</li><li>트랜잭션 블록 밖에서 실행</li></ul></div>`,s:`열네 번째 단계입니다. 필요한 경우 에이아이 데이터베이스 북 데이터베이스를 생성합니다. 실행할 문장은 크리에이트 데이터베이스 에이아이 데이터베이스 북입니다. 이 문장은 권한이 있는 사용자로 실행해야 하고, 같은 이름의 데이터베이스가 없어야 하며, 트랜잭션 블록 밖에서 실행해야 합니다. 디비버에서 해당 문장만 선택하거나 커서를 해당 문장에 둔 뒤 스테이트먼트 실행을 사용합니다.`},
{k:'CREATE ERRORS',l:'대표 오류',h:`<h2>Database 생성 대표 오류</h2><div class="table-wrap"><table><thead><tr><th>오류</th><th>확인할 내용</th></tr></thead><tbody><tr><td>cannot run inside a transaction block</td><td>Auto-commit, 실행 범위</td></tr><tr><td>permission denied to create database</td><td>접속 사용자와 CREATEDB 권한</td></tr><tr><td>already exists</td><td>기존 Database 존재 여부</td></tr></tbody></table></div>`,s:`데이터베이스 생성 중 자주 보는 오류입니다. 캔낫 런 인사이드 어 트랜잭션 블록은 자동 커밋과 실행 범위를 확인합니다. 퍼미션 디나이드 투 크리에이트 데이터베이스는 접속 사용자와 크리에이트디비 권한을 확인합니다. 얼레디 이그지스츠는 같은 이름의 데이터베이스가 이미 존재한다는 의미입니다.`},
{k:'RECONNECT DB',l:'Step 15',h:`<h2>ai_database_book으로 다시 연결합니다</h2><div class="flow"><div class="flow-step">연결 새로고침</div><div class="flow-arrow">→</div><div class="flow-step">연결 설정 수정 또는 새 연결</div><div class="flow-arrow">→</div><div class="flow-step current">Database = ai_database_book</div><div class="flow-arrow">→</div><div class="flow-step">새 SQL Editor</div></div>`,s:`열다섯 번째 단계입니다. 데이터베이스를 만들었다고 기존 편집기의 연결 대상이 자동으로 바뀌지는 않습니다. 연결을 새로고침하고, 연결 설정을 수정하거나 새 연결을 만들어 데이터베이스 항목을 에이아이 데이터베이스 북으로 지정합니다. 그런 다음 새 에스큐엘 편집기를 엽니다.`},
{k:'CURRENT DATABASE',l:'Step 16',h:`<h2>현재 Database를 확인합니다</h2><pre>SELECT current_database();</pre><div class="quote">결과가 ai_database_book이어야 합니다.</div>`,s:`열여섯 번째 단계입니다. 새 에스큐엘 편집기에서 셀렉트 커런트 데이터베이스를 실행합니다. 결과가 에이아이 데이터베이스 북이어야 합니다. 만약 포스트그레스가 나오면 아직 기본 데이터베이스에 연결된 상태입니다. 연결 대상을 다시 확인하고 에이아이 데이터베이스 북으로 연결해야 합니다.`},
{k:'SCHEMA PATH',l:'Step 17',h:`<h2>현재 Schema와 search_path를 확인합니다</h2><pre>SELECT current_schema();
SHOW search_path;</pre><p class="body-text">current_schema가 항상 public이어야 하는 것은 아닙니다.</p>`,s:`열일곱 번째 단계입니다. 현재 스키마와 검색 경로를 확인합니다. 셀렉트 커런트 스키마와 쇼 서치 패스를 실행합니다. 커런트 스키마가 항상 퍼블릭이어야 하는 것은 아닙니다. 검색 경로에 따라 다를 수 있습니다. 중요한 것은 퍼블릭 스키마가 존재하고 사용할 수 있는지, 검색 경로 결과를 설명할 수 있는지입니다.`},
{k:'NAVIGATOR PATH',l:'Step 18',h:`<h2>DBeaver Navigator에서 위치를 확인합니다</h2><div class="hierarchy"><div>PostgreSQL 연결</div><div>ai_database_book</div><div>Schemas</div><div>public</div><div>Tables</div></div><p class="body-text">Chapter 04 전에는 Tables 아래가 비어 있어도 정상입니다.</p>`,s:`열여덟 번째 단계입니다. 디비버 데이터베이스 내비게이터에서 구조를 확인합니다. 포스트그레스큐엘 연결 아래에 에이아이 데이터베이스 북이 있고, 그 안에 스키마, 퍼블릭, 테이블스가 보이는지 확인합니다. 4장에서 아직 테이블을 만들기 전이라면 테이블스 아래가 비어 있어도 정상입니다.`},
{k:'READ ONLY TIMEZONE',l:'Step 19',h:`<h2>읽기 전용 상태와 TimeZone을 확인합니다</h2><pre>SHOW transaction_read_only;
SHOW TimeZone;</pre><div class="quote">transaction_read_only = off이면<br>읽기·쓰기 가능한 연결입니다.</div>`,s:`열아홉 번째 단계입니다. 읽기 전용 상태와 시간대를 확인합니다. 쇼 트랜잭션 리드 온리를 실행합니다. 로컬 필수 경로에서는 결과가 오프여야 읽기와 쓰기가 가능한 연결입니다. 쇼 타임존도 실행해 현재 시간대 값을 확인합니다. 시간대 값은 환경별로 다를 수 있으므로 확인해 기록하면 됩니다.`},
{k:'SETUP CHECK RUN',l:'Step 20',h:`<h2>setup_check.sql을 실행합니다</h2><div class="step-box"><h3>수행 작업</h3><ul class="bullet-list"><li>code/chapter03/setup_check.sql 파일을 엽니다.</li><li>ai_database_book 연결에서 실행합니다.</li><li>결과를 확인하고 필요한 항목을 기록합니다.</li></ul></div>`,s:`스무 번째 단계입니다. 코드 폴더의 챕터 쓰리, 셋업 체크 에스큐엘 파일을 엽니다. 반드시 에이아이 데이터베이스 북 연결에서 실행합니다. 이 파일은 버전, 현재 데이터베이스, 현재 스키마, 검색 경로, 사용자, 읽기 전용 상태, 시간대, 계산 결과를 보여 줍니다. 결과를 확인하고 필요한 항목을 기록합니다.`},
{k:'CHECK RESULT',l:'Step 21',h:`<h2>setup_check 결과에서 필수 항목을 확인합니다</h2><div class="table-wrap"><table><thead><tr><th>항목</th><th>기준</th></tr></thead><tbody><tr><td>현재 DB</td><td>ai_database_book</td></tr><tr><td>public</td><td>존재하고 사용 가능</td></tr><tr><td>읽기 전용</td><td>off</td></tr><tr><td>계산</td><td>1 + 1 = 2</td></tr></tbody></table></div>`,s:`셋업 체크 결과에서 필수 항목을 확인합니다. 현재 데이터베이스는 에이아이 데이터베이스 북이어야 합니다. 퍼블릭 스키마가 존재하고 사용 가능해야 합니다. 읽기 전용 상태는 오프여야 합니다. 계산 결과는 일이 더하기 일이 이가 되어야 합니다. 시간대와 현재 사용자는 환경별로 다를 수 있으므로 값 자체를 확인하고 기록합니다.`},
{k:'VALIDATE RUN',l:'Step 22',h:`<h2>setup_validate_local.sql을 실행합니다</h2><div class="step-box"><h3>통과 메시지</h3><div class="codebox smallcode">Chapter 03 local environment validation passed</div></div><p class="body-text">하나라도 다르면 예외가 발생하므로 연결과 권한을 다시 확인합니다.</p>`,s:`스물두 번째 단계입니다. 셋업 밸리데이트 로컬 에스큐엘을 실행합니다. 모두 통과하면 챕터 쓰리 로컬 인바이런먼트 밸리데이션 패스드 메시지가 출력됩니다. 하나라도 다르면 예외가 발생합니다. 이 경우 현재 데이터베이스, 퍼블릭 스키마, 권한, 읽기 전용 상태를 다시 확인합니다.`},
{k:'SAVE RECORD',l:'Step 23',h:`<h2>환경 확인 기록을 남깁니다</h2><pre>## PostgreSQL 실습 환경 확인 기록
- 운영체제:
- PostgreSQL 버전:
- DBeaver 버전:
- 연결 테스트 결과:
- 현재 데이터베이스:
- current_schema:
- search_path:
- transaction_read_only:
- TimeZone:
- setup_validate_local 결과:</pre>`,s:`스물세 번째 단계입니다. 환경 확인 기록을 남깁니다. 운영체제, 포스트그레스큐엘 버전, 디비버 버전, 연결 테스트 결과, 현재 데이터베이스, 현재 스키마, 검색 경로, 읽기 전용 상태, 시간대, 자동 검증 결과를 기록합니다. 이 기록은 나중에 오류가 생겼을 때 환경을 재현하고 비교하는 근거가 됩니다.`},
{k:'SECRET CHECK',l:'Step 24',h:`<h2>비밀정보가 파일과 캡처에 들어가지 않았는지 확인합니다</h2><ul class="bullet-list"><li>Password 없음</li><li>전체 접속 URL 없음</li><li>API Key·Access Token 없음</li><li>실제 password file 경로와 내용 없음</li></ul>`,s:`스물네 번째 단계입니다. 비밀정보가 파일과 캡처에 들어가지 않았는지 확인합니다. 비밀번호가 없어야 합니다. 전체 접속 유알엘이 없어야 합니다. 에이피아이 키와 액세스 토큰이 없어야 합니다. 실제 패스워드 파일 경로와 내용도 공개 자료에 넣지 않습니다. 수업 중 화면 공유를 할 때도 연결 정보가 과도하게 노출되지 않도록 주의합니다.`},
{k:'ERROR CONNECTION REFUSED',l:'오류 해결 1',h:`<h2>Connection refused가 나오면</h2><div class="grid-3"><article class="card"><h3>서비스</h3><p>PostgreSQL 서비스 실행 여부</p></article><article class="card"><h3>Host</h3><p>localhost 또는 서버 주소</p></article><article class="card emphasis"><h3>Port</h3><p>5432 또는 실제 설정 포트</p></article></div>`,s:`커넥션 리퓨즈드가 나오면 먼저 포스트그레스큐엘 서비스가 실행 중인지 확인합니다. 다음으로 호스트가 로컬호스트인지, 실제 서버 주소가 맞는지 확인합니다. 포트가 오천사백삼십이인지, 설치할 때 다른 포트를 사용했는지 확인합니다. 방화벽이나 회사 학교 네트워크 정책도 원인이 될 수 있습니다.`},
{k:'ERROR PASSWORD',l:'오류 해결 2',h:`<h2>Password authentication failed가 나오면</h2><div class="grid-2"><article class="card"><h3>Username</h3><p>postgres 또는 실제 생성한 사용자 확인</p></article><article class="card emphasis"><h3>Password</h3><p>설치 중 설정한 비밀번호 확인</p></article></div>`,s:`패스워드 오센티케이션 페일드가 나오면 사용자 이름과 비밀번호를 확인합니다. 윈도우 일반 설치에서는 초기 사용자 이름이 포스트그레스인 경우가 많습니다. 비밀번호는 설치 중 직접 설정한 값입니다. 비밀번호를 모르는 경우에는 단순히 여러 번 시도하기보다 비밀번호 재설정 절차를 확인해야 합니다.`},
{k:'ERROR DB DOES NOT EXIST',l:'오류 해결 3',h:`<h2>Database does not exist가 나오면</h2><ul class="bullet-list"><li>Database 이름 철자를 확인합니다.</li><li>ai_database_book을 실제로 생성했는지 확인합니다.</li><li>현재 연결 설정의 Database 항목을 확인합니다.</li><li>연결 새로고침 또는 새 연결 생성을 진행합니다.</li></ul>`,s:`데이터베이스 더즈 낫 이그지스트가 나오면 데이터베이스 이름 철자를 확인합니다. 에이아이 데이터베이스 북을 실제로 생성했는지 확인합니다. 현재 연결 설정의 데이터베이스 항목도 확인합니다. 데이터베이스를 생성한 뒤 연결을 새로고침하지 않았거나 새 연결을 만들지 않은 경우도 많습니다.`},
{k:'ERROR TRANSACTION',l:'오류 해결 4',h:`<h2>CREATE DATABASE cannot run inside a transaction block</h2><div class="grid-2"><article class="card"><h3>원인</h3><p>트랜잭션 블록 안에서 CREATE DATABASE 실행</p></article><article class="card emphasis"><h3>확인</h3><p>Auto-commit, 실행 범위, 선택한 SQL 문장</p></article></div>`,s:`크리에이트 데이터베이스 캔낫 런 인사이드 어 트랜잭션 블록 오류는 크리에이트 데이터베이스를 트랜잭션 블록 안에서 실행했을 때 발생합니다. 디비버의 오토 커밋 상태와 실행 범위를 확인합니다. 전체 스크립트 실행 대신 해당 문장만 스테이트먼트 실행하는 방식으로 다시 확인할 수 있습니다.`},
{k:'ERROR TABLES INVISIBLE',l:'오류 해결 5',h:`<h2>DB나 Table이 보이지 않으면</h2><pre>SELECT current_database();
SELECT current_schema();
SHOW search_path;</pre><p class="body-text">Database, Schema, 필터, 새로고침을 차례대로 확인합니다.</p>`,s:`데이터베이스나 테이블이 보이지 않으면 먼저 현재 데이터베이스, 현재 스키마, 검색 경로를 확인합니다. 그다음 디비버 내비게이터의 데이터베이스, 스키마, 필터, 새로고침 상태를 확인합니다. 4장 전에는 아직 테이블을 만들지 않았기 때문에 테이블스 아래가 비어 있어도 정상입니다.`},
{k:'AI QUESTION',l:'오류 질문 템플릿',h:`<h2>AI에게 질문할 때 사용할 형식</h2><div class="prompt-box">운영체제:
PostgreSQL 사용 방식: 로컬 / 관리형
PostgreSQL 버전:
DBeaver 버전:
연결값: Host·Port·Database·Username만 일부 마스킹
실행한 작업:
발생한 오류 메시지:
이미 확인한 내용:
비밀번호와 전체 URL은 제외했습니다.</div>`,s:`에이아이에게 질문할 때는 이 형식을 사용합니다. 운영체제, 포스트그레스큐엘 사용 방식, 버전, 디비버 버전, 연결값 일부, 실행한 작업, 오류 메시지, 이미 확인한 내용을 제공합니다. 비밀번호와 전체 유알엘은 제외했다고 명시합니다. 이렇게 질문하면 에이아이가 원인을 더 정확히 분류할 수 있습니다.`},
{k:'FINAL CHECKLIST',l:'완료 점검',h:`<h2>실습 완료 체크리스트</h2><div class="table-wrap"><table><thead><tr><th>점검 항목</th><th>완료 기준</th></tr></thead><tbody><tr><td>PostgreSQL 서버</td><td>로컬 서비스 실행 중</td></tr><tr><td>DBeaver 연결</td><td>Test Connection 성공</td></tr><tr><td>작업 DB</td><td>ai_database_book 연결</td></tr><tr><td>환경 SQL</td><td>setup_check 실행</td></tr><tr><td>자동 검증</td><td>setup_validate_local 통과</td></tr><tr><td>비밀정보</td><td>공개 파일·캡처에 없음</td></tr></tbody></table></div>`,s:`마지막으로 실습 완료 체크리스트를 확인합니다. 포스트그레스큐엘 서버가 실행 중이어야 합니다. 디비버 테스트 커넥션이 성공해야 합니다. 작업 데이터베이스인 에이아이 데이터베이스 북에 연결되어야 합니다. 셋업 체크를 실행하고, 셋업 밸리데이트 로컬이 통과해야 합니다. 그리고 비밀정보가 공개 파일이나 화면 캡처에 없어야 합니다.`},
{k:'NEXT CHAPTER',l:'다음 장 연결',h:`<h2>다음 장에서는 실제 Table과 SQL을 시작합니다</h2><div class="flow"><div class="flow-step done">3장<br>환경 준비</div><div class="flow-arrow">→</div><div class="flow-step current">4장<br>Table 생성</div><div class="flow-arrow">→</div><div class="flow-step">INSERT<br>SELECT</div><div class="flow-arrow">→</div><div class="flow-step">검증과 수정</div></div>`,s:`다음 장에서는 실제 테이블과 에스큐엘을 시작합니다. 3장에서 준비한 에이아이 데이터베이스 북 환경을 사용해 퍼블릭 스키마 안에 테이블을 만들고, 인서트와 셀렉트를 실행합니다. 오늘의 연결과 환경 검증이 안정적으로 끝나야 다음 장에서 오류를 줄이고 학습에 집중할 수 있습니다.`}
];