window.CH3_TITLE='Chapter 03 이론 강의';
window.CH3_SLIDES=[
{k:'CHAPTER 03 · THEORY',l:'이론 강의',h:`<h1>PostgreSQL과 DBeaver로<br>실습 환경 만들기</h1><p class="lead">3장은 이론과 실습을 분리합니다. 먼저 왜 이 환경이 필요한지, 어떤 기준으로 완료를 판단할지 확인합니다.</p><div class="title-meta"><span class="pill">PostgreSQL</span><span class="pill">DBeaver</span><span class="pill">연결 구조</span><span class="pill">검증 기준</span></div>`,s:`안녕하세요. 3장부터는 이론 강의와 실습 강의를 분리해서 진행하겠습니다. 이론 강의에서는 포스트그레스큐엘과 디비버가 각각 어떤 역할을 하는지, 로컬 데이터베이스와 관리형 데이터베이스가 어떻게 다른지, 그리고 실습이 완료되었다고 판단하는 기준이 무엇인지 먼저 정리합니다. 실습 강의에서는 이 자료와 실제 프로그램 화면을 함께 띄워 놓고 설치와 연결, 환경 검증을 단계별로 진행하겠습니다.`},
{k:'WHERE WE ARE',l:'전체 과정 속 위치',h:`<h2>3장은 실제 SQL 실습을 위한<br>환경 준비 단계입니다</h2><div class="flow"><div class="flow-step done">1장<br>왜 DB를 배우는가</div><div class="flow-arrow">→</div><div class="flow-step done">2장<br>기본 용어</div><div class="flow-arrow">→</div><div class="flow-step current">3장<br>설치·연결·검증</div><div class="flow-arrow">→</div><div class="flow-step">4장<br>Table·SQL 시작</div></div>`,s:`전체 과정에서 3장의 위치를 보겠습니다. 1장에서는 에이아이 시대에 왜 데이터베이스를 배워야 하는지 살펴보았습니다. 2장에서는 데이터, 디비엠에스, 스키마, 테이블, 행, 열 같은 기본 용어를 정리했습니다. 3장인 이번 장에서는 그 개념을 실제 환경으로 연결합니다. 포스트그레스큐엘을 설치하고, 디비버로 연결하고, 다음 장부터 사용할 아이 데이터베이스 북 데이터베이스가 올바르게 준비되었는지 확인합니다.`},
{k:'TWO-PART CLASS',l:'진행 방식',h:`<h2>이론 후 실습으로 진행합니다</h2><div class="grid-2"><article class="card"><h3>1부 · 이론</h3><p>역할, 연결값, 로컬/관리형 차이, 완료 기준을 먼저 설명합니다.</p></article><article class="card emphasis"><h3>2부 · 실습</h3><p>발표자료와 프로그램 화면을 함께 띄워 설치·연결·검증을 진행합니다.</p></article></div>`,s:`이번 장은 두 부분으로 나누어 진행합니다. 1부 이론에서는 개념과 실습 목적을 먼저 설명합니다. 2부 실습에서는 발표자료를 한쪽에 두고, 다른 쪽에는 포스트그레스큐엘 설치 화면이나 디비버 화면을 띄워서 함께 따라갑니다. 실습 자료는 화면 캡처를 많이 넣기보다 입력값, 수행 작업, 완료 확인, 자주 발생하는 오류를 중심으로 구성합니다.`},
{k:'CHAPTER GOAL',l:'학습 목표',h:`<h2>이번 장의 목표는<br>설치 자체가 아니라 재현 가능한 연결입니다</h2><ul class="bullet-list"><li>PostgreSQL 서버와 DBeaver의 역할을 구분한다.</li><li>DBeaver에서 PostgreSQL 연결을 만든다.</li><li>작업용 Database인 ai_database_book으로 연결한다.</li><li>current_database, current_schema, search_path를 확인한다.</li><li>setup_check와 setup_validate_local을 구분한다.</li></ul>`,s:`이번 장의 목표는 설치 파일을 한 번 실행하는 것이 아닙니다. 더 중요한 목표는 재현 가능한 연결입니다. 포스트그레스큐엘 서버와 디비버의 역할을 구분하고, 디비버에서 포스트그레스큐엘 연결을 만들고, 작업용 데이터베이스인 에이아이 데이터베이스 북으로 연결해야 합니다. 또한 현재 데이터베이스, 현재 스키마, 검색 경로를 확인하고, 환경 정보를 조회하는 파일과 자동으로 통과 여부를 판정하는 파일을 구분해야 합니다.`},
{k:'NOT THIS CHAPTER',l:'범위 제한',h:`<h2>3장에서는 Table 생성과 CRUD를<br>아직 진행하지 않습니다</h2><div class="grid-3"><article class="card"><span class="number">4장</span><h3>Table·CRUD</h3><p>테이블 생성과 기본 SQL</p></article><article class="card"><span class="number">6장</span><h3>무결성 오류</h3><p>PK, FK, NOT NULL 검증</p></article><article class="card"><span class="number">9장</span><h3>Transaction</h3><p>Commit, Rollback, 동시성</p></article></div>`,s:`범위를 분명히 하겠습니다. 3장에서는 테이블 생성과 데이터 입력, 크러드 실습을 아직 진행하지 않습니다. 4장에서 테이블 생성과 기본 에스큐엘을 시작하고, 6장에서 무결성 오류를 다루며, 9장에서 트랜잭션을 배웁니다. 3장의 역할은 이후 실습을 안전하게 수행할 수 있도록 연결과 환경 확인을 마치는 것입니다.`},
{k:'PRACTICE PATH',l:'필수 실습 경로',h:`<h2>로컬 필수 실습 경로</h2><div class="flow"><div class="flow-step">PostgreSQL<br>서버 실행</div><div class="flow-arrow">→</div><div class="flow-step">DBeaver<br>연결</div><div class="flow-arrow">→</div><div class="flow-step">ai_database_book<br>확인·생성</div><div class="flow-arrow">→</div><div class="flow-step">환경 SQL<br>검증</div></div>`,s:`이 책의 필수 실습 경로는 로컬 포스트그레스큐엘을 기준으로 합니다. 먼저 로컬 포스트그레스큐엘 서버를 실행합니다. 다음으로 디비버에서 연결을 만듭니다. 그다음 에이아이 데이터베이스 북 데이터베이스가 있는지 확인하고, 없다면 생성합니다. 마지막으로 환경 확인 에스큐엘을 실행해 현재 데이터베이스, 스키마, 검색 경로, 읽기 전용 상태와 시간대를 확인합니다.`},
{k:'ENVIRONMENT',l:'기본 환경',h:`<h2>기본 실습 환경은<br>로컬 PostgreSQL + DBeaver + SQL 파일입니다</h2><div class="grid-3"><article class="card"><h3>PostgreSQL</h3><p>데이터 저장과 SQL 실행을 담당하는 DBMS</p></article><article class="card"><h3>DBeaver</h3><p>SQL 작성과 결과 확인을 돕는 Client</p></article><article class="card emphasis"><h3>SQL 파일</h3><p>실행 과정과 검증 기준을 재실행 가능하게 보관</p></article></div>`,s:`기본 실습 환경은 세 가지로 구성됩니다. 첫째, 포스트그레스큐엘입니다. 데이터를 저장하고 에스큐엘을 실행하는 디비엠에스입니다. 둘째, 디비버입니다. 포스트그레스큐엘에 연결해서 에스큐엘을 작성하고 결과를 확인하는 클라이언트 도구입니다. 셋째, 에스큐엘 파일입니다. 실행 과정과 검증 기준을 다시 실행할 수 있도록 저장하는 파일입니다.`},
{k:'VERSION BASELINE',l:'출판 기준 환경',h:`<h2>버전은 기준일과 호환 범위를<br>구분해서 안내합니다</h2><div class="table-wrap"><table><thead><tr><th>항목</th><th>기준</th></tr></thead><tbody><tr><td>기준 버전 확인일</td><td>2026-07-24</td></tr><tr><td>운영체제 기준</td><td>Windows 11</td></tr><tr><td>PostgreSQL 기준</td><td>18.4</td></tr><tr><td>DBeaver Community 기준</td><td>26.1.3</td></tr><tr><td>SQL 호환 목표</td><td>PostgreSQL 15 이상</td></tr></tbody></table></div>`,s:`출판 기준 환경은 화면과 같습니다. 기준 버전 확인일은 이천이십육년 칠월 이십사일입니다. 운영체제 기준은 윈도우 일레븐입니다. 포스트그레스큐엘 기준 버전은 십팔 점 사이고, 디비버 커뮤니티 기준 버전은 이십육 점 일 점 삼입니다. 다만 이 책의 에스큐엘 호환 목표는 포스트그레스큐엘 십오 이상입니다. 실제 버전에 따라 화면 배치와 메뉴 이름은 조금 달라질 수 있습니다.`},
{k:'ROLE REVIEW',l:'역할 복습',h:`<h2>PostgreSQL과 DBeaver는<br>같은 종류의 프로그램이 아닙니다</h2><div class="table-wrap"><table><thead><tr><th>구분</th><th>PostgreSQL</th><th>DBeaver</th></tr></thead><tbody><tr><td>종류</td><td>DBMS·서버</td><td>Client 도구</td></tr><tr><td>역할</td><td>데이터 저장·SQL 처리</td><td>SQL 작성·결과 표시</td></tr><tr><td>데이터 보관</td><td>실제 데이터 보관</td><td>직접 보관하지 않음</td></tr></tbody></table></div>`,s:`포스트그레스큐엘과 디비버는 같은 종류의 프로그램이 아닙니다. 포스트그레스큐엘은 디비엠에스이자 데이터베이스 서버입니다. 실제 데이터를 저장하고 에스큐엘을 처리하며 권한과 규칙을 적용합니다. 디비버는 클라이언트 도구입니다. 사용자가 에스큐엘을 작성하고 결과를 화면에서 확인하도록 도와줍니다. 디비버만 설치했다고 데이터베이스 서버가 준비되는 것은 아닙니다.`},
{k:'CLIENT SERVER',l:'Client–Server',h:`<h2>SQL 실행은 Client와 Server가<br>함께 처리합니다</h2><div class="flow"><div class="flow-step">사용자</div><div class="flow-arrow">→</div><div class="flow-step">DBeaver<br>SQL 작성</div><div class="flow-arrow">→</div><div class="flow-step">PostgreSQL<br>SQL 실행</div><div class="flow-arrow">→</div><div class="flow-step">결과·오류<br>표시</div></div>`,s:`에스큐엘 실행 흐름을 보겠습니다. 사용자는 디비버에서 에스큐엘을 작성합니다. 디비버는 그 명령을 포스트그레스큐엘에 전달합니다. 포스트그레스큐엘은 실제로 에스큐엘을 실행합니다. 그리고 결과나 오류를 디비버로 돌려줍니다. 그래서 오류가 발생했을 때는 디비버 문제인지, 포스트그레스큐엘 서버 문제인지, 연결값 문제인지, 에스큐엘 문제인지 구분해야 합니다.`},
{k:'LOCAL VS MANAGED',l:'로컬과 관리형',h:`<h2>필수 경로는 로컬 PostgreSQL입니다</h2><div class="grid-2"><article class="card emphasis"><h3>로컬 PostgreSQL</h3><p>내 컴퓨터에 설치해 서버 구조와 연결을 직접 확인합니다.</p></article><article class="card"><h3>관리형 PostgreSQL</h3><p>클라우드 서비스가 운영 일부를 담당하지만 연결·권한·비밀정보 관리는 여전히 필요합니다.</p></article></div>`,s:`이번 책의 필수 경로는 로컬 포스트그레스큐엘입니다. 자신의 컴퓨터에 설치해 서버 구조와 연결을 직접 확인합니다. 관리형 포스트그레스큐엘은 설치 부담이 적고 여러 기기에서 접근할 수 있지만, 인터넷, 계정, 에스에스엘, 비용, 접속 정보 관리가 필요합니다. Supabase 같은 관리형 서비스는 선택 읽기로 다룹니다.`},
{k:'SUPABASE NOTE',l:'Supabase 선택 읽기',h:`<h2>Supabase는 선택 읽기이며<br>로컬 필수 경로를 대체하지 않습니다</h2><div class="quote">Supabase도 PostgreSQL을 제공하지만<br>프로젝트 구조와 연결 방식은 로컬 실습과 다릅니다.</div>`,s:`Supabase는 선택 읽기입니다. Supabase 프로젝트에도 실제 포스트그레스큐엘 데이터베이스가 제공됩니다. 하지만 Auth, Storage, Realtime 같은 서비스가 연결되어 있고, 기본 데이터베이스 이름이나 연결 방식이 로컬 필수 경로와 다릅니다. 따라서 Supabase 프로젝트를 4장 이후의 필수 실습 환경으로 그대로 대체하지 않습니다.`},
{k:'CONNECTION VALUES',l:'연결값의 의미',h:`<h2>DBeaver 연결값은<br>각각 의미가 다릅니다</h2><div class="table-wrap"><table><thead><tr><th>항목</th><th>일반 값</th><th>의미</th></tr></thead><tbody><tr><td>Host</td><td>localhost</td><td>서버가 실행되는 컴퓨터</td></tr><tr><td>Port</td><td>5432</td><td>연결을 기다리는 통신 번호</td></tr><tr><td>Database</td><td>postgres</td><td>처음 접속할 데이터베이스</td></tr><tr><td>Username</td><td>postgres</td><td>초기 구성 사용자</td></tr></tbody></table></div>`,s:`디비버 연결값은 각각 의미가 있습니다. 호스트는 포스트그레스큐엘 서버가 실행되는 컴퓨터입니다. 포트는 서버가 연결을 기다리는 통신 번호이며 일반적으로 오천사백삼십이입니다. 데이터베이스는 처음 접속할 데이터베이스입니다. 사용자 이름은 인증에 사용하는 계정입니다. 비밀번호는 설치 과정에서 설정한 값을 사용합니다.`},
{k:'POSTGRES NAME',l:'postgres 주의',h:`<h2>postgres는 사용자와 Database 이름에<br>둘 다 나타날 수 있습니다</h2><div class="grid-2"><article class="card"><h3>postgres 사용자</h3><p>PostgreSQL에 로그인하는 관리자 역할</p></article><article class="card emphasis"><h3>postgres Database</h3><p>설치 시 일반적으로 생성되는 기본 Database</p></article></div>`,s:`포스트그레스라는 이름은 사용자와 데이터베이스 이름에 모두 나타날 수 있습니다. 포스트그레스 사용자는 포스트그레스큐엘에 로그인하는 관리자 역할입니다. 포스트그레스 데이터베이스는 설치 시 일반적으로 생성되는 기본 데이터베이스입니다. 이름이 같다고 해서 둘을 같은 것으로 보면 안 됩니다. 하나는 로그인 역할이고 다른 하나는 데이터베이스입니다.`},
{k:'SECURITY FIRST',l:'보안 주의',h:`<h2>비밀번호와 접속 URL은<br>공개 자료에 넣지 않습니다</h2><ul class="bullet-list"><li>Password, 전체 접속 URL, API Key, Access Token은 공개하지 않습니다.</li><li>SQL 파일, README, GitHub, 화면 캡처에 포함하지 않습니다.</li><li>AI 질문에는 민감한 연결 정보를 마스킹합니다.</li></ul>`,s:`보안 주의입니다. 비밀번호, 전체 접속 유알엘, 에이피아이 키, 액세스 토큰은 공개 자료에 넣지 않습니다. 에스큐엘 파일, 리드미, 깃허브, 화면 캡처에도 포함하지 않습니다. 에이아이에게 오류를 질문할 때도 호스트나 사용자 이름은 필요한 부분만 남기고 마스킹합니다. 이미 노출된 비밀정보는 파일에서 지우는 것만으로 충분하지 않고 즉시 변경하거나 폐기해야 합니다.`},
{k:'DATABASE CREATION',l:'작업 DB 생성 기준',h:`<h2>ai_database_book은<br>먼저 존재 여부를 확인한 뒤 생성합니다</h2><pre>SELECT datname,
       pg_get_userbyid(datdba) AS database_owner
FROM pg_database
WHERE datname = 'ai_database_book';</pre>`,s:`작업용 데이터베이스 이름은 에이아이 데이터베이스 북입니다. 새로 만들기 전에 먼저 존재 여부를 확인해야 합니다. 화면의 에스큐엘은 피지 데이터베이스에서 데이터베이스 이름과 소유자를 조회합니다. 결과가 영 행이면 아직 데이터베이스가 없는 것입니다. 한 행이 나오면 기존 데이터베이스의 소유자와 사용 목적을 확인합니다.`},
{k:'CREATE DATABASE',l:'CREATE DATABASE',h:`<h2>필요한 경우에만<br>Database를 생성합니다</h2><pre>CREATE DATABASE ai_database_book;</pre><div class="quote">CREATE DATABASE는 트랜잭션 밖에서 실행합니다.</div>`,s:`데이터베이스가 없다면 필요한 경우에만 생성합니다. 화면의 문장은 크리에이트 데이터베이스 에이아이 데이터베이스 북입니다. 이 문장은 데이터베이스를 새로 만드는 명령입니다. 중요한 점은 크리에이트 데이터베이스가 트랜잭션 블록 안에서 실행될 수 없다는 것입니다. 그래서 디비버에서 자동 커밋 상태와 실행 범위를 확인해야 합니다.`},
{k:'RECONNECT',l:'새 DB로 다시 연결',h:`<h2>Database를 만들었다고<br>연결 대상이 자동으로 바뀌지는 않습니다</h2><div class="flow"><div class="flow-step">CREATE DATABASE</div><div class="flow-arrow">→</div><div class="flow-step">연결 새로고침</div><div class="flow-arrow">→</div><div class="flow-step">ai_database_book 연결</div><div class="flow-arrow">→</div><div class="flow-step current">current_database 확인</div></div>`,s:`크리에이트 데이터베이스가 성공해도 기존 에스큐엘 편집기의 연결 대상이 자동으로 바뀌지는 않습니다. 데이터베이스를 만든 뒤에는 연결을 새로고침하고, 에이아이 데이터베이스 북 전용 연결을 만들거나 연결 설정을 수정해야 합니다. 그다음 새 에스큐엘 편집기를 열고 커런트 데이터베이스 결과가 에이아이 데이터베이스 북인지 확인합니다.`},
{k:'CHECK CURRENT',l:'현재 환경 확인',h:`<h2>현재 Database·Schema·search_path를<br>SQL로 확인합니다</h2><pre>SELECT current_database();
SELECT current_schema();
SHOW search_path;</pre>`,s:`현재 환경은 눈으로 추측하지 않고 에스큐엘로 확인합니다. 커런트 데이터베이스는 현재 연결된 데이터베이스를 보여 줍니다. 커런트 스키마는 검색 경로에서 실제로 사용할 수 있는 첫 번째 스키마를 보여 줍니다. 쇼 서치 패스는 객체 이름을 생략했을 때 어떤 순서로 스키마를 찾는지 보여 줍니다. 이 세 가지는 앞으로 테이블이 보이지 않거나 결과가 이상할 때 가장 먼저 확인할 정보입니다.`},
{k:'SCHEMA CAVEAT',l:'current_schema 주의',h:`<h2>current_schema가 항상 public인 것은 아닙니다</h2><div class="quote">완료 기준은 current_schema = public이 아니라<br>public 스키마 존재와 USAGE 권한 확인입니다.</div>`,s:`주의할 점이 있습니다. 커런트 스키마가 항상 퍼블릭인 것은 아닙니다. 검색 경로에 사용자 이름과 같은 스키마가 있고 실제로 존재하면 커런트 스키마가 퍼블릭이 아닐 수 있습니다. 그래서 완료 기준을 단순히 커런트 스키마 이퀄 퍼블릭으로 두지 않습니다. 퍼블릭 스키마가 존재하고, 현재 사용자가 퍼블릭 스키마에 유세지 권한을 가지고 있는지 확인하는 것이 더 정확합니다.`},
{k:'EXECUTION RANGE',l:'실행 범위',h:`<h2>DBeaver에서는 실행 범위를<br>구분해야 합니다</h2><div class="grid-3"><article class="card"><h3>Statement</h3><p>커서가 있는 현재 SQL 문장</p></article><article class="card"><h3>선택 영역</h3><p>선택한 SQL만 실행</p></article><article class="card emphasis"><h3>Script</h3><p>편집기 또는 파일의 여러 문장 실행</p></article></div>`,s:`디비버에서는 실행 범위를 구분해야 합니다. 스테이트먼트 실행은 커서가 있는 현재 에스큐엘 문장을 실행합니다. 선택 영역 실행은 선택한 에스큐엘만 실행합니다. 스크립트 실행은 편집기 또는 파일의 여러 문장을 실행합니다. 변경 에스큐엘이 포함된 경우에는 어떤 범위를 실행하는지 특히 조심해야 합니다.`},
{k:'AUTO COMMIT',l:'Auto-commit',h:`<h2>Auto-commit과 Manual commit은<br>변경 확정 방식이 다릅니다</h2><div class="grid-2"><article class="card emphasis"><h3>Auto-commit</h3><p>변경 문장이 실행되면 즉시 확정될 수 있습니다.</p></article><article class="card"><h3>Manual commit</h3><p>명시적으로 Commit 또는 Rollback해야 할 수 있습니다.</p></article></div>`,s:`오토 커밋과 매뉴얼 커밋은 변경을 확정하는 방식이 다릅니다. 오토 커밋에서는 변경 문장이 실행되면 즉시 확정될 수 있습니다. 매뉴얼 커밋에서는 명시적으로 커밋하거나 롤백해야 할 수 있습니다. 9장에서 트랜잭션을 자세히 배우기 전까지는 변경 에스큐엘을 한 문장 또는 확인한 선택 영역 단위로 실행하는 습관을 들이는 것이 좋습니다.`},
{k:'SETUP CHECK',l:'setup_check.sql',h:`<h2>setup_check.sql은<br>환경 정보를 사람이 읽기 위한 조회 파일입니다</h2><pre>SELECT version();
SELECT current_database();
SELECT current_schema();
SHOW search_path;
SHOW transaction_read_only;
SHOW TimeZone;
SELECT 1 + 1 AS result;</pre>`,s:`셋업 체크 에스큐엘은 환경 정보를 사람이 읽고 기록하기 위한 조회 파일입니다. 버전, 현재 데이터베이스, 현재 스키마, 검색 경로, 읽기 전용 상태, 시간대, 간단한 계산 결과를 확인합니다. 이 파일은 테이블이나 데이터를 생성하거나 수정하지 않으므로 여러 번 실행할 수 있습니다.`},
{k:'VALIDATION FILE',l:'setup_validate_local.sql',h:`<h2>setup_validate_local.sql은<br>로컬 필수 경로를 통과·실패로 판정합니다</h2><ul class="bullet-list"><li>PostgreSQL 15 이상</li><li>current_database() = ai_database_book</li><li>public 스키마 존재와 USAGE 권한</li><li>transaction_read_only = off</li><li>계산 결과 = 2</li></ul>`,s:`셋업 밸리데이트 로컬 에스큐엘은 로컬 필수 경로를 통과 또는 실패로 판정합니다. 포스트그레스큐엘 십오 이상인지, 현재 데이터베이스가 에이아이 데이터베이스 북인지, 퍼블릭 스키마가 존재하고 유세지 권한이 있는지, 트랜잭션 읽기 전용 상태가 오프인지, 계산 결과가 이인지 검사합니다. 통과하면 챕터 쓰리 로컬 인바이런먼트 밸리데이션 패스드 메시지를 출력합니다.`},
{k:'ERROR TYPES',l:'오류 유형',h:`<h2>오류는 유형별로 분류해서 해결합니다</h2><div class="table-wrap"><table><thead><tr><th>증상</th><th>우선 확인</th></tr></thead><tbody><tr><td>Connection refused</td><td>서비스, Host, Port</td></tr><tr><td>Password authentication failed</td><td>Username, Password</td></tr><tr><td>Database does not exist</td><td>Database 이름과 생성 여부</td></tr><tr><td>Cannot run inside a transaction block</td><td>Auto-commit, 실행 범위</td></tr></tbody></table></div>`,s:`오류는 유형별로 분류해서 해결합니다. 커넥션 리퓨즈드는 서버 서비스, 호스트, 포트 문제를 먼저 확인합니다. 패스워드 오센티케이션 페일드는 사용자 이름과 비밀번호를 확인합니다. 데이터베이스 더즈 낫 이그지스트는 데이터베이스 이름과 생성 여부를 확인합니다. 캔낫 런 인사이드 어 트랜잭션 블록은 자동 커밋 상태와 실행 범위를 확인해야 합니다.`},
{k:'AI ERROR QUESTION',l:'AI 질문 작성',h:`<h2>AI에게 질문할 때는<br>재현 가능한 정보만 제공합니다</h2><div class="prompt-box">운영체제:
PostgreSQL 사용 방식: 로컬 / 관리형
PostgreSQL 버전:
DBeaver 버전:
실행한 작업:
발생한 오류 메시지:
이미 확인한 내용:
비밀번호와 전체 접속 URL은 제외했습니다.</div>`,s:`에이아이에게 오류를 질문할 때는 재현 가능한 정보를 제공해야 합니다. 운영체제, 포스트그레스큐엘 사용 방식, 버전, 디비버 버전, 실행한 작업, 발생한 오류 메시지, 이미 확인한 내용을 정리합니다. 비밀번호와 전체 접속 유알엘은 제외해야 합니다. 에이아이 답변은 그대로 실행하지 말고, 현재 운영체제와 설치 방식에 맞는지, 삭제나 초기화 명령이 포함되어 있는지 확인해야 합니다.`},
{k:'DONE CRITERIA',l:'완료 기준',h:`<h2>3장의 완료 기준</h2><div class="table-wrap"><table><thead><tr><th>항목</th><th>완료 기준</th></tr></thead><tbody><tr><td>PostgreSQL</td><td>로컬 서비스 실행</td></tr><tr><td>DBeaver</td><td>Test Connection 성공</td></tr><tr><td>작업 DB</td><td>ai_database_book 연결</td></tr><tr><td>읽기·쓰기</td><td>transaction_read_only = off</td></tr><tr><td>자동 검증</td><td>setup_validate_local.sql 통과</td></tr></tbody></table></div>`,s:`3장의 완료 기준입니다. 포스트그레스큐엘 로컬 서비스가 실행 중이어야 합니다. 디비버에서 테스트 커넥션이 성공해야 합니다. 작업용 데이터베이스인 에이아이 데이터베이스 북에 연결되어야 합니다. 트랜잭션 읽기 전용 상태가 오프여야 합니다. 마지막으로 셋업 밸리데이트 로컬 에스큐엘이 통과해야 합니다. 이 조건을 만족해야 다음 장에서 테이블과 에스큐엘 실습을 안정적으로 진행할 수 있습니다.`},
{k:'THEORY WRAP-UP',l:'이론 정리',h:`<h2>이론 강의 핵심 정리</h2><div class="quote">3장의 핵심은 설치 완료가 아니라<br>올바른 연결과 재현 가능한 환경 검증입니다.</div><p class="body-text">이제 실습 자료와 실제 프로그램 화면을 함께 보며 단계별로 진행합니다.</p>`,s:`이론 강의를 정리하겠습니다. 3장의 핵심은 설치 완료가 아니라 올바른 연결과 재현 가능한 환경 검증입니다. 포스트그레스큐엘은 서버이고, 디비버는 클라이언트입니다. 로컬 필수 경로는 에이아이 데이터베이스 북 데이터베이스에 연결하고, 현재 데이터베이스와 스키마, 검색 경로, 읽기 전용 상태를 확인하는 것입니다. 이제 실습 자료와 실제 프로그램 화면을 함께 보며 단계별로 진행하겠습니다.`}
];