-- Chapter 12. nosql_lab 스키마 생성
-- 목적: 기존 프로젝트를 보호하면서 JSONB·Key-Value 개념과 저장소 선택 기준을 실습합니다.
-- 주의: 기존 스키마나 테이블을 자동으로 삭제하지 않습니다.

SELECT
    current_user AS current_user_name,
    current_database() AS current_database_name,
    current_schema() AS current_schema_name;

-- 앞 장의 주요 스키마가 유지되는지 객체 존재 여부만 확인합니다.
SELECT
    to_regnamespace('course_project') AS course_project_schema,
    to_regnamespace('transaction_lab') AS transaction_lab_schema,
    to_regnamespace('performance_lab') AS performance_lab_schema,
    to_regnamespace('security_lab') AS security_lab_schema;

CREATE SCHEMA nosql_lab;

CREATE TABLE nosql_lab.course_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    metadata JSONB NOT NULL,
    document_version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_nosql_course_documents_title
        CHECK (char_length(trim(title)) > 0),

    CONSTRAINT chk_nosql_course_documents_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object'),

    CONSTRAINT chk_nosql_course_documents_version
        CHECK (document_version >= 1)
);

CREATE TABLE nosql_lab.key_value_cache_examples (
    cache_key TEXT PRIMARY KEY,
    cache_value JSONB NOT NULL,
    source_name TEXT NOT NULL,
    expired_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_nosql_cache_key
        CHECK (char_length(trim(cache_key)) > 0),

    CONSTRAINT chk_nosql_cache_value_object
        CHECK (jsonb_typeof(cache_value) = 'object'),

    CONSTRAINT chk_nosql_cache_source
        CHECK (char_length(trim(source_name)) > 0)
);

CREATE TABLE nosql_lab.storage_choice_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_name TEXT NOT NULL UNIQUE,
    system_role TEXT NOT NULL,
    primary_query TEXT NOT NULL,
    candidate_storage TEXT NOT NULL,
    source_of_truth TEXT NOT NULL,
    consistency_requirement TEXT NOT NULL,
    synchronization_strategy TEXT NOT NULL,
    reason TEXT NOT NULL,

    CONSTRAINT chk_nosql_storage_role
        CHECK (system_role IN (
            'source_of_truth',
            'ephemeral_state',
            'derived_cache',
            'flexible_metadata',
            'event_log',
            'relationship_index'
        )),

    CONSTRAINT chk_nosql_storage_case_name
        CHECK (char_length(trim(case_name)) > 0),

    CONSTRAINT chk_nosql_storage_primary_query
        CHECK (char_length(trim(primary_query)) > 0),

    CONSTRAINT chk_nosql_storage_candidate
        CHECK (char_length(trim(candidate_storage)) > 0),

    CONSTRAINT chk_nosql_storage_source
        CHECK (char_length(trim(source_of_truth)) > 0)
);

SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'nosql_lab'
ORDER BY table_name;
