-- Chapter 12. nosql_lab 스키마 생성
-- 목적: 기존 프로젝트를 보호하면서 JSONB·Key-Value 개념과 저장소 선택 기준을 실습합니다.
-- 주의: 기존 스키마나 테이블을 자동으로 삭제하지 않습니다.

SELECT current_user AS current_user_name;
SELECT current_database();
SELECT current_schema();
SHOW search_path;

-- ============================================================
-- 0. 실행 전 보호 조건
-- ============================================================
DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '실행 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF to_regclass('course_project.students') IS NULL
       OR to_regclass('course_project.instructors') IS NULL
       OR to_regclass('course_project.courses') IS NULL
       OR to_regclass('course_project.enrollments') IS NULL THEN
        RAISE EXCEPTION
            '실행 중단: Chapter 07 course_project 핵심 테이블이 준비되지 않았습니다.';
    END IF;

    IF (SELECT COUNT(*) FROM course_project.students) <> 3
       OR (SELECT COUNT(*) FROM course_project.instructors) <> 2
       OR (SELECT COUNT(*) FROM course_project.courses) <> 3
       OR (SELECT COUNT(*) FROM course_project.enrollments) <> 5 THEN
        RAISE EXCEPTION
            '실행 중단: Chapter 07 기준 상태는 students 3, instructors 2, courses 3, enrollments 5여야 합니다.';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_namespace
        WHERE nspname = 'nosql_lab'
    ) THEN
        RAISE EXCEPTION
            '실행 중단: nosql_lab 스키마가 이미 존재합니다. 보존 여부를 확인한 뒤 reset_nosql_lab.sql 사용을 검토하세요.';
    END IF;
END
$$;

-- ============================================================
-- 1. 스키마와 테이블 생성
-- 중간 실패 시 일부 객체만 남지 않도록 하나의 트랜잭션으로 처리합니다.
-- ============================================================
BEGIN;

CREATE SCHEMA nosql_lab;

-- 안정된 핵심 속성은 일반 컬럼으로 두고,
-- 가변 태그·옵션·강사 표시용 스냅샷만 JSONB에 둡니다.
-- source_course_id는 Chapter 07 원본과 대조하기 위한 논리적 참조입니다.
-- nosql_lab 단독 이동성을 유지하기 위해 물리적 FK는 만들지 않습니다.
CREATE TABLE nosql_lab.course_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_course_id INTEGER NOT NULL,
    course_code TEXT NOT NULL,
    title TEXT NOT NULL,
    level TEXT NOT NULL,
    metadata JSONB NOT NULL,
    document_version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_nosql_course_documents_source_course
        UNIQUE (source_course_id),

    CONSTRAINT uq_nosql_course_documents_code
        UNIQUE (course_code),

    CONSTRAINT chk_nosql_course_documents_code_not_blank
        CHECK (char_length(trim(course_code)) > 0),

    CONSTRAINT chk_nosql_course_documents_title_not_blank
        CHECK (char_length(trim(title)) > 0),

    CONSTRAINT chk_nosql_course_documents_level
        CHECK (level IN ('basic', 'intermediate', 'advanced')),

    CONSTRAINT chk_nosql_course_documents_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object'),

    CONSTRAINT chk_nosql_course_documents_version
        CHECK (document_version >= 1),

    CONSTRAINT chk_nosql_course_documents_updated_at
        CHECK (updated_at >= created_at)
);

-- 이 테이블은 Key-Value 제품의 개념 시뮬레이션입니다.
-- 값은 편의를 위해 JSONB로 저장하지만 객체·배열·문자열·숫자 등 JSONB 값 전체를 허용합니다.
-- expired_at이 NULL이면 만료 정책이 없는 키로 해석합니다.
CREATE TABLE nosql_lab.key_value_cache_examples (
    cache_key TEXT PRIMARY KEY,
    cache_value JSONB NOT NULL,
    source_name TEXT NOT NULL,
    expired_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_nosql_cache_key_not_blank
        CHECK (char_length(trim(cache_key)) > 0),

    CONSTRAINT chk_nosql_cache_source_not_blank
        CHECK (char_length(trim(source_name)) > 0)
);

-- 저장소 후보는 정답표가 아니라 근거·PoC·복구 계획이 포함된 의사결정 기록입니다.
CREATE TABLE nosql_lab.storage_choice_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_name TEXT NOT NULL,
    system_role TEXT NOT NULL,
    primary_query TEXT NOT NULL,
    candidate_storage TEXT NOT NULL,
    source_of_truth TEXT NOT NULL,
    consistency_requirement TEXT NOT NULL,
    synchronization_strategy TEXT NOT NULL,
    recovery_strategy TEXT NOT NULL,
    poc_success_criteria TEXT NOT NULL,
    decision_status TEXT NOT NULL,
    reason TEXT NOT NULL,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_nosql_storage_choice_case
        UNIQUE (case_name),

    CONSTRAINT chk_nosql_storage_role
        CHECK (system_role IN (
            'source_of_truth',
            'ephemeral_state',
            'derived_cache',
            'flexible_metadata',
            'event_log',
            'relationship_index'
        )),

    CONSTRAINT chk_nosql_storage_decision_status
        CHECK (decision_status IN (
            'candidate',
            'poc_planned',
            'hold',
            'adopted',
            'rejected'
        )),

    CONSTRAINT chk_nosql_storage_case_name_not_blank
        CHECK (char_length(trim(case_name)) > 0),

    CONSTRAINT chk_nosql_storage_primary_query_not_blank
        CHECK (char_length(trim(primary_query)) > 0),

    CONSTRAINT chk_nosql_storage_candidate_not_blank
        CHECK (char_length(trim(candidate_storage)) > 0),

    CONSTRAINT chk_nosql_storage_source_not_blank
        CHECK (char_length(trim(source_of_truth)) > 0),

    CONSTRAINT chk_nosql_storage_consistency_not_blank
        CHECK (char_length(trim(consistency_requirement)) > 0),

    CONSTRAINT chk_nosql_storage_sync_not_blank
        CHECK (char_length(trim(synchronization_strategy)) > 0),

    CONSTRAINT chk_nosql_storage_recovery_not_blank
        CHECK (char_length(trim(recovery_strategy)) > 0),

    CONSTRAINT chk_nosql_storage_poc_not_blank
        CHECK (char_length(trim(poc_success_criteria)) > 0),

    CONSTRAINT chk_nosql_storage_reason_not_blank
        CHECK (char_length(trim(reason)) > 0)
);

COMMIT;

-- ============================================================
-- 2. 생성 결과 확인
-- ============================================================
SELECT
    table_schema,
    table_name
FROM information_schema.tables
WHERE table_schema = 'nosql_lab'
ORDER BY table_name;

SELECT
    conrelid::regclass::text AS table_name,
    conname AS constraint_name,
    contype AS constraint_type
FROM pg_constraint
WHERE connamespace = 'nosql_lab'::regnamespace
ORDER BY conrelid::regclass::text, conname;
