from pathlib import Path


def read(path):
    return Path(path).read_text(encoding='utf-8')


def write(path, text):
    Path(path).write_text(text, encoding='utf-8')


def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 match, found {count}')
    return text.replace(old, new, 1)


# -----------------------------------------------------------------------------
# Book body
# -----------------------------------------------------------------------------
path = 'book/chapter13/chapter13.md'
text = read(path)
text = replace_once(
    text,
    'ChatGPT와 Codex의 지원 기능과 사용 환경은 바뀔 수 있으며 서로 겹치는 기능도 있습니다. 이 장의 구분은 제품의 절대 기능 경계가 아니라 데이터베이스 작업을 안전하게 진행하기 위한 권장 흐름입니다. 현재 공식 안내의 큰 흐름은 Chat은 빠른 질의·대화, Work는 장시간 다단계 산출물, Codex는 코드 작성·디버깅·테스트·명령 실행·저장소 작업에 초점을 둔다는 것입니다. 실제 사용 시 최신 공식 안내를 다시 확인합니다.',
    'ChatGPT와 Codex의 지원 기능과 사용 환경은 바뀔 수 있으며 서로 겹치는 기능도 있습니다. 이 장의 구분은 제품의 절대 기능 경계가 아니라 데이터베이스 작업을 안전하게 진행하기 위한 권장 흐름입니다. **2026년 8월 출판 검수 시점의 OpenAI 공식 안내**는 Chat을 빠른 대화형 지원, Work를 더 길고 여러 단계인 작업과 완성된 산출물, Codex를 소프트웨어 개발·기술 작업에 맞춘 환경으로 설명합니다. 제공 범위는 플랜·워크스페이스·사용 화면에 따라 달라질 수 있으므로 실제 사용 시 최신 공식 안내를 다시 확인합니다.',
    'chapter product guidance',
)
text = replace_once(
    text,
    '| ChatGPT | 요구사항 구조화, 설계 대안·검토 질문·프롬프트 초안 | 미확정 업무 정책 확정 |\n| Codex | 저장소 탐색, 대상 파일 수정, SQL·테스트 작성, diff·실행 지원 | 변경 자동 승인 |\n| 사람 | 요구사항 확인, 데이터·권한·운영 범위 결정, 실행 결과와 diff 검토 | 최종 책임을 AI에 이전 |',
    '| ChatGPT Chat | 요구사항 구조화, 설계 대안·검토 질문·프롬프트 초안 | 미확정 업무 정책 확정 |\n| ChatGPT Work | 긴 다단계 검토, 자료 분석, 검토 보고서 같은 완성 산출물 작성 지원 | 실행 증거 없이 변경 승인 |\n| Codex | 저장소 탐색, 대상 파일 수정, SQL·테스트 작성, diff·실행 지원 | 변경 자동 승인 |\n| 사람 | 요구사항 확인, 데이터·권한·운영 범위 결정, 실행 결과와 diff 검토 | 최종 책임을 AI에 이전 |',
    'chapter role table',
)
text = text.replace('`payments` | 현재 결제 상태와 외부 비민감 참조값 |', '`payments` | 현재 결제 상태와 가상 외부 참조값 |')
text = replace_once(
    text,
    'payment_reference는 외부 결제 시스템의 비민감 참조값으로 문서화',
    'payment_reference는 실습용 가상 외부 참조값이며 실제 보호 수준은 조직 정책으로 판단',
    'chapter payment reference evidence',
)
text = replace_once(
    text,
    '생성 파일은 자동 DROP을 실행하지 않습니다. 처음부터 다시 시작할 때만 보호된 `reset_ai_review_lab.sql`을 사용합니다.',
    '생성 파일은 자동 DROP을 실행하지 않습니다. `01_ai_review_lab_schema.sql`은 Chapter 07·08 canonical 데이터뿐 아니라 **Chapter 07 명명 제약조건 15개, NOT NULL 열 20개, 현재 역할의 `ai_database_book` CREATE 권한**을 DDL 전에 확인합니다. Chapter 11의 `security_lab`이나 Chapter 12의 `nosql_lab` 존재 자체를 시작 조건으로 요구하지는 않습니다. 처음부터 다시 시작할 때만 보호된 `reset_ai_review_lab.sql`을 사용합니다.',
    'chapter execution guard paragraph',
)
text = replace_once(
    text,
    '명시적 ID 입력은 IDENTITY 내부 시퀀스의 다음 값을 자동으로 이동시키지 않습니다. Seed 파일은 `ALTER TABLE ... RESTART WITH`를 실행합니다.\n\n오류·경계값 테스트는 명시적 테스트 ID를 사용하고 하위 트랜잭션에서 취소합니다. 자동 ID를 사용한 트랜잭션이 취소되면 번호 공백이 생길 수 있으며, 번호 연속성은 정합성 기준이 아닙니다.',
    '이 장의 ID 컬럼은 `GENERATED BY DEFAULT AS IDENTITY`를 사용합니다. INSERT에서 ID를 직접 지정하면 그 값이 우선 사용되므로 내부 시퀀스가 그 값에 맞춰 자동으로 이동하지 않습니다. 그래서 Seed 파일은 `ALTER TABLE ... RESTART WITH`로 다음 자동값을 명시적으로 조정합니다.\n\n반대로 자동 ID를 요청해 시퀀스 값이 발급된 뒤 트랜잭션이 취소되어도 그 값은 일반적으로 재사용을 위해 회수되지 않습니다. 오류·경계값 테스트는 기준 상태를 보호하기 위해 명시적 테스트 ID와 하위 트랜잭션을 사용하며, 자동 번호의 공백 자체는 정합성 오류로 보지 않습니다.',
    'chapter identity explanation',
)
text = replace_once(
    text,
    'Chapter 07 원본 신청 5행 유지\n기준 행 수 3/3/2/3/4/4',
    'Chapter 07 원본 신청 5행 유지\nChapter 07 명명 제약조건 15개 / NOT NULL 열 20개 유지\n기준 행 수 3/3/2/3/4/4',
    'chapter final gate source structure',
)
write(path, text)

# -----------------------------------------------------------------------------
# Outline
# -----------------------------------------------------------------------------
path = 'book/chapter13/chapter13_outline.md'
text = read(path)
text = replace_once(
    text,
    '생성·Seed·초기화가 잘못된 DB에서 차단되는가?\n명시적 ID 뒤 IDENTITY 다음 값이 조정되었는가?',
    '생성·Seed·초기화가 잘못된 DB에서 차단되는가?\nChapter 07 명명 제약조건 15개와 NOT NULL 열 20개가 유지되는가?\n현재 역할에 ai_database_book CREATE 권한이 있는지 DDL 전에 확인하는가?\n명시적 ID 뒤 IDENTITY 다음 값이 조정되었는가?',
    'outline key questions',
)
text = replace_once(
    text,
    '| FK | 4 | - | - |',
    '| FK | 4 | - | - |\n| Chapter 07 명명 제약조건 | 15 | - | - |\n| Chapter 07 NOT NULL 열 | 20 | - | - |',
    'outline base data',
)
text = replace_once(
    text,
    '- AI 결과 검토\n- 요구사항·결정·미확정 정책',
    '- AI 결과 검토\n- ChatGPT Chat·Work·Codex 역할과 제공 범위 변화 가능성\n- 요구사항·결정·미확정 정책',
    'outline core concepts',
)
text = replace_once(
    text,
    '- 생성·Seed·초기화 파일은 현재 DB와 상태를 실제 검사한다.\n- 구조·Seed는 트랜잭션으로 처리한다.',
    '- 생성·Seed·초기화 파일은 현재 DB와 상태를 실제 검사한다.\n- 생성 전 Chapter 07 명명 제약조건 15개 / NOT NULL 열 20개와 현재 역할의 DB CREATE 권한을 확인한다.\n- 구조·Seed는 트랜잭션으로 처리한다.',
    'outline safety',
)
write(path, text)

# -----------------------------------------------------------------------------
# Reader workbook
# -----------------------------------------------------------------------------
path = 'book/chapter13/chapter13_activity.md'
text = read(path)
text = replace_once(
    text,
    '| Chapter 07 신청 수 | 5 |  |\n| 생성 전 `ai_review_lab` 미존재 | true |  |',
    '| Chapter 07 신청 수 | 5 |  |\n| Chapter 07 명명 제약조건 | 15개 |  |\n| Chapter 07 NOT NULL 열 | 20개 |  |\n| 현재 역할 DB CREATE 권한 | 있음 |  |\n| 생성 전 `ai_review_lab` 미존재 | true |  |',
    'activity preflight rows',
)
text = text.replace('### 예상 실패 22개', '### 예상 실패 24개')
text = replace_once(
    text,
    '| 결제실패·금액 0·시각 NULL | 성공 후 자동 취소 |  |\n\n| 최종 집계 | 기대 | 실제 |',
    '| 결제실패·금액 0·시각 NULL | 성공 후 자동 취소 |  |\n| 대소문자 다른 학생 이메일 | 현재 정확 문자열 정책에서 성공 후 자동 취소 |  |\n\n| 최종 집계 | 기대 | 실제 |',
    'activity sixth success',
)
text = text.replace('| total | 27 |  |', '| total | 30 |  |')
text = replace_once(
    text,
    '| Chapter 07 신청 | 5 |  |  |\n| 기준 행 수 | 3/3/2/3/4/4 |  |  |',
    '| Chapter 07 신청 | 5 |  |  |\n| Chapter 07 구조 계약 | 명명 제약조건 15 / NOT NULL 20 |  |  |\n| 기준 행 수 | 3/3/2/3/4/4 |  |  |',
    'activity final structure row',
)
write(path, text)

# -----------------------------------------------------------------------------
# Main SQL preflight
# -----------------------------------------------------------------------------
path = 'code/chapter13/01_ai_review_lab_schema.sql'
text = read(path)
text = replace_once(
    text,
    'DECLARE\n    recorded_amount_type_ok BOOLEAN;\nBEGIN',
    'DECLARE\n    recorded_amount_type_ok BOOLEAN;\n    v_project_named_constraint_count BIGINT;\n    v_project_not_null_count BIGINT;\nBEGIN',
    '01 declarations',
)
anchor = """    IF EXISTS (\n        SELECT 1\n        FROM course_project.enrollments\n        WHERE status IN ('신청', '수강중')\n        GROUP BY student_id, course_id\n        HAVING COUNT(*) > 1\n    ) THEN\n        RAISE EXCEPTION\n            '실행 중단: Chapter 07·08 원본에 활성 신청 중복이 있습니다.';\n    END IF;\n\n"""
addition = anchor + """    IF NOT has_database_privilege(current_user, current_database(), 'CREATE') THEN\n        RAISE EXCEPTION\n            '실행 중단: 현재 역할 %에는 데이터베이스 %의 CREATE 권한이 없습니다.',\n            current_user, current_database();\n    END IF;\n\n    SELECT COUNT(*)\n    INTO v_project_named_constraint_count\n    FROM pg_constraint\n    WHERE conrelid IN (\n        'course_project.students'::regclass,\n        'course_project.instructors'::regclass,\n        'course_project.courses'::regclass,\n        'course_project.enrollments'::regclass\n    )\n      AND conname IN (\n        'uq_course_students_email',\n        'chk_course_students_name_not_blank',\n        'chk_course_students_email_not_blank',\n        'uq_course_instructors_email',\n        'chk_course_instructors_name_not_blank',\n        'chk_course_instructors_email_not_blank',\n        'chk_course_instructors_specialty_not_blank',\n        'fk_course_courses_instructor',\n        'chk_course_courses_title_not_blank',\n        'chk_course_courses_level',\n        'chk_course_courses_price',\n        'fk_course_enrollments_student',\n        'fk_course_enrollments_course',\n        'chk_course_enrollments_status',\n        'chk_course_enrollments_recorded_amount'\n      );\n\n    SELECT COUNT(*)\n    INTO v_project_not_null_count\n    FROM information_schema.columns\n    WHERE table_schema = 'course_project'\n      AND table_name IN ('students', 'instructors', 'courses', 'enrollments')\n      AND is_nullable = 'NO';\n\n    IF v_project_named_constraint_count <> 15\n       OR v_project_not_null_count <> 20 THEN\n        RAISE EXCEPTION\n            '실행 중단: Chapter 07 구조 기준과 다릅니다. named_constraints=%, not_null_columns=%',\n            v_project_named_constraint_count, v_project_not_null_count;\n    END IF;\n\n"""
text = replace_once(text, anchor, addition, '01 preflight guards')
write(path, text)

# -----------------------------------------------------------------------------
# Final SQL gate: re-check upstream structure, type and active policy
# -----------------------------------------------------------------------------
path = 'code/chapter13/08_ai_review_lab_validation.sql'
text = read(path)
text = replace_once(
    text,
    '    temp_failure_count INTEGER;\n    temp_success_count INTEGER;\nBEGIN',
    '    temp_failure_count INTEGER;\n    temp_success_count INTEGER;\n    v_project_named_constraint_count BIGINT;\n    v_project_not_null_count BIGINT;\nBEGIN',
    '08 declarations',
)
anchor = """    IF NOT EXISTS (\n        SELECT 1 FROM course_project.enrollments\n        WHERE id = 1001 AND status = '완료' AND recorded_amount = 100000\n    ) OR NOT EXISTS (\n        SELECT 1 FROM course_project.enrollments\n        WHERE id = 1004 AND status = '취소' AND recorded_amount = 150000\n    ) OR NOT EXISTS (\n        SELECT 1 FROM course_project.enrollments\n        WHERE id = 1005 AND status = '신청' AND recorded_amount = 120000\n    ) THEN\n        RAISE EXCEPTION\n            '최종 검증 실패: Chapter 07·08 핵심 신청 1001/1004/1005가 변경되었습니다.';\n    END IF;\n\n"""
addition = anchor + """    IF NOT EXISTS (\n        SELECT 1\n        FROM information_schema.columns\n        WHERE table_schema = 'course_project'\n          AND table_name = 'enrollments'\n          AND column_name = 'recorded_amount'\n          AND data_type = 'numeric'\n          AND numeric_precision = 12\n          AND numeric_scale = 0\n    ) OR EXISTS (\n        SELECT 1\n        FROM information_schema.columns\n        WHERE table_schema = 'course_project'\n          AND table_name = 'enrollments'\n          AND column_name = 'paid_amount'\n    ) THEN\n        RAISE EXCEPTION\n            '최종 검증 실패: Chapter 07·08 recorded_amount 구조가 기준과 다릅니다.';\n    END IF;\n\n    IF to_regclass('course_project.uq_course_enrollments_active') IS NULL\n       OR EXISTS (\n            SELECT 1\n            FROM course_project.enrollments\n            WHERE status IN ('신청', '수강중')\n            GROUP BY student_id, course_id\n            HAVING COUNT(*) > 1\n       ) THEN\n        RAISE EXCEPTION\n            '최종 검증 실패: Chapter 07 활성 신청 정책이 기준과 다릅니다.';\n    END IF;\n\n    SELECT COUNT(*)\n    INTO v_project_named_constraint_count\n    FROM pg_constraint\n    WHERE conrelid IN (\n        'course_project.students'::regclass,\n        'course_project.instructors'::regclass,\n        'course_project.courses'::regclass,\n        'course_project.enrollments'::regclass\n    )\n      AND conname IN (\n        'uq_course_students_email',\n        'chk_course_students_name_not_blank',\n        'chk_course_students_email_not_blank',\n        'uq_course_instructors_email',\n        'chk_course_instructors_name_not_blank',\n        'chk_course_instructors_email_not_blank',\n        'chk_course_instructors_specialty_not_blank',\n        'fk_course_courses_instructor',\n        'chk_course_courses_title_not_blank',\n        'chk_course_courses_level',\n        'chk_course_courses_price',\n        'fk_course_enrollments_student',\n        'fk_course_enrollments_course',\n        'chk_course_enrollments_status',\n        'chk_course_enrollments_recorded_amount'\n      );\n\n    SELECT COUNT(*)\n    INTO v_project_not_null_count\n    FROM information_schema.columns\n    WHERE table_schema = 'course_project'\n      AND table_name IN ('students', 'instructors', 'courses', 'enrollments')\n      AND is_nullable = 'NO';\n\n    IF v_project_named_constraint_count <> 15\n       OR v_project_not_null_count <> 20 THEN\n        RAISE EXCEPTION\n            '최종 검증 실패: Chapter 07 구조 기준과 다릅니다. named_constraints=%, not_null_columns=%',\n            v_project_named_constraint_count, v_project_not_null_count;\n    END IF;\n\n"""
text = replace_once(text, anchor, addition, '08 upstream structure gate')
write(path, text)

# -----------------------------------------------------------------------------
# Code README and templates
# -----------------------------------------------------------------------------
path = 'code/chapter13/README.md'
text = read(path)
text = replace_once(
    text,
    '1005 = 신청 / 120000\n활성 신청 부분 고유 인덱스 존재\n활성 신청 중복 = 0',
    '1005 = 신청 / 120000\n활성 신청 부분 고유 인덱스 존재\n활성 신청 중복 = 0\nChapter 07 명명 제약조건 = 15\nChapter 07 NOT NULL 열 = 20\n현재 역할의 ai_database_book CREATE 권한 존재',
    'README prerequisite list',
)
text = replace_once(
    text,
    'Chapter 12의 `nosql_lab`도 Chapter 13 검증에서는 보호 대상입니다. 전용 자동 검증은 Chapter 12 기준 상태를 실제 생성한 뒤 Chapter 13 실행 전·후 fingerprint가 같은지 확인합니다.',
    '새 스키마를 만드는 `01_ai_review_lab_schema.sql`은 DDL 전에 현재 역할의 `ai_database_book` CREATE 권한도 확인합니다. Chapter 11의 `security_lab`이나 Chapter 12의 `nosql_lab` 존재 자체를 시작 조건으로 요구하지는 않습니다.\n\nChapter 12의 `nosql_lab`도 Chapter 13 검증에서는 보호 대상입니다. 전용 자동 검증은 Chapter 12 기준 상태를 실제 생성한 뒤 Chapter 13 실행 전·후 fingerprint가 같은지 확인합니다.',
    'README preflight explanation',
)
text = replace_once(
    text,
    '명시적 ID 입력은 IDENTITY 내부 시퀀스를 자동으로 이동시키지 않으므로 Seed 파일에서 `RESTART WITH`를 적용합니다. 반례 테스트는 명시적 테스트 ID를 사용하며 모두 하위 트랜잭션에서 자동 취소됩니다.',
    '`GENERATED BY DEFAULT AS IDENTITY` 컬럼에 명시적 ID를 넣으면 그 값이 우선 사용되므로 내부 시퀀스가 해당 값에 맞춰 자동 이동하지 않습니다. Seed 파일에서 `RESTART WITH`를 적용해 다음 자동값을 조정합니다. 반대로 자동 ID를 위해 시퀀스 값이 발급된 뒤 트랜잭션이 취소되더라도 그 값은 일반적으로 회수되지 않으므로 번호 공백은 정합성 오류로 보지 않습니다. 반례 테스트는 명시적 테스트 ID를 사용하며 모두 하위 트랜잭션에서 자동 취소됩니다.',
    'README identity explanation',
)
text = replace_once(
    text,
    'Chapter 07·08 canonical state 3/2/3/5',
    'Chapter 07·08 canonical state 3/2/3/5 + 명명 제약조건 15 + NOT NULL 열 20',
    'README final gate',
)
write(path, text)

path = 'code/chapter13/PROMPT_TEMPLATES.md'
text = read(path)
text = replace_once(
    text,
    '- Chapter 07 enrollments 5행 유지\n- bad_enrollments 3행',
    '- Chapter 07 enrollments 5행 유지\n- Chapter 07 명명 제약조건 15개 / NOT NULL 열 20개 유지\n- 01 생성 단계에서 현재 역할의 DB CREATE 권한 확인\n- bad_enrollments 3행',
    'prompt current baseline',
)
write(path, text)

path = 'code/chapter13/AI_REVIEW_REPORT_TEMPLATE.md'
text = read(path)
text = replace_once(
    text,
    '| Chapter 07 신청 | 5 |  |  |\n| ai_review_lab 생성 전 미존재 | true |  |  |',
    '| Chapter 07 신청 | 5 |  |  |\n| Chapter 07 명명 제약조건 | 15 |  |  |\n| Chapter 07 NOT NULL 열 | 20 |  |  |\n| 현재 역할 DB CREATE 권한 | 있음 |  |  |\n| ai_review_lab 생성 전 미존재 | true |  |  |',
    'report execution guards',
)
text = replace_once(
    text,
    '| 결제실패·금액 0·시각 NULL | 성공 |  |  |\n\n---',
    '| 결제실패·금액 0·시각 NULL | 성공 |  |  |\n| 대소문자 다른 학생 이메일 | 현재 정확 문자열 정책에서 성공 |  |  |\n\n---',
    'report sixth success',
)
write(path, text)

# -----------------------------------------------------------------------------
# Presentations
# -----------------------------------------------------------------------------
path = 'presentation/chapter13/chapter13_theory_lecture_plan.md'
text = read(path)
text = replace_once(
    text,
    '| ChatGPT | 요구사항 정리, 대안 비교, 검토 질문 | 미확정 정책 확정 |\n| Codex | 파일 탐색, SQL·테스트 작성, diff 지원 | 변경 자동 승인 |\n| 사람 | 정책 확인, 실행 결과·diff 검토 | 책임을 AI에 이전 |',
    '| ChatGPT Chat | 요구사항 정리, 대안 비교, 검토 질문 | 미확정 정책 확정 |\n| ChatGPT Work | 긴 다단계 검토, 자료 분석, 완성 산출물 작성 지원 | 실행 증거 없이 변경 승인 |\n| Codex | 파일 탐색, SQL·테스트 작성, diff 지원 | 변경 자동 승인 |\n| 사람 | 정책 확인, 실행 결과·diff 검토 | 책임을 AI에 이전 |',
    'theory role table',
)
text = replace_once(
    text,
    '현재 공식 안내의 큰 흐름은 Chat은 빠른 질의·대화, Work는 장시간 다단계 산출물, Codex는 코드·테스트·명령·저장소 작업에 초점을 둡니다. 기능과 사용 환경은 바뀔 수 있으므로 실제 사용 시 최신 공식 안내를 다시 확인합니다.',
    '2026년 8월 출판 검수 시점의 OpenAI 공식 안내는 Chat을 빠른 대화형 지원, Work를 더 길고 여러 단계인 작업과 완성된 산출물, Codex를 소프트웨어 개발·기술 작업에 맞춘 환경으로 설명합니다. 제공 범위는 플랜·워크스페이스·사용 화면에 따라 달라질 수 있으므로 실제 사용 시 최신 공식 안내를 다시 확인합니다.',
    'theory product guidance',
)
text = replace_once(
    text,
    '생성·검증 대상:\nai_review_lab',
    '생성·검증 대상:\nai_review_lab\n\n시작 게이트:\nChapter 07 canonical 데이터\n+ 명명 제약조건 15 / NOT NULL 20\n+ 현재 역할 DB CREATE 권한',
    'theory isolated gate screen',
)
text = replace_once(
    text,
    '챕터 13은 `ai_review_lab`이라는 격리 스키마에서만 실행합니다. 앞 장의 모든 스키마는 변경 금지입니다.',
    '챕터 13은 `ai_review_lab`이라는 격리 스키마에서만 실행합니다. 앞 장의 모든 스키마는 변경 금지입니다. 01 파일은 스키마를 만들기 전에 Chapter 07 구조 계약과 현재 역할의 DB CREATE 권한도 확인합니다.',
    'theory isolated gate script',
)
text = text.replace('예상 실패 22개\n+ 정상 경계값 6개', '예상 실패 24개\n+ 정상 경계값 6개')
text = replace_once(
    text,
    'payment_reference는 비민감 외부 참조값',
    'payment_reference는 실습용 가상 외부 참조값\n실제 보호 수준은 조직 정책으로 판단',
    'theory payment reference',
)
write(path, text)

path = 'presentation/chapter13/chapter13_practice_lecture_plan.md'
text = read(path)
text = replace_once(
    text,
    '변경 금지: course_project, transaction_lab, performance_lab, security_lab, nosql_lab\n생성 대상: ai_review_lab',
    '변경 금지: course_project, transaction_lab, performance_lab, security_lab, nosql_lab\n생성 대상: ai_review_lab\n시작 게이트: Chapter 07 구조 15/20 + 현재 역할 DB CREATE 권한',
    'practice guard screen',
)
text = replace_once(
    text,
    '중요한 것은 에이아이 검토 실습이 앞 장 데이터를 건드리지 않는다는 점입니다.',
    '중요한 것은 에이아이 검토 실습이 앞 장 데이터를 건드리지 않는다는 점입니다. 01 파일은 Chapter 07 canonical 데이터와 구조 계약을 확인하고, 새 스키마 생성에 필요한 DB CREATE 권한이 없으면 DDL 전에 중단합니다.',
    'practice guard script',
)
text = text.replace('| `payments` | 현재 결제 상태·외부 참조값 |', '| `payments` | 현재 결제 상태·가상 외부 참조값 |')
text = replace_once(
    text,
    '명시적 아이디를 사용하기 때문에 관계를 쉽게 확인할 수 있습니다. 하지만 명시적 아이디 입력은 아이덴티티 다음 값을 자동으로 이동시키지 않습니다.\n\n그래서 Seed 파일이 `RESTART WITH`로 다음 자동값을 맞췄는지 확인합니다.',
    '명시적 아이디를 사용하기 때문에 관계를 쉽게 확인할 수 있습니다. 이 장의 `GENERATED BY DEFAULT AS IDENTITY`에서는 직접 지정한 값이 우선 사용되므로 내부 시퀀스가 그 값에 맞춰 자동 이동하지 않습니다.\n\n그래서 Seed 파일이 `RESTART WITH`로 다음 자동값을 맞췄는지 확인합니다. 반대로 자동값이 발급된 뒤 트랜잭션이 취소되어 생긴 번호 공백은 오류로 보지 않습니다.',
    'practice identity script',
)
text = replace_once(
    text,
    '완료·취소 뒤 재신청',
    '완료·취소 뒤 재신청\n대소문자 다른 학생 이메일은 현재 정확 문자열 정책에서 성공',
    'practice boundary list',
)
text = replace_once(
    text,
    'Chapter 07 신청 5행 유지\n기준 행 수 3/3/2/3/4/4',
    'Chapter 07 신청 5행 유지\nChapter 07 구조 = 명명 제약조건 15 / NOT NULL 20\n기준 행 수 3/3/2/3/4/4',
    'practice final gate',
)
write(path, text)

path = 'presentation/chapter13/chapter13_script.html'
text = read(path)
text = replace_once(text, '<body>', '<body data-script-content-enhancer="off">', 'script enhancer opt-out')
write(path, text)

# -----------------------------------------------------------------------------
# Image README
# -----------------------------------------------------------------------------
path = 'images/chapter13/README.md'
text = read(path)
text = text.replace('ChatGPT·Codex의 역할은 절대적 기능 경계가 아니라 권장 흐름으로 표현한다.', 'ChatGPT Chat·Work·Codex의 역할은 절대적 기능 경계가 아니라 권장 흐름으로 표현한다.')
text = replace_once(
    text,
    '정상 JOIN 4\nFK 4\n반례 17\nunexpected 0',
    '정상 JOIN 4\nFK 4\n예상 실패 24\n정상 경계값 6\n전체 30 / 통과 30\nunexpected 0',
    'image README test baseline',
)
write(path, text)

# -----------------------------------------------------------------------------
# Review/revision record: add publication refinement note
# -----------------------------------------------------------------------------
path = 'book/chapter13/chapter13_review_revision.md'
text = read(path)
append = """

---

## 18. 2026-08-10 최종 출판 정밀 검수 추가 반영

Chapter 12 최종 출판 검수에서 강화한 실행 안전성 기준을 Chapter 13에도 연결하고, 2026년 8월 OpenAI 공식 제품 안내와 PostgreSQL 16 공식 문서를 다시 대조했습니다.

추가 반영:

```text
ChatGPT Chat / Work / Codex 역할을 2026년 8월 공식 안내 기준으로 최신화
제품 기능·제공 범위는 플랜·워크스페이스·사용 화면에 따라 바뀔 수 있음을 명시
Chapter 07 구조 계약 = 명명 제약조건 15 / NOT NULL 열 20
ai_review_lab 생성 전 현재 역할 DB CREATE 권한 확인
08 최종 게이트에서 Chapter 07 구조·recorded_amount·활성 신청 정책 재확인
워크북의 오래된 예상 실패 22 → 24 수정
워크북 total 27 → 30 수정
T30 대소문자 이메일 정상 경계값을 워크북·보고서 템플릿에 추가
이미지 README의 오래된 반례 17 기준을 24 실패 + 6 성공 = 30으로 수정
payment_reference를 자동 비민감 값으로 단정하지 않고 실제 보호 수준은 조직 정책으로 판단
GENERATED BY DEFAULT AS IDENTITY와 명시적 ID·시퀀스·ROLLBACK 번호 공백 설명 정밀화
작성된 발표자 스크립트의 generic content enhancer 비활성화
```

최종 자동 실행 결과는 `notes/chapter13_validation_result.md`와 `notes/chapter13_review_checklist.md`에 별도로 기록합니다.
"""
if '## 18. 2026-08-10 최종 출판 정밀 검수 추가 반영' not in text:
    text += append
write(path, text)

# -----------------------------------------------------------------------------
# Review checklist: add new criteria but leave run metadata for post-validation update
# -----------------------------------------------------------------------------
path = 'notes/chapter13_review_checklist.md'
text = read(path)
text = replace_once(
    text,
    '| 활성 신청 인덱스 | 존재 | 실제 통과 |\n| transaction_lab | 변경 없음 | sentinel 통과 |',
    '| 활성 신청 인덱스 | 존재 | 실제 통과 |\n| Chapter 07 명명 제약조건 | 15 | 최종 재검증 대상 |\n| Chapter 07 NOT NULL 열 | 20 | 최종 재검증 대상 |\n| 현재 역할 DB CREATE 권한 | 생성 전 확인 | 최종 재검증 대상 |\n| transaction_lab | 변경 없음 | sentinel 통과 |',
    'checklist guards',
)
text = text.replace('| Chat: 빠른 질문·대화형 지원 | 반영 |', '| Chat: 빠른 질문·대화형 지원 | 반영 |\n| Work: 긴 다단계 작업·완성 산출물 | 반영 |')
text = text.replace('| payment_reference 자동 비민감 단정 금지 | 반영 |', '| payment_reference 자동 비민감 단정 금지 | 반영 |')
append = """

---

## 20. 2026-08-10 최종 출판 재검증 항목

```text
OpenAI 공식 안내 기준 Chat / Work / Codex 역할 최신화
Chapter 07 구조 계약 15 / 20 인계 확인
DB CREATE 권한 없는 역할에서 01이 DDL 전에 실패하는지 확인
권한 실패 뒤 ai_review_lab이 생성되지 않았는지 확인
08에서 Chapter 07 구조·recorded_amount·활성 신청 정책 재확인
워크북 24 실패 + 6 성공 = 30 정합성
T30 대소문자 이메일 정상 경계값 문서 동기화
이미지 README 30개 테스트 기준 동기화
발표자 스크립트 generic enhancer 비활성화
PostgreSQL 16 전체 01→08 재실행
protected schema fingerprint·reset 원자성 재확인
```

실제 Run ID와 최종 결과는 재검증 완료 후 갱신합니다.
"""
if '## 20. 2026-08-10 최종 출판 재검증 항목' not in text:
    text += append
write(path, text)

# -----------------------------------------------------------------------------
# Permanent Chapter 13 workflow: static guards + executable preflight tests
# -----------------------------------------------------------------------------
path = '.github/workflows/validate-chapter13.yml'
text = read(path)
static_anchor = """          print(f'Chapter 13 static alignment passed: body={len(numbered)}, theory=20, practice=20, assets={len(svgs)}, version={version}')\n"""
static_checks = """          if '예상 실패 22개' in activity or '예상 실패 22개' in theory:\n              raise SystemExit('Chapter 13 contains stale expected-failure count 22')\n          if '### 예상 실패 24개' not in activity or '| total | 30 |' not in activity:\n              raise SystemExit('Chapter 13 workbook must use 24 failures and total 30')\n          if '반례 17' in image_readme or '예상 실패 24' not in image_readme or '정상 경계값 6' not in image_readme:\n              raise SystemExit('Chapter 13 image README test baseline is stale')\n          if '2026년 8월 출판 검수 시점의 OpenAI 공식 안내' not in chapter:\n              raise SystemExit('Chapter 13 body missing dated OpenAI product-scope note')\n          if 'ChatGPT Work' not in chapter or 'ChatGPT Work' not in theory:\n              raise SystemExit('Chapter 13 Chat/Work/Codex role alignment missing')\n          if 'data-script-content-enhancer=\"off\"' not in script_html:\n              raise SystemExit('Chapter 13 authored presenter script must disable generic enhancer')\n          for token in [\n              \"has_database_privilege(current_user, current_database(), 'CREATE')\",\n              'v_project_named_constraint_count <> 15',\n              'v_project_not_null_count <> 20',\n          ]:\n              if token not in sql['01_ai_review_lab_schema.sql']:\n                  raise SystemExit(f'01 missing final preflight token {token}')\n          for token in ['v_project_named_constraint_count <> 15', 'v_project_not_null_count <> 20']:\n              if token not in sql['08_ai_review_lab_validation.sql']:\n                  raise SystemExit(f'08 missing upstream structure token {token}')\n\n""" + static_anchor
text = replace_once(text, static_anchor, static_checks, 'workflow static checks')
step_anchor = """      - name: Build Chapter 12 handoff state\n"""
new_steps = """      - name: Verify inherited Chapter 07 structure contract\n        shell: bash\n        run: |\n          STRUCTURE=$(psql -d ai_database_book -At -v ON_ERROR_STOP=1 <<'SQL'\n          SELECT\n            (SELECT COUNT(*) FROM pg_constraint\n             WHERE conrelid IN ('course_project.students'::regclass,'course_project.instructors'::regclass,'course_project.courses'::regclass,'course_project.enrollments'::regclass)\n               AND conname IN (\n                 'uq_course_students_email','chk_course_students_name_not_blank','chk_course_students_email_not_blank',\n                 'uq_course_instructors_email','chk_course_instructors_name_not_blank','chk_course_instructors_email_not_blank','chk_course_instructors_specialty_not_blank',\n                 'fk_course_courses_instructor','chk_course_courses_title_not_blank','chk_course_courses_level','chk_course_courses_price',\n                 'fk_course_enrollments_student','fk_course_enrollments_course','chk_course_enrollments_status','chk_course_enrollments_recorded_amount'\n               )) || ':' ||\n            (SELECT COUNT(*) FROM information_schema.columns\n             WHERE table_schema='course_project' AND table_name IN ('students','instructors','courses','enrollments') AND is_nullable='NO');\n          SQL\n          )\n          echo \"Chapter 07 structure contract: $STRUCTURE\"\n          test \"$STRUCTURE\" = \"15:20\"\n\n      - name: Verify Chapter 13 CREATE privilege guard before DDL\n        shell: bash\n        run: |\n          psql -v ON_ERROR_STOP=1 -d ai_database_book <<'SQL'\n          CREATE ROLE ch13_no_create LOGIN PASSWORD 'chapter13-test';\n          GRANT CONNECT ON DATABASE ai_database_book TO ch13_no_create;\n          REVOKE CREATE ON DATABASE ai_database_book FROM ch13_no_create;\n          GRANT USAGE ON SCHEMA course_project TO ch13_no_create;\n          GRANT SELECT ON ALL TABLES IN SCHEMA course_project TO ch13_no_create;\n          SQL\n          set +e\n          PGUSER=ch13_no_create PGPASSWORD=chapter13-test \\\n            psql -h localhost -d ai_database_book -v ON_ERROR_STOP=1 \\\n            -f code/chapter13/01_ai_review_lab_schema.sql > /tmp/ch13_no_create.log 2>&1\n          status=$?\n          set -e\n          cat /tmp/ch13_no_create.log\n          test \"$status\" -ne 0\n          grep -q \"CREATE 권한\" /tmp/ch13_no_create.log\n          test \"$(psql -d ai_database_book -Atc \"SELECT to_regnamespace('ai_review_lab') IS NULL\")\" = \"t\"\n\n""" + step_anchor
text = replace_once(text, step_anchor, new_steps, 'workflow executable guards')
write(path, text)

print('Chapter 13 final publication review patch applied')
