-- Chapter 05. 요구사항에서 데이터 모델과 ERD 만들기
-- 목적: 도서 대여 시스템 ERD를 PostgreSQL 테이블 구조로 구현합니다.
-- 범위: books 한 행을 하나의 대여 대상 도서로 취급하며 복본 구분은 다루지 않습니다.
-- 주의: 이 파일은 기존 테이블이나 데이터를 자동으로 삭제하지 않습니다.

-- ============================================================
-- 0. 현재 실행 위치 확인
-- 기대 결과: ai_database_book / public
-- ============================================================
SELECT current_database();
SELECT current_schema();

-- ============================================================
-- 1. 회원 테이블
-- ============================================================
CREATE TABLE members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    joined_at DATE NOT NULL
);

-- ============================================================
-- 2. 도서 테이블
-- ============================================================
CREATE TABLE books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    published_year INTEGER,
    isbn VARCHAR(20) UNIQUE NOT NULL
);

-- ============================================================
-- 3. 대여 사건 테이블
-- member_id와 book_id는 반드시 기존 회원과 도서를 참조합니다.
-- returned_at은 미반납 상태를 표현하기 위해 NULL을 허용합니다.
-- ============================================================
CREATE TABLE loans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL REFERENCES members(id),
    book_id INTEGER NOT NULL REFERENCES books(id),
    borrowed_at DATE NOT NULL,
    due_at DATE NOT NULL,
    returned_at DATE
);

-- 생성 후 DBeaver에서 다음 구조를 확인합니다.
-- Schemas -> public -> Tables -> members, books, loans
