-- Chapter 05 호환 파일: 01_library_schema.sql과 같은 역할
-- 기존 링크와 강의 자료 호환을 위해 유지합니다.
-- 번호 파일과 이 파일을 모두 실행하지 마세요.
-- 세 테이블 생성은 하나의 트랜잭션으로 묶어 중간 실패 시 부분 생성 상태를 남기지 않습니다.

SELECT current_database();
SELECT current_user;
SELECT current_schema();
SHOW search_path;

BEGIN;

DO $$
BEGIN
    IF current_database() <> 'ai_database_book' THEN
        RAISE EXCEPTION
            '생성 중단: 현재 데이터베이스는 %입니다. ai_database_book에 연결하세요.',
            current_database();
    END IF;

    IF current_setting('transaction_read_only')::boolean THEN
        RAISE EXCEPTION
            '생성 중단: 현재 연결이 읽기 전용입니다.';
    END IF;

    IF to_regnamespace('public') IS NULL THEN
        RAISE EXCEPTION
            '생성 중단: public 스키마가 존재하지 않습니다.';
    END IF;

    IF to_regclass('public.members') IS NOT NULL
       OR to_regclass('public.books') IS NOT NULL
       OR to_regclass('public.loans') IS NOT NULL THEN
        RAISE EXCEPTION
            '생성 중단: Chapter 05 테이블 중 하나 이상이 이미 존재합니다. 기존 상태를 확인하거나 reset_library.sql을 검토하세요.';
    END IF;
END
$$;

CREATE TABLE public.members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    joined_at DATE NOT NULL
);

CREATE TABLE public.books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    published_year INTEGER,
    isbn VARCHAR(20) NOT NULL
);

CREATE TABLE public.loans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL REFERENCES public.members(id),
    book_id INTEGER NOT NULL REFERENCES public.books(id),
    borrowed_at DATE NOT NULL,
    due_at DATE NOT NULL,
    returned_at DATE
);

DO $$
DECLARE
    v_member_count bigint;
    v_book_count bigint;
    v_loan_count bigint;
BEGIN
    IF to_regclass('public.members') IS NULL
       OR to_regclass('public.books') IS NULL
       OR to_regclass('public.loans') IS NULL THEN
        RAISE EXCEPTION '생성 검증 실패: 세 테이블이 모두 생성되지 않았습니다.';
    END IF;

    SELECT COUNT(*) INTO v_member_count FROM public.members;
    SELECT COUNT(*) INTO v_book_count FROM public.books;
    SELECT COUNT(*) INTO v_loan_count FROM public.loans;

    IF v_member_count <> 0 OR v_book_count <> 0 OR v_loan_count <> 0 THEN
        RAISE EXCEPTION
            '생성 검증 실패: 새 테이블이 비어 있지 않습니다. members=%, books=%, loans=%',
            v_member_count, v_book_count, v_loan_count;
    END IF;
END
$$;

COMMIT;

SELECT
    to_regclass('public.members') AS members_table,
    to_regclass('public.books') AS books_table,
    to_regclass('public.loans') AS loans_table;
