-- Chapter 05. 요구사항에서 데이터 모델과 ERD 만들기
-- 목적: 도서 대여 시스템 ERD를 PostgreSQL 테이블 구조로 구현합니다.
-- 범위: books 한 행을 하나의 대여 대상 도서로 취급하며 복본 구분은 다루지 않습니다.
-- 주의: 이 파일은 기존 테이블이나 데이터를 자동으로 삭제하지 않습니다.
-- 주의: 자동 커밋 상태에서는 앞 테이블이 생성된 뒤 뒤 문장에서 오류가 날 수 있습니다.

-- ============================================================
-- 0. 현재 실행 위치 확인
-- 기대 결과: ai_database_book / public
-- ============================================================
SELECT current_database();
SELECT current_schema();
SHOW search_path;

-- ============================================================
-- 1. 회원 테이블
-- email의 고유성은 요구사항에서 아직 확정되지 않았으므로
-- Chapter 05에서는 UNIQUE를 적용하지 않습니다.
-- ============================================================
CREATE TABLE public.members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    joined_at DATE NOT NULL
);

-- ============================================================
-- 2. 도서 테이블
-- isbn의 고유성, ISBN이 없는 도서와 동일 ISBN 복본 정책은 미확정입니다.
-- Chapter 05에서는 ISBN을 저장하되 UNIQUE를 적용하지 않습니다.
-- ============================================================
CREATE TABLE public.books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    published_year INTEGER,
    isbn VARCHAR(20) NOT NULL
);

-- ============================================================
-- 3. 대여 사건 테이블
-- member_id와 book_id는 반드시 기존 회원과 도서를 참조합니다.
-- returned_at은 미반납 상태를 표현하기 위해 NULL을 허용합니다.
-- 날짜 선후 관계와 동시 대여 방지 규칙은 Chapter 06에서 검토합니다.
-- ============================================================
CREATE TABLE public.loans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL REFERENCES public.members(id),
    book_id INTEGER NOT NULL REFERENCES public.books(id),
    borrowed_at DATE NOT NULL,
    due_at DATE NOT NULL,
    returned_at DATE
);

-- 생성 후 DBeaver에서 다음 구조를 확인합니다.
-- Schemas -> public -> Tables -> members, books, loans
